-- Maintenance schema — προετοιμασία για το import ιστορικού συντήρησης
-- Αποφάσεις owner: docs/data-cleanup/MAINT-HISTORY-ANALYSIS-2026-08-05.md §6
-- 2026-08-05 · ΔΕΝ έχει εκτελεστεί ακόμη — αναμένει έγκριση owner
--
-- Εκτέλεση: Supabase → SQL Editor. Όλα τα βήματα είναι idempotent (IF NOT EXISTS).
-- Καμία απώλεια δεδομένων: το maint_history είναι άδειο (0 εγγραφές, 2026-08-05).

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────
-- 1. WORKSHOPS — λείπουν πεδία που χρειάζεται ο owner
-- ─────────────────────────────────────────────────────────────────────────────
-- Ο owner ετοιμάζει ΑΦΜ ανά συνεργείο· δεν υπάρχει στήλη. Τα aliases κρατούν τις
-- 107 raw παραλλαγές του Excel ώστε το επόμενο import να είναι αυτόματο.

ALTER TABLE workshops ADD COLUMN IF NOT EXISTS tax_id      text;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS legal_name  text;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS country     text;
ALTER TABLE workshops ADD COLUMN IF NOT EXISTS aliases     text[] DEFAULT '{}';

COMMENT ON COLUMN workshops.tax_id     IS 'ΑΦΜ';
COMMENT ON COLUMN workshops.legal_name IS 'Πλήρης επωνυμία· το name μένει το συνηθισμένο όνομα';
COMMENT ON COLUMN workshops.country    IS 'GR | BG — υπάρχουν συνεργεία Βουλγαρίας';
COMMENT ON COLUMN workshops.aliases    IS 'Raw ονόματα από τις καρτέλες Excel, για αυτόματη αντιστοίχιση σε μελλοντικά imports';

-- Αναζήτηση aliases κατά το import
CREATE INDEX IF NOT EXISTS workshops_aliases_idx ON workshops USING gin (aliases);

-- ΑΦΜ μοναδικό όπου δηλώνεται (επιτρέπονται πολλά NULL)
CREATE UNIQUE INDEX IF NOT EXISTS workshops_tax_id_key
  ON workshops (tax_id) WHERE tax_id IS NOT NULL AND deleted_at IS NULL;


-- ─────────────────────────────────────────────────────────────────────────────
-- 2. MAINT_HISTORY — πραγματικό FK προς το όχημα
-- ─────────────────────────────────────────────────────────────────────────────
-- Τα trucks και trailers είναι ΔΥΟ ξεχωριστοί πίνακες, άρα ένα σκέτο vehicle_id
-- δεν μπορεί να έχει referential integrity. Δύο nullable FK + CHECK ώστε να είναι
-- πάντα συμπληρωμένο ακριβώς ένα από τα δύο.
--
-- Το vehicle_plate ΜΕΝΕΙ ως denormalized στήλη για εμφάνιση/αναζήτηση — αλλά
-- παύει να είναι ο σύνδεσμος. Λύνει τον κίνδυνο του HANDOFF.md: αλλαγή πινακίδας
-- δεν ορφανεύει πια το ιστορικό.

ALTER TABLE maint_history ADD COLUMN IF NOT EXISTS truck_id   bigint REFERENCES trucks(id);
ALTER TABLE maint_history ADD COLUMN IF NOT EXISTS trailer_id bigint REFERENCES trailers(id);

CREATE INDEX IF NOT EXISTS maint_history_truck_idx   ON maint_history (truck_id)   WHERE truck_id   IS NOT NULL;
CREATE INDEX IF NOT EXISTS maint_history_trailer_idx ON maint_history (trailer_id) WHERE trailer_id IS NOT NULL;

-- Ακριβώς ένα όχημα ανά εγγραφή.
-- NOT VALID: δεν ελέγχει υπάρχουσες γραμμές (ο πίνακας είναι άδειος, αλλά έτσι η
-- εντολή είναι ασφαλής και αν τρέξει ξανά αργότερα).
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'maint_history_one_vehicle') THEN
    ALTER TABLE maint_history
      ADD CONSTRAINT maint_history_one_vehicle
      CHECK (num_nonnulls(truck_id, trailer_id) = 1) NOT VALID;
  END IF;
END $$;

-- Ίχνος προέλευσης του import (αναστρεψιμότητα — §5.4 της ανάλυσης)
ALTER TABLE maint_history ADD COLUMN IF NOT EXISTS source_ref   text;
ALTER TABLE maint_history ADD COLUMN IF NOT EXISTS needs_review boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN maint_history.source_ref   IS 'Αρχείο/φύλλο/γραμμές Excel από όπου προήλθε η εγγραφή';
COMMENT ON COLUMN maint_history.needs_review IS 'Προβληματικό δεδομένο στην πηγή (ημερομηνία, κόστος, χλμ από κείμενο)';

CREATE INDEX IF NOT EXISTS maint_history_needs_review_idx
  ON maint_history (needs_review) WHERE needs_review;


-- ─────────────────────────────────────────────────────────────────────────────
-- 3. MAINT_PLAN — preventive tracking (κατάσταση, όχι ιστορικό)
-- ─────────────────────────────────────────────────────────────────────────────
-- Μία εγγραφή ανά όχημα, update-in-place. Απόφαση owner: μόνο φορτηγά με χλμ (35).
-- Το next_service_km ΔΕΝ αποθηκεύεται — είναι παράγωγο, αλλιώς ξεσυγχρονίζεται
-- (στο Excel ήδη είχε αποκλίσεις).

CREATE TABLE IF NOT EXISTS maint_plan (
  id                       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  truck_id                 bigint NOT NULL UNIQUE REFERENCES trucks(id),
  service_interval_km      integer NOT NULL,
  last_service_date        date,
  last_service_odometer_km integer,
  current_odometer_km      integer,
  odometer_reading_date    date,
  notes                    text,
  created_at               timestamptz NOT NULL DEFAULT now(),
  updated_at               timestamptz NOT NULL DEFAULT now(),
  deleted_at               timestamptz,
  CONSTRAINT maint_plan_interval_positive CHECK (service_interval_km > 0)
);

COMMENT ON TABLE  maint_plan IS 'Κατάσταση preventive συντήρησης ανά φορτηγό. Update-in-place — ΔΕΝ είναι ιστορικό.';
COMMENT ON COLUMN maint_plan.service_interval_km IS '60000 MAN/Scania S660/Ford · 75000 Volvo FH500 · 90000 Scania CB0142HO';

-- Παράγωγα: όριο επόμενου σέρβις και υπόλοιπο χιλιομέτρων
CREATE OR REPLACE VIEW maint_plan_status AS
SELECT p.*,
       t.license_plate,
       t.brand,
       t.model,
       (p.last_service_odometer_km + p.service_interval_km)                         AS next_service_km,
       (p.last_service_odometer_km + p.service_interval_km - p.current_odometer_km) AS km_remaining
FROM   maint_plan p
JOIN   trucks t ON t.id = p.truck_id
WHERE  p.deleted_at IS NULL;

COMMIT;


-- ─────────────────────────────────────────────────────────────────────────────
-- ΣΗΜΕΙΩΣΕΙΣ — δεν εκτελούνται
-- ─────────────────────────────────────────────────────────────────────────────
-- · Το maint_history.type παραμένει free text στη βάση. Οι 8 νέες κατηγορίες
--   επιβάλλονται από το UI (modules/maintenance.js). Δεν μπαίνει CHECK ώστε να
--   μη «σπάσει» η βάση αν αλλάξει η λίστα — η ταξινομία είναι απόφαση προϊόντος.
-- · Δεν αγγίζεται το maint_history.vehicle_plate / vehicle_type — μένουν ως έχουν
--   για συμβατότητα με τον υπάρχοντα κώδικα.
-- · Οι 2 δοκιμαστικές εγγραφές workshops ('ZZ 0013 stg', 'upd') θέλουν καθάρισμα
--   πριν το import — ξεχωριστό βήμα, με έγκριση owner.
