-- ═══════════════════════════════════════════════════════════════════════
-- LOCAL_MOVES — τοπικές κινήσεις
-- 2026-08-10 · Weekly National v3, Φ5α · SPEC §Δ18
--
-- ΤΙ ΕΙΝΑΙ
-- Οι κινήσεις που στο Excel ζουν στην ενότητα «ΤΟΠΙΚΑ ΔΡΟΜΟΛΟΓΙΑ»: ημερήσιες
-- μετακινήσεις κοντινών αποστάσεων, συχνά κομμάτια εθνικών ή διεθνών
-- δρομολογίων που αναλαμβάνει τοπικός οδηγός. Παράδειγμα W31: ο Δούμος τη
-- Δευτέρα κάνει Αθήνα→Σίνδος (φορτίο Δελατόλα) και Θεσσαλονίκη→Αλεξάνδρεια
-- (2 κιβώτια Άλμη).
--
-- ΓΙΑΤΙ ΝΕΟΣ ΠΙΝΑΚΑΣ ΚΑΙ ΟΧΙ NATIONAL_LOADS
-- 1. Το `direction` έχει ΔΥΟ τιμές (North→South / South→North) και
--    φιλτράρεται σε 20 σημεία μέσα σε 4 αρχεία (weekly_natl, orders_natl,
--    daily_ramp, ai-chat). Τρίτη τιμή «ΤΟΠΙΚΟ» σημαίνει έλεγχο και στα 20 —
--    και όποιο ξεχαστεί, οι τοπικές είτε εξαφανίζονται είτε διπλομετρούνται,
--    ΣΙΩΠΗΛΑ.
-- 2. Θεσσαλονίκη→Αλεξάνδρεια δεν είναι ούτε βορράς-νότος ούτε το αντίστροφο.
-- 3. Μια τοπική κίνηση συχνά δεν έχει ΚΑΝΕΝΑΝ πελάτη και ΚΑΜΙΑ παραγγελία,
--    ενώ το national_loads είναι χτισμένο γύρω από πολυμορφικό γονέα.
-- 4. Το national_loads είναι η επιφάνεια σχεδιασμού των εθνικών φορτίων.
--    Κάθε μέτρηση που μετράει «φορτία» θα άρχιζε να μετράει και τα θελήματα
--    του οδηγού γραφείου.
--
-- ΑΣΦΑΛΕΙΑ: καθαρά προσθετικό. Κανένας υπάρχων πίνακας δεν αγγίζεται.
-- ═══════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE IF NOT EXISTS public.local_moves (
  id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Η γραμμή του Weekly National είναι «οδηγός × ημέρα» (SPEC Δ7):
  -- move_date ομαδοποιεί, sequence δίνει τη σειρά μέσα στη μέρα.
  move_date           date     NOT NULL,
  sequence            smallint NOT NULL DEFAULT 1,

  driver_id           bigint REFERENCES public.drivers(id),
  truck_id            bigint REFERENCES public.trucks(id),
  trailer_id          bigint REFERENCES public.trailers(id),
  partner_id          bigint REFERENCES public.partners(id),

  from_location_id    bigint REFERENCES public.locations(id),
  to_location_id      bigint REFERENCES public.locations(id),

  -- «2 κιβώτια Άλμη», «μοίρασμα IFCO» — ό,τι γράφεται σήμερα στο χέρι.
  description         text,
  pallets             numeric,

  -- Ώρες ρολογιού τοίχου (HH:MM), όπως τα ραντεβού των NAT_LOADS. Το κείμενο
  -- περνά αυτούσιο μέσα από τον facade και δεν κουβαλά ζώνη ώρας.
  time_from           text,
  time_to             text,

  -- ΟΙ ΔΥΟ ΓΟΝΕΙΣ (SPEC Δ6/Δ8). Και οι δύο NULL = ΑΥΤΟΤΕΛΗΣ τοπική κίνηση,
  -- π.χ. ΚΑΡΑΜΟΛΕΓΚΟΣ → ΝΕΑ ΜΟΥΔΑΝΙΑ. Ένας από τους δύο = η κίνηση
  -- εξυπηρετεί κομμάτι άλλου δρομολογίου, και η σύνδεση φαίνεται ΚΑΙ ΑΠΟ ΤΙΣ
  -- ΔΥΟ πλευρές στο εβδομαδιαίο.
  parent_nat_load_id  bigint REFERENCES public.national_loads(id),
  parent_order_id     bigint REFERENCES public.orders(id),

  status              text NOT NULL DEFAULT 'Pending',
  notes               text,

  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  deleted_at          timestamptz,

  -- Ίδιος κανόνας με τον πολυμορφικό γονέα των national_loads: ποτέ και τα
  -- δύο. Μια κίνηση εξυπηρετεί ένα πράγμα, ή τίποτα.
  CONSTRAINT local_moves_one_parent
    CHECK (parent_nat_load_id IS NULL OR parent_order_id IS NULL),

  CONSTRAINT local_moves_time_from_fmt
    CHECK (time_from IS NULL OR time_from ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$'),
  CONSTRAINT local_moves_time_to_fmt
    CHECK (time_to   IS NULL OR time_to   ~ '^([01][0-9]|2[0-3]):[0-5][0-9]$')
);

-- Το εβδομαδιαίο ρωτά ΠΑΝΤΑ «οι κινήσεις αυτής της εβδομάδας»: ένα εύρος
-- move_date. Αυτό είναι το index που μετράει.
CREATE INDEX IF NOT EXISTS local_moves_date_idx
  ON public.local_moves (move_date) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS local_moves_driver_idx
  ON public.local_moves (driver_id) WHERE driver_id IS NOT NULL AND deleted_at IS NULL;

-- Για το chip «καλύπτεται τοπικά» στο γονικό σκέλος: από ένα φορτίο προς τις
-- τοπικές κινήσεις που το εξυπηρετούν.
CREATE INDEX IF NOT EXISTS local_moves_parent_nl_idx
  ON public.local_moves (parent_nat_load_id) WHERE parent_nat_load_id IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS local_moves_parent_order_idx
  ON public.local_moves (parent_order_id) WHERE parent_order_id IS NOT NULL AND deleted_at IS NULL;

COMMENT ON TABLE public.local_moves IS
  'Τοπικές κινήσεις — η ενότητα ΤΟΠΙΚΑ ΔΡΟΜΟΛΟΓΙΑ του Weekly National. Χωριστά από national_loads: δεν έχουν κατεύθυνση βορρά-νότου και συχνά ούτε πελάτη ούτε παραγγελία.';
COMMENT ON COLUMN public.local_moves.sequence IS
  'Σειρά της κίνησης μέσα στη μέρα του οδηγού (1η, 2η…).';
COMMENT ON COLUMN public.local_moves.parent_nat_load_id IS
  'Το εθνικό φορτίο που εξυπηρετεί η κίνηση. NULL μαζί με parent_order_id = αυτοτελής.';
COMMENT ON COLUMN public.local_moves.parent_order_id IS
  'Η διεθνής παραγγελία που εξυπηρετεί η κίνηση. NULL μαζί με parent_nat_load_id = αυτοτελής.';

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════
-- ΜΕΤΑ ΤΟ MIGRATION — τρία βήματα, με ΑΥΤΗ τη σειρά
--
-- 0) RLS — ΕΛΕΓΞΕ ΠΡΩΤΑ τι ισχύει στους αδελφούς πίνακες. Δεν το ορίζω εδώ
--    γιατί δεν το βλέπω από το repo, και ένας πίνακας χωρίς policies είτε
--    είναι ορθάνοιχτος είτε εντελώς κλειστός — και τα δύο είναι λάθος:
--
--      SELECT relname, relrowsecurity
--        FROM pg_class
--       WHERE relname IN ('national_loads','local_moves');
--
--      SELECT polname, polcmd FROM pg_policy
--       WHERE polrelid = 'public.national_loads'::regclass;
--
--    Αντέγραψε το ΙΔΙΟ σχήμα policies με το national_loads.
--
-- 1) WORKER — νέο μπλοκ πίνακα. Τα labels είναι Airtable-style, όπως τα
--    χρησιμοποιεί το frontend:
--
--    local_moves: {
--      name: "LOCAL MOVES",
--      pg: "local_moves",
--      fields: {
--        "Date": "move_date", "Sequence": "sequence",
--        "Description": "description", "Pallets": "pallets",
--        "Time From": "time_from", "Time To": "time_to",
--        "Status": "status", "Notes": "notes"
--      },
--      links: {
--        Driver:  { column: "driver_id",  table: "drivers"  },
--        Truck:   { column: "truck_id",   table: "trucks"   },
--        Trailer: { column: "trailer_id", table: "trailers" },
--        Partner: { column: "partner_id", table: "partners" },
--        "From Location": { column: "from_location_id", table: "locations" },
--        "To Location":   { column: "to_location_id",   table: "locations" },
--        "Parent Nat Load": { column: "parent_nat_load_id", table: "national_loads" },
--        "Parent Order":    { column: "parent_order_id",    table: "orders" }
--      }
--    }
--
--    Και δικαιώματα: local_moves: ["GET","POST","PATCH","DELETE"].
--
-- 2) FRONTEND — TABLES.LOCAL_MOVES στο config.js, μετά η ενότητα ΤΟΠΙΚΑ στο
--    weekly_natl.js (φέτα 5).
--
-- ΕΛΕΓΧΟΣ ότι πέρασε:
--   SELECT count(*) FROM public.local_moves;               -- 0
--   SELECT conname FROM pg_constraint
--    WHERE conrelid = 'public.local_moves'::regclass;      -- 3 CHECK + FKs
-- ═══════════════════════════════════════════════════════════════════════
