// Generates schema.sql (PGlite fixture) from columns-2026-09-22.mjs. Deterministic; the catalog test fails if
// the committed schema.sql differs from a fresh generation (principle 3).
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { TABLES, SYNTHETIC, SNAPSHOT } from './columns-2026-09-22.mjs';
const TY = { int8: 'bigint', int4: 'integer', int2: 'smallint', text: 'text', timestamptz: 'timestamptz', date: 'date',
  numeric: 'numeric', bool: 'boolean', jsonb: 'jsonb', bpchar: 'char(2)', _text: 'text[]', uuid: 'uuid' };
export function schemaSql() {
  const out = [`-- GENERATED by tms-auditor/test/fixtures/build-schema.mjs from ${SNAPSHOT}. Do not edit.`,
    '-- Local fixture only: production types/columns, NO constraints/triggers/data. ids are identities for convenience.'];
  const emit = (name, cols, note) => {
    const lines = cols.map(([c, t]) => {
      const nn = t.endsWith('!'); const base = t.replace('!', ''); let d = `  ${c} ${TY[base] || (() => { throw new Error('type ' + t); })()}`;
      if (c === 'id' && nn) d += ' GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY';
      else if (nn) d += ' NOT NULL' + (base === 'timestamptz' ? ' DEFAULT now()' : base === 'bool' ? ' DEFAULT false' : base === 'int4' ? ' DEFAULT 0' : '');
      return d;
    });
    out.push(`${note ? '-- ' + note + '\n' : ''}CREATE TABLE public.${name} (\n${lines.join(',\n')}\n);`);
  };
  for (const [t, cols] of Object.entries(TABLES)) emit(t, cols);
  for (const [t, cols] of Object.entries(SYNTHETIC)) emit(t, cols, 'SYNTHETIC (not from the production catalog)');
  return out.join('\n') + '\n';
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  fs.writeFileSync(path.join(path.dirname(fileURLToPath(import.meta.url)), 'schema.sql'), schemaSql());
  console.log('schema.sql:', Object.keys(TABLES).length, 'tables +', Object.keys(SYNTHETIC).length, 'synthetic');
}
