#!/usr/bin/env bash
# ============================================================================
# make-staging-config.sh, build config.staging.js from the real config.js
# ----------------------------------------------------------------------------
# Purpose: point the REAL app at the NEW backend (Worker 2, Supabase Postgres)
# so the UI can be exercised in a browser against the new stack, which is the
# one thing the staging validation could not previously claim.
#
# WHY GENERATED, NOT HAND-MAINTAINED: config.js holds the table-id map, the
# model ids, and the role/permission matrix. A hand-copied staging twin would
# drift from it silently and we would be testing a fiction. This derives the
# staging config from the real file every run, changing only two constants:
#
#   USE_PROXY  -> true                         (send JWT, use the proxy path)
#   PROXY_URL  -> the Stage 2 backend Worker   (NOT the old tms-api-proxy)
#
# THE TWO WORKERS ARE DIFFERENT THINGS (learning #86):
#   tms-api-proxy...              = Worker 1, pass-through to AIRTABLE
#   petras-tms-backend-staging... = Worker 2, the new POSTGRES backend  <-- here
#
# The generated file is gitignored: it is a build artifact, and pinning a URL
# into the repo invites someone to ship it. Nothing here holds a secret; auth is
# a JWT minted at runtime by logging in.
#
# Usage: tests/e2e/make-staging-config.sh [worker-url]
# ============================================================================
set -euo pipefail

cd "$(dirname "$0")/../.."

BACKEND="${1:-https://petras-tms-backend-staging.petrasgroup.workers.dev}"
SRC="config.js"
OUT="config.staging.js"

[ -f "$SRC" ] || { echo "$SRC not found (run from the repo)" >&2; exit 1; }

{
  echo "// GENERATED by tests/e2e/make-staging-config.sh — DO NOT EDIT, DO NOT COMMIT."
  echo "// Real config.js with USE_PROXY=true and PROXY_URL pointed at the Stage 2"
  echo "// backend, so the UI runs against Postgres instead of Airtable."
  echo "// Regenerate after any config.js change."
  echo ""
  sed \
    -e "s|^const USE_PROXY  *= *false;|const USE_PROXY  = true;|" \
    -e "s|^const PROXY_URL  *= *'[^']*';|const PROXY_URL  = '${BACKEND}';|" \
    "$SRC"
} > "$OUT"

# Fail loudly rather than producing a config that silently still points at
# Airtable: a green test run against the OLD stack would be worse than no run.
grep -q "const USE_PROXY  = true;" "$OUT" \
  || { echo "FAILED: USE_PROXY was not flipped (config.js format changed?)" >&2; exit 1; }
grep -q "const PROXY_URL  = '${BACKEND}';" "$OUT" \
  || { echo "FAILED: PROXY_URL was not repointed (config.js format changed?)" >&2; exit 1; }

echo "Wrote $OUT"
echo "  USE_PROXY = true"
echo "  PROXY_URL = $BACKEND"

# ── app.staging.html: the real app, loading the staging config ──────────────
# Same generate-don't-copy reasoning: app.html's script list (and its ?v= cache
# busters) changes constantly, so a hand-maintained twin would load stale
# modules and we would be testing code nobody runs.
APP_SRC="app.html"
APP_OUT="app.staging.html"
[ -f "$APP_SRC" ] || { echo "$APP_SRC not found" >&2; exit 1; }

# Swap only the config script tag; every other module keeps its own ?v=.
sed -e 's|<script src="config\.js[^"]*"></script>|<script src="config.staging.js"></script>|' \
    "$APP_SRC" > "$APP_OUT"

grep -q '<script src="config.staging.js"></script>' "$APP_OUT" \
  || { echo "FAILED: config script tag not swapped in $APP_OUT" >&2; exit 1; }
grep -q '<script src="config.js' "$APP_OUT" \
  && { echo "FAILED: $APP_OUT still loads the real config.js" >&2; exit 1; }

echo "Wrote $APP_OUT (loads config.staging.js)"
