-- 053 — DRAFT (ΔΕΝ ΕΚΤΕΛΕΣΤΗΚΕ) — order_documents: ο πίνακας πίσω από τα scanned
--        έγγραφα παραγγελίας (CMR/τιμολόγια/φωτογραφίες), scan round 3. Τρέχει ο
--        owner, μετά τις 15:00 (αρχή 7). Branch feat/scan-round3.
--
-- ΣΕΙΡΑ (υποχρεωτική): 053 → deploy Worker (R2 binding ORDER_DOCS + TABLES map
--   tblOrderDocuments + /docs/* routes). Αν γίνει deploy ΠΡΙΝ το 053: κάθε
--   /docs/upload και /docs/list αποτυγχάνει δυνατά (500, στήλη/πίνακας δεν
--   υπάρχει) — δεν υπάρχει σιωπηλή αποτυχία, γιατί ο πίνακας δεν υπάρχει καθόλου
--   και η PostgREST αρνείται. Αντίστροφα (053 χωρίς deploy) είναι ακίνδυνο: ο
--   πίνακας κάθεται άδειος, καμία οθόνη δεν τον διαβάζει ακόμη.
--
-- ΤΙ ΕΙΝΑΙ
-- Ένα σκαναρισμένο ή ανεβασμένο αρχείο ανά (order_id, sha256): το ίδιο αρχείο
-- να ανέβει δύο φορές στην ίδια παραγγελία δεν δημιουργεί δεύτερο αντικείμενο
-- στο R2 ούτε δεύτερη γραμμή (ο Worker το κάνει idempotent στο /docs/upload).
-- Το πραγματικό byte-περιεχόμενο ζει στο R2 bucket tms-order-docs (EU
-- jurisdiction, χωρίς public access)· αυτός ο πίνακας κρατά μόνο τα metadata
-- και το κλειδί r2_key. ΠΟΤΕ δεν σβήνεται (ON DELETE RESTRICT + καμία διαδρομή
-- DELETE στον Worker) — ένα σκαναρισμένο έγγραφο παραγγελίας είναι απόδειξη,
-- όχι πρόχειρο σημείωμα (ίδια λογική με τα GROUPAGE LINES, never-delete).
--
-- ΓΙΑΤΙ order_id bigint ΚΑΙ ΟΧΙ uuid
-- orders.id είναι bigint (μετρημένο στα υπάρχοντα FKs: worker/migrations/
-- 018_order_legs.sql, db/migrations/2026-08-10_local_moves.sql κ.ά. γράφουν
-- όλα `references orders(id)` πάνω σε bigint). Δύο τύποι πρωτεύοντος κλειδιού
-- για τον ίδιο γονέα θα ήταν δεύτερη πηγή αλήθειας (αρχή 3) — id εδώ ακολουθεί
-- την ΙΔΙΑ σύμβαση (bigint identity), όχι uuid.
--
-- ΓΙΑΤΙ legacy_id ΚΑΙ ΟΧΙ ΜΟΝΟ id
-- Ο Worker μιμείται το Airtable: ΚΑΘΕ πίνακας που περνά από τον γενικό facade
-- (GET/GET-one) διαβάζεται/γράφεται με `legacy_id=eq.recXXXXXXXXXXXXXX`
-- (toAirtableRecord: `{ id: row.legacy_id, fields }`, deployed γρ. ~2192).
-- ΤΟ ΙΔΙΟ σχήμα με local_moves (db/migrations/2026-09-03_fixes.sql §Β): text,
-- nullable, ΧΩΡΙΣ default, UNIQUE. Χωρίς default επειδή η γεννήτρια
-- (mintLegacyId, 'rec' + 14 τυχαίοι χαρακτήρες) ζει ΜΟΝΟ στον Worker — δύο
-- γεννήτριες για τον ίδιο πίνακα θα ήταν δεύτερη πηγή αλήθειας. Ο πίνακας
-- είναι read-only μέσω του γενικού facade (μόνο GET) — η εγγραφή γίνεται από
-- το αποκλειστικό /docs/upload, που θα μπει το ίδιο το legacy_id στο INSERT.
--
-- ΓΙΑΤΙ ON DELETE RESTRICT στο order_id
-- Ίδιος κανόνας με groupage_lines/pl_movements (αρχή 4, «ο κανόνας μπαίνει όσο
-- πιο χαμηλά αντέχει»): μια παραγγελία με σκαναρισμένα έγγραφα δεν μπορεί ποτέ
-- να σβηστεί hard-delete χωρίς πρώτα να αποφασιστεί τι γίνεται με τα έγγραφά
-- της. Ο facade δεν κάνει ποτέ hard delete στα ORDERS ούτως ή άλλως
-- (handleOrderCascadeDelete γράφει deleted_at) — αυτό το CHECK πιάνει και κάθε
-- μελλοντική διαδρομή SQL που θα το παρέκαμπτε.
--
-- ΓΙΑΤΙ deleted_at παρόλο που ΔΕΝ υπάρχει DELETE endpoint
-- Το γενικό facade GET (handleFacadeGet/handleFacadeGetOne) προσθέτει ΠΑΝΤΑ
-- `deleted_at=is.null` στο φίλτρο, ανεξάρτητα από το ποιος πίνακας — χωρίς τη
-- στήλη η PostgREST θα απαντούσε 400 σε κάθε GET μέσω του facade (tblOrderDocuments).
-- Η στήλη μένει πάντα NULL σήμερα (καμία διαδρομή δεν τη γράφει) — δεν είναι
-- νεκρός κώδικας, είναι προϋπόθεση του μηχανισμού ανάγνωσης.
--
-- ΔΙΚΑΙΩΜΑΤΑ — ΓΕΝΝΙΕΤΑΙ ΚΛΕΙΣΤΟΣ (αρχή 5)
-- Η Supabase δίνει αυτόματα πρόσβαση στον anon σε κάθε νέο πίνακα· αυτό το
-- REVOKE το ακυρώνει ρητά, όπως κάθε νέος πίνακας θα έπρεπε να κάνει από την
-- αρχή. RLS ενεργό (χωρίς πολιτικές, όπως όλο το v2 — SECURITY.md): ο Worker
-- μιλάει με service_role, που παρακάμπτει RLS ούτως ή άλλως, άρα το REVOKE από
-- anon/authenticated είναι η πραγματική πόρτα εδώ, όχι το RLS.
--
-- ΑΝΑΣΤΡΕΨΙΜΟ (ο πίνακας θα είναι άδειος στην πρώτη εκτέλεση):
--   DROP TABLE public.order_documents;

BEGIN;

-- ΠΡΙΝ: ο πίνακας δεν υπάρχει ήδη (πρέπει 0).
SELECT count(*) AS already_there FROM information_schema.tables
 WHERE table_schema = 'public' AND table_name = 'order_documents';

CREATE TABLE public.order_documents (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Facade record id (βλ. σχόλιο πάνω). Ο Worker το γεμίζει στο /docs/upload
  -- με mintLegacyId() — καμία default τιμή εδώ.
  legacy_id   text UNIQUE,

  order_id    bigint NOT NULL REFERENCES public.orders(id) ON DELETE RESTRICT,

  sha256      char(64) NOT NULL CHECK (sha256 ~ '^[0-9a-f]{64}$'),
  filename    text NOT NULL CHECK (length(filename) BETWEEN 1 AND 255),
  mime        text NOT NULL,
  size        bigint NOT NULL CHECK (size > 0 AND size <= 15728640),  -- 15 MiB, ίδιο όριο με τον Worker

  -- Το πραγματικό αντικείμενο: orders/<order_id>/<sha256> στο bucket
  -- tms-order-docs. UNIQUE γιατί δύο γραμμές να δείχνουν στο ίδιο αντικείμενο
  -- θα ήταν δύο πηγές αλήθειας για ένα αρχείο.
  r2_key      text NOT NULL UNIQUE,

  source      text NOT NULL CHECK (source IN ('scan', 'upload')),
  uploaded_by text,                          -- caller.sub (username), όχι ρόλος· ίχνος, όχι δικαίωμα
  created_at  timestamptz NOT NULL DEFAULT now(),
  deleted_at  timestamptz,                   -- βλ. σχόλιο πάνω· καμία διαδρομή δεν τη γράφει σήμερα

  -- Το ίδιο αρχείο (ίδιο sha256) στην ίδια παραγγελία δεν μπαίνει δεύτερη
  -- φορά — αυτό κάνει idempotent το /docs/upload χωρίς δεύτερο round-trip.
  CONSTRAINT order_documents_order_sha_key UNIQUE (order_id, sha256)
);

CREATE INDEX order_documents_order_idx ON public.order_documents (order_id) WHERE deleted_at IS NULL;

ALTER TABLE public.order_documents ENABLE ROW LEVEL SECURITY;

-- Γεννιέται κλειστός (αρχή 5): η Supabase δίνει αυτόματα πρόσβαση στον anon.
REVOKE ALL ON public.order_documents FROM anon;
REVOKE ALL ON public.order_documents FROM authenticated;
REVOKE ALL ON public.order_documents FROM PUBLIC;
-- id (bigint identity) χρειάζεται τη sequence ρητά (ίδιο μοτίβο με κάθε άλλο
-- GENERATED BY DEFAULT AS IDENTITY πίνακα εδώ) — χωρίς αυτό το service_role θα
-- έβλεπε "permission denied for sequence" στο πρώτο INSERT.
REVOKE ALL ON SEQUENCE public.order_documents_id_seq FROM anon, authenticated, PUBLIC;

COMMENT ON TABLE public.order_documents IS
  'Scanned/uploaded documents attached to an order (scan round 3, 28/9/2026). Real bytes live in R2 bucket tms-order-docs; this table is metadata + the r2_key. Read-only via the generic facade (tblOrderDocuments, GET only) — writes go through the dedicated /docs/upload endpoint, which streams into R2 and mints legacy_id itself. Never deleted: ON DELETE RESTRICT on order_id, no DELETE route anywhere.';

-- ΜΕΤΑ: η στήλη/πίνακας/δείκτες υπάρχουν (πρέπει 1 σε καθένα).
SELECT (SELECT count(*) FROM information_schema.tables
         WHERE table_schema = 'public' AND table_name = 'order_documents') AS table_exists,
       (SELECT count(*) FROM pg_indexes
         WHERE schemaname = 'public' AND tablename = 'order_documents'
           AND indexname = 'order_documents_order_idx') AS order_index_exists,
       (SELECT count(*) FROM pg_constraint
         WHERE conrelid = 'public.order_documents'::regclass
           AND conname = 'order_documents_order_sha_key') AS unique_order_sha_exists;

-- ΜΕΤΑ: γεννήθηκε κλειστός — 0 γραμμές privilege για anon/authenticated.
SELECT grantee, privilege_type FROM information_schema.role_table_grants
 WHERE table_schema = 'public' AND table_name = 'order_documents'
   AND grantee IN ('anon', 'authenticated', 'PUBLIC');
-- αναμενόμενο: 0 γραμμές

COMMIT;

-- Επανάληψη ελέγχου session (CLAUDE.md «ο επαναλαμβανόμενος έλεγχος»), μετά την πρώτη χρήση:
--   SELECT count(*) AS σύνολο,
--          count(*) FILTER (WHERE deleted_at IS NULL) AS ζωντανά,
--          count(DISTINCT order_id) AS παραγγελίες_με_έγγραφο
--     FROM order_documents;
--   -- (Β) Ο auditor check B-55/B-56 (tms-auditor/checks/) καλύπτει ορφανά order_id
--   --     και παραγγελίες scan χωρίς κανένα έγγραφο — και τα δύο DISABLED μέχρι
--   --     αυτό το migration να τρέξει (βλ. σχόλιο enabled: no: ... στα .sql τους).
