-- 060 DRY RUN - GENERATED by worker/migrations/drafts/tools/build-060-dryrun.mjs from 060_local_relay.sql.
-- DO NOT EDIT BY HAND: edit 060 and regenerate (tms-auditor/test/dryrun-060.test.mjs fails on any drift).
--
-- WHAT: 060's own DO block, statement for statement (every guard, change and proof, the B-54 bump, the
--   auditor rows run as tms_check_runner), wrapped in ONE outer DO block that first fingerprints data 060
--   must not touch, then checks the result, and ENDS WITH A DELIBERATE ERROR. The error rolls the whole
--   block back: NOTHING it did is kept (no column, constraint, index, function, trigger, view change,
--   auditor row, B-54 edit).
-- WHEN: the same evening, AFTER 15:00 (the team works 05:30-14:30), BEFORE 060_local_relay.sql - and
--   after 057 when both go out together (060 then measures the triggers 057 added). It takes the same
--   locks as 060 (lock_timeout 5 s, then it gives up - run it again a little later).
-- WHY ONE DO BLOCK: the Supabase SQL editor is NOT atomic across statements (lesson 056), but ONE DO
--   block is ONE statement: its final error undoes everything inside it.
-- EXPECTED (the red ERROR is deliberate):
--   ERROR: P0001: DRY RUN 060 finished - EVERYTHING UNDONE, nothing kept. Result: 3 OK, 0 FAIL  ||  A ok ... | B ok B-54 T -> T+4 ... | C ok ...
--   (T = the live trigger count: 31 after 057, 27 without it.)
--   Anything with FAIL or ERROR in it: do NOT run 060, copy the panel to the coordinator.
--   ONE exception: "2 OK, 1 FAIL" where the FAIL is C alone (A ok, B ok). C fingerprints live tables
--   and every public sequence while the block runs, so ONE save by someone else in those seconds
--   (a payroll line, an order, any nextval) turns it red - it fails closed, nothing was kept. Wait 5
--   minutes and run the dry run once more; if C fails again, copy the panel to the coordinator.
--   A different message altogether ("060: ...", "060 proof: ...", a lock timeout) is the guard or proof
--   of 060 that stopped - exactly what 060 itself would have said. Do NOT run 060.
-- AFTER: SELECT that nothing was kept - local_moves has no move_kind column, B-63..B-65 do not exist,
--   B-54 red_value is still T (060_local_relay_verify.sql is for AFTER 060, not here).
-- Scenarios: A 060's objects exist inside the block; B B-54 moved by exactly +4 and equals the live
--   count; C data 060 must not touch is unchanged (orders, payroll lines, round trips, local_moves,
--   drivers, every auditor row but B-09/B-54/B-63..B-65, the last_value of every public sequence).

DO $dry$
DECLARE
  ok int := 0; bad int := 0; res text[] := '{}';
  dry_fp_before text; dry_b54_before int; dry_trg_before int; dry_n int;
BEGIN
  -- the B-54 value and the trigger count 060 will meet, and the data it must leave alone
  SELECT red_value INTO dry_b54_before FROM monitoring.checks WHERE id = 'B-54';
  SELECT count(*) INTO dry_trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  SELECT (SELECT md5(
    coalesce((SELECT string_agg(concat_ws(':', id, status, driver_id, truck_id, trailer_id, partner_id, loading_datetime, delivery_datetime, deleted_at), ',' ORDER BY id) FROM public.orders), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, driver_id, entry_type, entry_date, rt_id, trip_value, advance, expenses, amount, deleted_at, needs_review, review_note), ',' ORDER BY id) FROM public.dl_entries), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, status, driver_id, truck_id, trailer_id, date_start, date_end), ',' ORDER BY id) FROM public.ct_round_trips), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, status, driver_id, parent_order_id, parent_nat_load_id, move_date, deleted_at), ',' ORDER BY id) FROM public.local_moves), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, full_name, active, deleted_at), ',' ORDER BY id) FROM public.drivers), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks
              WHERE id NOT IN ('B-09', 'B-54', 'B-63', 'B-64', 'B-65')), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) INTO dry_fp_before;

  -- ===== 060_local_relay.sql, its DO block verbatim (a nested block: its errors stop everything) =====
DECLARE
  n int; k int;
  trg_before int; trg_after int;
  dl_live_before bigint; orders_before bigint; rts_before bigint;
  old_unlink text; new_unlink text; tail text; step6 text;
  old_view text; new_view text; view_acl_before text; view_cols_before int; sel_prefix text; old_joins text;
  r record; v numeric; ids text[];
BEGIN
  -- pg_get_viewdef (md5 guard below) prints names relative to the search_path: pin it.
  PERFORM set_config('search_path', 'public, extensions', true);
  -- ALTER TABLE on dl_entries / local_moves, CREATE TRIGGER on orders and the
  -- dl_v_entries replace need strong locks: behind an idle open transaction they would wait
  -- forever while every app read of those tables queues behind them. Give up after 5 s instead -
  -- the whole block rolls back, nothing half-done; run it again later (same as 057).
  PERFORM set_config('lock_timeout', '5s', true);

  -- 0. GUARDS (SELECT only): the base is what was measured on 4/10.
  IF to_regclass('monitoring.checks') IS NULL THEN
    RAISE EXCEPTION '060: monitoring.checks does not exist (047 must run first)';
  END IF;
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public'
              AND ((table_name = 'local_moves' AND column_name = 'move_kind')
                OR (table_name = 'dl_entries' AND column_name = 'local_move_id'))) THEN
    RAISE EXCEPTION '060: already applied (a 060 column exists)';
  END IF;
  IF to_regprocedure('public.local_moves_before()') IS NOT NULL
     OR to_regprocedure('public.local_moves_follow_order()') IS NOT NULL
     OR to_regprocedure('public.dl_local_day_sync(bigint,date)') IS NOT NULL
     OR to_regprocedure('public.dl_sync_from_local_move()') IS NOT NULL
     OR to_regprocedure('public.dl_local_line_guard()') IS NOT NULL
     OR to_regclass('public.local_moves_relay_once') IS NOT NULL
     OR to_regclass('public.dl_local_day_live') IS NOT NULL THEN
    RAISE EXCEPTION '060: a name 060 creates is taken - stop';
  END IF;
  -- Plain rows written by Weekly National before this runs are welcome (they become 'local').
  -- A row naming an ORDER would violate local_moves_kind_parent: decide before running.
  SELECT count(*) INTO n FROM public.local_moves WHERE parent_order_id IS NOT NULL;
  IF n > 0 THEN
    RAISE EXCEPTION '060: % local_moves rows carry parent_order_id (old Weekly International local UI) - ask the coordinator', n;
  END IF;
  -- orders dates are DATE (national_loads are timestamptz): the relay day is compared as is.
  SELECT count(*) INTO n FROM information_schema.columns WHERE table_schema = 'public' AND table_name = 'orders'
     AND column_name IN ('loading_datetime', 'delivery_datetime') AND data_type = 'date';
  IF n <> 2 THEN RAISE EXCEPTION '060: orders loading/delivery_datetime are not both DATE'; END IF;
  -- Two objects are extended from their live text: refuse if either changed since 4/10.
  old_unlink := pg_get_functiondef('public.order_soft_delete_unlink()'::regprocedure);
  IF md5(old_unlink) <> '7b873ab86adbfb2db10590e0c47f87bc' THEN
    RAISE EXCEPTION '060: order_soft_delete_unlink changed since 4/10 (md5 %) - re-measure', md5(old_unlink);
  END IF;
  old_view := pg_get_viewdef('public.dl_v_entries'::regclass);
  IF md5(old_view) <> 'c81a268c7312574d10da6c78ef316326' THEN
    RAISE EXCEPTION '060: dl_v_entries changed since 4/10 (md5 %) - re-measure', md5(old_view);
  END IF;
  SELECT relacl::text INTO view_acl_before FROM pg_class WHERE oid = 'public.dl_v_entries'::regclass;
  SELECT count(*) INTO view_cols_before FROM pg_attribute
   WHERE attrelid = 'public.dl_v_entries'::regclass AND attnum > 0 AND NOT attisdropped;
  IF NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-09'
                  AND md5(sql_text) = 'b8f8d0e705f8466a3f6305c9e38c544f'
                  AND md5(coalesce(ids_sql, '')) = 'b96ff398c369f06b6eb9c99d343e155c') THEN
    RAISE EXCEPTION '060: B-09 is not the text measured on 4/10 - production was edited, stop';
  END IF;
  IF EXISTS (SELECT 1 FROM monitoring.checks WHERE id IN ('B-63', 'B-64', 'B-65')) THEN
    RAISE EXCEPTION '060: check ids B-63..B-65 are taken - ask the coordinator';
  END IF;
  SELECT count(*) INTO trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  -- run_checks compares against coalesce(baseline, red_value): a baseline would make the bump below
  -- a no-op and B-54 a standing P1 red.
  IF NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-54' AND red_value = trg_before AND baseline IS NULL) THEN
    RAISE EXCEPTION '060: B-54 red_value is not the live trigger count % (or has a baseline) - a migration changed triggers without bumping it, re-measure', trg_before;
  END IF;
  SELECT count(*) INTO dl_live_before FROM public.dl_entries WHERE deleted_at IS NULL;
  SELECT count(*) INTO orders_before FROM public.orders WHERE deleted_at IS NULL;
  SELECT count(*) INTO rts_before FROM public.ct_round_trips;

  -- 1. WHAT A LOCAL MOVE IS. Plain rows (Weekly National) default to 'local' and keep every
  --    freedom they have today; only relays are constrained.
  ALTER TABLE public.local_moves ADD COLUMN move_kind text NOT NULL DEFAULT 'local';
  ALTER TABLE public.local_moves
    ADD CONSTRAINT local_moves_kind_chk CHECK (move_kind IN ('local', 'relay_delivery', 'relay_loading')),
    -- ONE way to say "a local driver worked on this international order": a relay. A plain move
    -- never names an order (Weekly National's "assign to local driver" names a national load and
    -- stays allowed). Phase 1: relays serve international orders only.
    ADD CONSTRAINT local_moves_kind_parent CHECK (
         (move_kind = 'local' AND parent_order_id IS NULL)
      OR (move_kind <> 'local' AND parent_order_id IS NOT NULL AND parent_nat_load_id IS NULL)),
    -- A relay stores ONLY the handover point; the customer's stops are read live from the order.
    ADD CONSTRAINT local_moves_relay_points CHECK (
          (move_kind <> 'relay_delivery' OR (from_location_id IS NOT NULL AND to_location_id IS NULL))
      AND (move_kind <> 'relay_loading' OR (to_location_id IS NOT NULL AND from_location_id IS NULL))),
    -- "Done" is the order's status (Delivered / In Transit), never copied into the relay; the
    -- relay's own status is derived from the driver (local_moves_before) and only that.
    ADD CONSTRAINT local_moves_relay_status CHECK (
         move_kind = 'local' OR status = 'Cancelled'
      OR (status = 'Assigned' AND driver_id IS NOT NULL) OR (status = 'Pending' AND driver_id IS NULL)),
    -- A partner relay would leave no cost trace anywhere (phase 1: own drivers only).
    ADD CONSTRAINT local_moves_relay_executor CHECK (move_kind = 'local' OR partner_id IS NULL),
    -- The RT keeps ONE trailer (rt_sync); the relay records what the local driver pulls (Q1).
    ADD CONSTRAINT local_moves_relay_trailer CHECK (move_kind = 'local' OR driver_id IS NULL OR trailer_id IS NOT NULL);
  CREATE UNIQUE INDEX local_moves_relay_once ON public.local_moves (parent_order_id, move_kind)
    WHERE deleted_at IS NULL AND status <> 'Cancelled' AND move_kind <> 'local';

  -- 2. RELAY RULES AT WRITE TIME. The CHECKs above are the floor (principle 4); this trigger
  --    refuses first with a machine code the Worker turns into a Greek 422 (principle 1), and
  --    derives what nobody types: status from the driver, day from the order.
  CREATE FUNCTION public.local_moves_before() RETURNS trigger
    LANGUAGE plpgsql SET search_path = public AS $f$
  DECLARE o record; d date;
  BEGIN
    IF TG_OP = 'UPDATE' THEN
      NEW.updated_at := now();
      -- Kind and order are what the payroll line and the auditor key on: never re-pointed.
      IF (OLD.move_kind <> 'local' OR NEW.move_kind <> 'local')
         AND (NEW.move_kind, NEW.parent_order_id, NEW.parent_nat_load_id)
             IS DISTINCT FROM (OLD.move_kind, OLD.parent_order_id, OLD.parent_nat_load_id) THEN
        RAISE EXCEPTION 'local_relay: the kind and the order of a relay never change - delete it and add a new one'
          USING ERRCODE = '23514', HINT = 'local_relay:kind_locked';
      END IF;
    END IF;
    -- Plain local moves (Weekly National, move_kind 'local'): today's behaviour exactly - no
    -- derived status, no refusal here (coordinator 4/10). An unknown kind falls through to
    -- local_moves_kind_chk.
    IF NEW.move_kind IS DISTINCT FROM 'relay_delivery' AND NEW.move_kind IS DISTINCT FROM 'relay_loading' THEN
      RETURN NEW;
    END IF;
    -- Un-deleting or un-cancelling would bring back a relay whose order may have moved on
    -- (rule of 023): the dispatcher adds a new one.
    IF TG_OP = 'UPDATE' AND ((OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL)
                             OR (OLD.status = 'Cancelled' AND NEW.status IS DISTINCT FROM 'Cancelled')) THEN
      RAISE EXCEPTION 'local_relay: a deleted or cancelled relay is not revived - add a new one'
        USING ERRCODE = '23514', HINT = 'local_relay:final';
    END IF;
    IF NEW.status IS NULL OR NEW.status IN ('Pending', 'Assigned') THEN
      NEW.status := CASE WHEN NEW.driver_id IS NOT NULL THEN 'Assigned' ELSE 'Pending' END;
    ELSIF NEW.status <> 'Cancelled' THEN
      RAISE EXCEPTION 'local_relay: a relay is Pending, Assigned or Cancelled - done is read from the order'
        USING ERRCODE = '23514', HINT = 'local_relay:status';
    END IF;
    IF NEW.deleted_at IS NOT NULL OR NEW.status = 'Cancelled' THEN
      RETURN NEW;                                   -- gone: nothing more to check, nothing paid
    END IF;
    IF NEW.parent_order_id IS NULL OR NEW.parent_nat_load_id IS NOT NULL THEN
      RAISE EXCEPTION 'local_relay: a relay serves exactly one international order'
        USING ERRCODE = '23514', HINT = 'local_relay:no_order';
    END IF;
    IF NEW.partner_id IS NOT NULL THEN
      RAISE EXCEPTION 'local_relay: a partner cannot be the local driver of a relay (phase 1)'
        USING ERRCODE = '23514', HINT = 'local_relay:partner';
    END IF;
    IF (NEW.move_kind = 'relay_delivery' AND (NEW.from_location_id IS NULL OR NEW.to_location_id IS NOT NULL))
       OR (NEW.move_kind = 'relay_loading' AND (NEW.to_location_id IS NULL OR NEW.from_location_id IS NOT NULL)) THEN
      RAISE EXCEPTION 'local_relay: a local delivery stores only From (the handover point), a local loading only To'
        USING ERRCODE = '23514', HINT = 'local_relay:points';
    END IF;
    IF NEW.driver_id IS NOT NULL AND NEW.trailer_id IS NULL THEN
      RAISE EXCEPTION 'local_relay: with a local driver the trailer is required'
        USING ERRCODE = '23514', HINT = 'local_relay:no_trailer';
    END IF;

    SELECT id, direction, veroia_switch, status, ops_status, deleted_at, driver_id, loading_datetime, delivery_datetime
      INTO o FROM orders WHERE id = NEW.parent_order_id;
    IF NOT FOUND THEN
      RAISE EXCEPTION 'local_relay: order % does not exist', NEW.parent_order_id
        USING ERRCODE = '23514', HINT = 'local_relay:no_order';
    END IF;
    -- Shape of the ORDER is checked when the relay is written; an order that changes later is
    -- never blocked - B-65 reports the mismatch the next day.
    IF TG_OP = 'INSERT' THEN
      IF o.deleted_at IS NOT NULL OR o.status = 'Cancelled' THEN
        RAISE EXCEPTION 'local_relay: order % is deleted or cancelled', o.id
          USING ERRCODE = '23514', HINT = 'local_relay:order_gone';
      END IF;
      IF o.ops_status = 'Provisional' THEN
        RAISE EXCEPTION 'local_relay: order % is a pre-order - convert it first', o.id
          USING ERRCODE = '23514', HINT = 'local_relay:preorder';
      END IF;
      IF coalesce(o.veroia_switch, false) THEN
        RAISE EXCEPTION 'local_relay: order % goes through Veroia Switch (cross-dock)', o.id
          USING ERRCODE = '23514', HINT = 'local_relay:vs';
      END IF;
      IF o.direction IS DISTINCT FROM (CASE NEW.move_kind WHEN 'relay_delivery' THEN 'Import' ELSE 'Export' END) THEN
        RAISE EXCEPTION 'local_relay: a local delivery only on an import, a local loading only on an export (order %)', o.id
          USING ERRCODE = '23514', HINT = 'local_relay:direction';
      END IF;
      IF EXISTS (SELECT 1 FROM orders l WHERE l.parent_order_id = o.id AND l.deleted_at IS NULL) THEN
        RAISE EXCEPTION 'local_relay: order % is split - put the relay on the leg', o.id
          USING ERRCODE = '23514', HINT = 'local_relay:split_parent';
      END IF;
      -- local_moves_relay_once is the floor; this only gives the refusal its code.
      IF EXISTS (SELECT 1 FROM local_moves x WHERE x.parent_order_id = o.id AND x.move_kind = NEW.move_kind
                    AND x.deleted_at IS NULL AND x.status <> 'Cancelled') THEN
        RAISE EXCEPTION 'local_relay: order % already has a live relay of this kind', o.id
          USING ERRCODE = '23514', HINT = 'local_relay:relay_exists';
      END IF;
    END IF;
    -- The relay exists because ANOTHER driver does this part; checked whenever the driver is set.
    IF NEW.driver_id IS NOT NULL AND NEW.driver_id = o.driver_id
       AND (TG_OP = 'INSERT' OR NEW.driver_id IS DISTINCT FROM OLD.driver_id) THEN
      RAISE EXCEPTION 'local_relay: the local driver is the international driver of order %', o.id
        USING ERRCODE = '23514', HINT = 'local_relay:same_driver';
    END IF;
    -- The relay day IS the order's customer day (orders dates are DATE: no time zone). Derived,
    -- never typed: a typed Date is replaced, so the Daily, the payroll day and the order agree.
    d := CASE NEW.move_kind WHEN 'relay_delivery' THEN o.delivery_datetime ELSE o.loading_datetime END;
    IF d IS NOT NULL THEN
      NEW.move_date := d;
    ELSIF TG_OP = 'INSERT' THEN
      RAISE EXCEPTION 'local_relay: order % has no % date', o.id,
        CASE NEW.move_kind WHEN 'relay_delivery' THEN 'delivery' ELSE 'loading' END
        USING ERRCODE = '23514', HINT = 'local_relay:no_order_date';
    END IF;  -- an UPDATE after the order lost its date keeps the last day (never block); B-65 'day'
    RETURN NEW;
  END $f$;
  CREATE TRIGGER local_moves_before BEFORE INSERT OR UPDATE ON public.local_moves
    FOR EACH ROW EXECUTE FUNCTION public.local_moves_before();

  -- 3. DELETING AN ORDER already has ONE home: order_soft_delete_unlink (023). Its new text is
  --    the live text (md5-guarded above) with step 6 inserted before the final return - steps
  --    1-5 are not retyped, so they cannot drift.
  tail := E'  return null;\nend $function$\n';
  IF (length(old_unlink) - length(replace(old_unlink, tail, ''))) <> length(tail) THEN
    RAISE EXCEPTION '060: the end of order_soft_delete_unlink is not where it was measured';
  END IF;
  step6 := $s6$  -- 6. local relays (060): a deleted order takes its local delivery/loading with it.
  --    dl_sync_from_local_move then cancels the local driver's day line, or flags it for review
  --    when amounts were written. Split legs reach here too (step 3 re-fires this trigger).
  for r in update local_moves lm set deleted_at = new.deleted_at
           where lm.parent_order_id = new.id and lm.deleted_at is null returning lm.id loop
    insert into audit_log (actor, role, action, table_name, record_id, before_data, after_data, created_at)
    values ('trigger:order_unlink', 'system', 'delete', 'local_moves', r.id::text,
            jsonb_build_object('parent_order_id', new.id), jsonb_build_object('reason', procedure_note), now());
  end loop;
$s6$;
  new_unlink := replace(old_unlink, tail, step6 || tail);
  EXECUTE new_unlink;

  -- 4. THE ORDER MOVES, THE RELAY FOLLOWS. Cancel and day moves only, per kind; an audit row only
  --    when something really changed. Never refuses: an order edit is never blocked by a relay.
  CREATE FUNCTION public.local_moves_follow_order() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $f$
  DECLARE r record;
  BEGIN
    IF NEW.deleted_at IS NOT NULL THEN RETURN NULL; END IF;     -- deletion belongs to 023 step 6
    IF NEW.status = 'Cancelled' AND OLD.status IS DISTINCT FROM 'Cancelled' THEN
      FOR r IN UPDATE local_moves lm SET status = 'Cancelled'
               WHERE lm.parent_order_id = NEW.id AND lm.move_kind <> 'local'
                 AND lm.deleted_at IS NULL AND lm.status <> 'Cancelled'
               RETURNING lm.id LOOP
        INSERT INTO audit_log (actor, role, action, table_name, record_id, before_data, after_data, created_at)
        VALUES ('trigger:local_moves_follow', 'system', 'update', 'local_moves', r.id::text,
                jsonb_build_object('parent_order_id', NEW.id),
                jsonb_build_object('status', 'Cancelled', 'reason', 'order ' || NEW.id || ' cancelled'), now());
      END LOOP;
      RETURN NULL;
    END IF;
    -- Un-cancelling the order never revives a relay (local_moves_before refuses it).
    FOR r IN UPDATE local_moves lm
             SET move_date = CASE lm.move_kind WHEN 'relay_delivery' THEN NEW.delivery_datetime ELSE NEW.loading_datetime END
             WHERE lm.parent_order_id = NEW.id AND lm.move_kind <> 'local'
               AND lm.deleted_at IS NULL AND lm.status <> 'Cancelled'
               AND (   (lm.move_kind = 'relay_delivery' AND NEW.delivery_datetime IS NOT NULL
                        AND lm.move_date IS DISTINCT FROM NEW.delivery_datetime)
                    OR (lm.move_kind = 'relay_loading' AND NEW.loading_datetime IS NOT NULL
                        AND lm.move_date IS DISTINCT FROM NEW.loading_datetime))
             RETURNING lm.id, lm.move_date LOOP
      INSERT INTO audit_log (actor, role, action, table_name, record_id, before_data, after_data, created_at)
      VALUES ('trigger:local_moves_follow', 'system', 'update', 'local_moves', r.id::text,
              jsonb_build_object('parent_order_id', NEW.id),
              jsonb_build_object('move_date', r.move_date, 'reason', 'order ' || NEW.id || ' day moved'), now());
    END LOOP;
    RETURN NULL;
  END $f$;
  CREATE TRIGGER local_moves_follow_order
    AFTER UPDATE OF status, loading_datetime, delivery_datetime ON public.orders
    FOR EACH ROW WHEN (
         (NEW.status = 'Cancelled' AND OLD.status IS DISTINCT FROM 'Cancelled')
      OR OLD.delivery_datetime IS DISTINCT FROM NEW.delivery_datetime
      OR OLD.loading_datetime IS DISTINCT FROM NEW.loading_datetime)
    EXECUTE FUNCTION public.local_moves_follow_order();

  -- 5. PAYROLL: ONE line per (local driver, day), from relays only. rt_id stays NULL on purpose:
  --    ct_v_rt_costs and dl_rt_live key on one ledger line per RT - the international's.
  ALTER TABLE public.dl_entries ADD COLUMN local_move_id bigint REFERENCES public.local_moves (id);
  ALTER TABLE public.dl_entries
    ADD CONSTRAINT dl_one_origin CHECK (rt_id IS NULL OR local_move_id IS NULL),
    ADD CONSTRAINT dl_lm_is_trip CHECK (local_move_id IS NULL OR entry_type = 'trip');
  -- The rule against paying a groupage three times lives here, not in a screen.
  CREATE UNIQUE INDEX dl_local_day_live ON public.dl_entries (driver_id, entry_date)
    WHERE local_move_id IS NOT NULL AND deleted_at IS NULL;

  CREATE FUNCTION public.dl_local_day_sync(p_driver bigint, p_day date) RETURNS void
    LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $f$
  DECLARE
    live dl_entries%rowtype; has_money boolean; valued boolean; anchor bigint; route_txt text;
    stamp text := ' (' || to_char(now() AT TIME ZONE 'Europe/Athens', 'DD/MM/YYYY') || ')';
    sep text := ' ' || chr(183) || ' ';
    -- Greek labels from base64 (this file stays ASCII). Transliterated:
    w_local   text := convert_from(decode('zqTOn86gzpnOms6f', 'base64'), 'UTF8');          -- TOPIKO
    w_deliv   text := convert_from(decode('z4DOsc+BzqzOtM6/z4POtw==', 'base64'), 'UTF8');  -- paradosi
    w_load    text := convert_from(decode('z4bPjM+Bz4TPic+Dzrc=', 'base64'), 'UTF8');      -- fortosi
    t_gone    text := convert_from(decode('zqTOv8+AzrnOus6tz4IgzrrOuc69zq7Pg861zrnPgjogzrrOsc68zq/OsSDOts+Jzr3PhM6xzr3OriDOus6vzr3Ot8+Dzrcgz4TOt8+CIM63zrzOrc+BzrHPgg==', 'base64'), 'UTF8');
                                    -- Topikes kiniseis: kamia zontani kinisi tis imeras
    r_gone    text := convert_from(decode('z4TOv8+AzrnOus6tz4IgzrrOuc69zq7Pg861zrnPgjogzrrOsc68zq/OsSDOts+Jzr3PhM6xzr3OriDPgM65zrE=', 'base64'), 'UTF8');
                                    -- topikes kiniseis: kamia zontani pia
    r_changed text := convert_from(decode('zqzOu867zrHOvs6xzr0gzr/OuSDPhM6/z4DOuc66zq3PgiDOus65zr3Ors+DzrXOuc+CIM+EzrfPgiDOt868zq3Pgc6xz4I=', 'base64'), 'UTF8');
                                    -- allaxan oi topikes kiniseis tis imeras
  BEGIN
    IF p_driver IS NULL OR p_day IS NULL THEN RETURN; END IF;
    -- Serialise every writer of this (driver, day). Without it two relays saved at once (api.js
    -- runs requests in parallel; two dispatchers; an order day move meeting a save) both see "no
    -- line", both INSERT, and the second dies on dl_local_day_live - taking the save with it.
    -- The day enters the key as a number: date-to-text follows DateStyle, and the SQL editor and
    -- PostgREST must take the SAME lock.
    PERFORM pg_advisory_xact_lock(hashtext('dl_local_day'), hashtext(p_driver::text || ':' || (p_day - DATE '2000-01-01')::text));

    -- OWNER-Q2 answered 5/10 (every relay driver: daily TOPIKO line): no driver is exempt and
    -- nothing about the driver is read - a live relay of his that day is the only thing that
    -- decides whether the day has a line.

    -- Label = order numbers only (Order No = orders.id, never renamed), so the label never goes
    -- stale and a changed label always means a changed set of relays.
    SELECT min(lm.id),
           w_local || sep || string_agg(CASE lm.move_kind WHEN 'relay_delivery' THEN w_deliv ELSE w_load END
                                        || ' ' || lm.parent_order_id, sep ORDER BY lm.id)
      INTO anchor, route_txt
      FROM local_moves lm
     WHERE lm.driver_id = p_driver AND lm.move_date = p_day AND lm.move_kind <> 'local'
       AND lm.deleted_at IS NULL AND lm.status <> 'Cancelled';

    SELECT * INTO live FROM dl_entries
     WHERE driver_id = p_driver AND entry_date = p_day AND local_move_id IS NOT NULL AND deleted_at IS NULL;
    -- Money = a non-zero amount. "Value 0" is accounting saying "nothing is owed": a line holding
    -- only zeros is cancelled like an empty one, instead of waiting in review (B-08) for nothing.
    has_money := coalesce(live.trip_value, 0) <> 0 OR coalesce(live.advance, 0) <> 0 OR coalesce(live.expenses, 0) <> 0;
    -- Valued = accounting typed ANY amount, "value 0" included. Used for the relabel below, not for
    -- the cancel path: a day settled at 0 that then gets ANOTHER relay must be looked at again.
    -- With has_money there, the new relay would be settled at 0 silently - no NULL amount (not
    -- pending), a line exists (B-64 quiet). (front review, round 2, 4/10)
    valued := live.trip_value IS NOT NULL OR live.advance IS NOT NULL OR live.expenses IS NOT NULL;

    IF anchor IS NULL THEN                                  -- no live relay left that day
      IF live.id IS NULL THEN RETURN; END IF;
      IF has_money THEN                                     -- possibly owed: flag, never drop silently
        -- Skip only while the line is STILL flagged for this reason (a repeat sync adds no second
        -- note). Not "the reason is somewhere in the note": accounting's check clears the flag and
        -- keeps the note, so after clear -> relay re-added -> relay deleted again that test would
        -- leave a paid line with no relay and no flag (review round 3, 5/10).
        UPDATE dl_entries SET needs_review = true, updated_at = now(),
               review_note = concat_ws(sep, review_note, r_gone || stamp)
         WHERE id = live.id
           AND NOT (needs_review AND position(r_gone IN coalesce(review_note, '')) > 0);
      ELSE
        UPDATE dl_entries SET deleted_at = now(), updated_at = now(), deleted_reason = t_gone
         WHERE id = live.id;
      END IF;
      RETURN;
    END IF;

    IF live.id IS NULL THEN
      -- amounts stay NULL on purpose, same rule as RT lines (owner 5/9): accounting enters them
      INSERT INTO dl_entries (driver_id, entry_type, entry_date, date_end, route, local_move_id, source, created_by)
      VALUES (p_driver, 'trip', p_day, p_day, route_txt, anchor, 'auto', 'trigger:local_move');
      RETURN;
    END IF;

    -- The label belongs to the trigger, not to money: always refreshed. A changed set of relays
    -- after a value was written (even 0) goes to review (B-08); accounting clears it with a reason.
    UPDATE dl_entries SET local_move_id = anchor, route = route_txt, updated_at = now(),
           needs_review = needs_review OR (valued AND route IS DISTINCT FROM route_txt),
           review_note = CASE WHEN valued AND route IS DISTINCT FROM route_txt
                              THEN concat_ws(sep, review_note, r_changed || stamp) ELSE review_note END
     WHERE id = live.id AND (local_move_id IS DISTINCT FROM anchor OR route IS DISTINCT FROM route_txt);
  END $f$;

  CREATE FUNCTION public.dl_sync_from_local_move() RETURNS trigger
    LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $f$
  BEGIN
    -- Plain local moves are never paid by a line (Weekly National errands, as today).
    IF NEW.move_kind = 'local' THEN RETURN NULL; END IF;
    IF TG_OP = 'UPDATE' AND (OLD.driver_id, OLD.move_date) IS DISTINCT FROM (NEW.driver_id, NEW.move_date) THEN
      -- fixed lock order (earlier day, then lower driver id first): two crossing moves cannot deadlock
      IF (OLD.move_date, coalesce(OLD.driver_id, 0)) < (NEW.move_date, coalesce(NEW.driver_id, 0)) THEN
        PERFORM dl_local_day_sync(OLD.driver_id, OLD.move_date);
        PERFORM dl_local_day_sync(NEW.driver_id, NEW.move_date);
      ELSE
        PERFORM dl_local_day_sync(NEW.driver_id, NEW.move_date);
        PERFORM dl_local_day_sync(OLD.driver_id, OLD.move_date);
      END IF;
    ELSE
      PERFORM dl_local_day_sync(NEW.driver_id, NEW.move_date);
    END IF;
    RETURN NULL;
  END $f$;
  -- Only what changes who/when is paid; kind and order are immutable (step 2); time, pallets,
  -- notes, trailer, truck do not touch payroll.
  CREATE TRIGGER dl_sync_from_local_move
    AFTER INSERT OR UPDATE OF driver_id, move_date, deleted_at, status ON public.local_moves
    FOR EACH ROW EXECUTE FUNCTION public.dl_sync_from_local_move();

  -- A local line belongs to the system, with ONE exit for accounting (coordinator D3 4/10): cancel
  -- with a reason (dl_cancel_reason) when the line stands for nothing - no live relay of that driver
  -- is left that day. A day with a live relay keeps its line, whoever the driver (owner 5/10: no
  -- distinction between drivers; else B-64 'unpaid'); "value 0" settles it. Never restored:
  -- dl_local_day_sync writes a new line when a relay returns. Here, not only in the Worker, so
  -- every writer obeys it (principle 4); dl_local_day_sync's own cancels meet exactly this condition.
  CREATE FUNCTION public.dl_local_line_guard() RETURNS trigger
    LANGUAGE plpgsql SET search_path = public AS $f$
  BEGIN
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
      RAISE EXCEPTION 'local_relay: a cancelled local payroll line is not restored - it comes back by itself when a relay of that driver and day returns'
        USING ERRCODE = '23514', HINT = 'local_relay:line_restore';
    END IF;
    IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL
       AND EXISTS (SELECT 1 FROM local_moves lm
                    WHERE lm.driver_id = OLD.driver_id AND lm.move_date = OLD.entry_date AND lm.move_kind <> 'local'
                      AND lm.deleted_at IS NULL AND lm.status <> 'Cancelled') THEN
      RAISE EXCEPTION 'local_relay: line % pays a live relay of that driver and day - enter value 0 or change the relay, do not cancel the line', OLD.id
        USING ERRCODE = '23514', HINT = 'local_relay:line_has_relay';
    END IF;
    RETURN NEW;
  END $f$;
  CREATE TRIGGER dl_local_line_guard BEFORE UPDATE OF deleted_at ON public.dl_entries
    FOR EACH ROW WHEN (OLD.local_move_id IS NOT NULL AND OLD.deleted_at IS DISTINCT FROM NEW.deleted_at)
    EXECUTE FUNCTION public.dl_local_line_guard();

  -- 6. THE LEDGER VIEW: the 30 columns exactly as today (deparsed text of 4/10, proven below
  --    against the live definition) + two appended (CREATE OR REPLACE VIEW only allows appending;
  --    owner and grants are kept). relay_info is jsonb with ASCII keys - the screens render it:
  --      LIVE local day line: {"kind":"local_day",
  --                       "moves":[{"id","move_kind","order_id","rt_codes":["RT-..",..]}]}
  --        (one entry per relay - the RT codes of its order are an array, so a relay never
  --         repeats; moves [] = no live relay left that day = cancel allowed, dl_local_line_guard)
  --      CANCELLED local line: NULL - the day's live relays belong to the live line, not to this
  --        one (the screens show route_text, the label the line had)
  --      RT line with relays on its orders: {"kind":"rt","relays":[{"id","move_kind","order_id",
  --                       "driver_id","driver_name","move_date"}]}
  --        (OWNER-Q4 answered 4/10 (no auto-reduction) - accounting sees who did the local part)
  --      anything else: NULL. No amounts in relay_info. Only keys a screen reads (principle 8).
  CREATE OR REPLACE VIEW public.dl_v_entries WITH (security_invoker = true) AS
   SELECT e.id,
      e.driver_id,
      e.entry_type,
      e.entry_date,
      e.date_end,
      e.rt_id,
      rt.code AS rt_code,
      COALESCE(e.route, rr.route_text, rt.code) AS route_text,
      e.trip_value,
      e.advance,
      e.expenses,
      e.amount,
      e.balance_delta,
      e.source,
      e.import_batch,
      e.needs_review,
      e.review_note,
      e.note,
      e.deleted_at,
      e.deleted_reason,
      e.created_by,
      e.created_at,
      e.updated_at,
      (e.deleted_at IS NOT NULL) AS cancelled,
      ((e.entry_type = 'trip'::text) AND (e.trip_value IS NULL) AND (e.deleted_at IS NULL)) AS pending,
      sum(
          CASE
              WHEN (e.deleted_at IS NULL) THEN e.balance_delta
              ELSE (0)::numeric
          END) OVER (PARTITION BY e.driver_id ORDER BY e.entry_date, e.id ROWS UNBOUNDED PRECEDING) AS running_balance,
          CASE
              WHEN (e.route IS NULL) THEN rr.route_legs
              ELSE NULL::jsonb
          END AS route_legs,
      (COALESCE(c.n, (0)::bigint))::integer AS cash_lines,
      COALESCE(c.s, (0)::numeric) AS cash_sum,
      e.expenses_auto,
      e.local_move_id,
      CASE WHEN e.local_move_id IS NOT NULL THEN lr.info ELSE rl.info END AS relay_info
     FROM (((dl_entries e
       LEFT JOIN ct_round_trips rt ON ((rt.id = e.rt_id)))
       LEFT JOIN dl_v_rt_route rr ON ((rr.rt_id = e.rt_id)))
       LEFT JOIN LATERAL ( SELECT count(*) AS n,
              sum((l.net + COALESCE(l.vat, (0)::numeric))) AS s
             FROM ct_cost_lines l
            WHERE ((l.rt_id = e.rt_id) AND (l.pay_source = 'CASH'::text))) c ON ((e.rt_id IS NOT NULL)))
       -- LIVE local day line -> its relays and the RTs they serve (live, so an RT made later shows)
       LEFT JOIN LATERAL ( SELECT jsonb_build_object(
                'kind', 'local_day',
                'moves', coalesce(jsonb_agg(jsonb_build_object(
                    'id', lm.id, 'move_kind', lm.move_kind, 'order_id', lm.parent_order_id,
                    'rt_codes', (SELECT coalesce(jsonb_agg(r2.code ORDER BY r2.id), '[]'::jsonb)
                                   FROM ct_rt_legs l2 JOIN ct_round_trips r2 ON r2.id = l2.rt_id AND r2.status <> 'cancelled'
                                  WHERE l2.order_id = lm.parent_order_id)) ORDER BY lm.id), '[]'::jsonb)) AS info
             FROM local_moves lm
            WHERE lm.driver_id = e.driver_id AND lm.move_date = e.entry_date AND lm.move_kind <> 'local'
              AND lm.deleted_at IS NULL AND lm.status <> 'Cancelled') lr ON e.local_move_id IS NOT NULL AND e.deleted_at IS NULL
       -- international RT line -> who did the local part, when (no amounts)
       LEFT JOIN LATERAL ( SELECT jsonb_build_object('kind', 'rt', 'relays', jsonb_agg(jsonb_build_object(
                    'id', lm.id, 'move_kind', lm.move_kind, 'order_id', lm.parent_order_id,
                    'driver_id', lm.driver_id, 'driver_name', d.full_name,
                    'move_date', lm.move_date) ORDER BY lm.id)) AS info
             FROM ct_rt_legs l3
             JOIN local_moves lm ON lm.parent_order_id = l3.order_id AND lm.move_kind <> 'local'
                                AND lm.deleted_at IS NULL AND lm.status <> 'Cancelled'
             LEFT JOIN drivers d ON d.id = lm.driver_id
            WHERE l3.rt_id = e.rt_id
           HAVING count(*) > 0) rl ON e.rt_id IS NOT NULL;

  -- 7. BORN CLOSED (principle 5): Supabase's default ACL gives EXECUTE on every new function to
  --    PUBLIC, anon, authenticated and service_role. Trigger functions are never called directly
  --    and EXECUTE is not checked when a trigger fires; dl_local_day_sync is callable and SECURITY
  --    DEFINER - only its owner (postgres, via the SECURITY DEFINER trigger dl_sync_from_local_move)
  --    may run it.
  REVOKE ALL ON FUNCTION public.local_moves_before(), public.local_moves_follow_order(),
    public.dl_local_day_sync(bigint, date), public.dl_sync_from_local_move(), public.dl_local_line_guard()
    FROM PUBLIC, anon, authenticated, service_role;

  -- 8. AUDITOR in the SAME run, so B-09 never sees a local line first. Texts = the catalog files
  --    tms-auditor/checks/B-09, B-63, B-64, B-65 .sql (generated, base64 for Greek; md5-proven below).
  --    B-09 sql/ids/exceptions only: every column the owner may have changed by hand stays.
  UPDATE monitoring.checks SET
    sql_text = $m$SELECT count(*) FROM dl_entries d WHERE d.entry_type='trip' AND d.source='auto' AND d.deleted_at IS NULL AND d.local_move_id IS NULL
 AND (d.rt_id IS NULL OR EXISTS (SELECT 1 FROM ct_round_trips r WHERE r.id=d.rt_id AND r.status='cancelled'))$m$,
    ids_sql = $m$SELECT coalesce(array_agg(x ORDER BY x), '{}') FROM (SELECT d.id::text AS x FROM dl_entries d WHERE d.entry_type='trip' AND d.source='auto' AND d.deleted_at IS NULL AND d.local_move_id IS NULL
 AND (d.rt_id IS NULL OR EXISTS (SELECT 1 FROM ct_round_trips r WHERE r.id=d.rt_id AND r.status='cancelled')) LIMIT 50) s$m$,
    exceptions = convert_from(decode('c291cmNlPSdleGNlbCcgKM65z4PPhM6/z4HOuc66z4wgNi85KSDPgM6/z4TOrS4gzpPPgc6xzrzOvM6tz4Igz4TOv8+AzrnOus6/z40gzr/OtM63zrPOv8+NIChsb2NhbF9tb3ZlX2lkLCDPh8+Jz4HOr8+CIM6zz43Pgc6/IM61zrogz4PPh861zrTOuc6xz4POvM6/z40pIM61zrrPhM+Mz4I6IM+EzrnPgiDOtc67zq3Os8+HzrXOuSDOvyBCLTY0Lg==', 'base64'), 'UTF8')
   WHERE id = 'B-09';
  GET DIAGNOSTICS k = ROW_COUNT;
  IF k <> 1 THEN RAISE EXCEPTION '060: B-09 updated % rows', k; END IF;
  INSERT INTO monitoring.checks (id, title, flows, sql_text, ids_sql, entity_table, red_op, red_value, baseline, severity,
    schedule_tag, is_queue, impact, next_step, exceptions, tolerance, enabled, disabled_reason) VALUES
    ($m$B-63$m$,
     convert_from(decode('zqTOv8+AzrnOus6uIM+AzrHPgc6szrTOv8+Dzrcvz4bPjM+Bz4TPic+Dzrcgz4fPic+Bzq/PgiDPhM6/z4DOuc66z4wgzr/OtM63zrPPjCAoz4POrs68zrXPgc6xLCDOsc+Nz4HOuc6/IM6uIM61zrrPgM+Bz4zOuM61z4POvM63KQ==', 'base64'), 'UTF8'),
     ARRAY[$m$F-22$m$,$m$F-35$m$]::text[],
     $m$SELECT count(*) FROM local_moves lm JOIN orders o ON o.id=lm.parent_order_id
 WHERE lm.move_kind<>'local' AND lm.deleted_at IS NULL AND lm.status<>'Cancelled' AND lm.driver_id IS NULL
 AND lm.move_date <= (now() AT TIME ZONE 'Europe/Athens')::date + 1
 AND NOT (coalesce(o.status,'')='Delivered' OR (lm.move_kind='relay_loading' AND coalesce(o.status,'')='In Transit'))$m$,
     $m$SELECT coalesce(array_agg(x ORDER BY x), '{}') FROM (SELECT coalesce(lm.legacy_id, lm.id::text) AS x FROM local_moves lm JOIN orders o ON o.id=lm.parent_order_id
 WHERE lm.move_kind<>'local' AND lm.deleted_at IS NULL AND lm.status<>'Cancelled' AND lm.driver_id IS NULL
 AND lm.move_date <= (now() AT TIME ZONE 'Europe/Athens')::date + 1
 AND NOT (coalesce(o.status,'')='Delivered' OR (lm.move_kind='relay_loading' AND coalesce(o.status,'')='In Transit')) LIMIT 50) s$m$,
     $m$local_moves$m$,
     $m$>$m$,
     0,
     NULL,
     $m$P2$m$,
     $m$hourly$m$,
     false,
     convert_from(decode('zpcgz4DOsc+BzrHOs86zzrXOu86vzrEgzrTOt867z47OuM63zrrOtSDCq868zrUgz4TOv8+AzrnOus+MIM6/zrTOt86zz4zCuyDOsc67zrvOrCDOus6xzr3Otc6vz4IgzrTOtc69IM6/z4HOr8+Dz4TOt866zrU6IM+Dz4TOuc+CIDA1OjMwIM+Ezr8gzpfOvM61z4HOrs+DzrnOvyDOtM61zq/Ph869zrXOuSDCq86kzp/OoC4gzqDOoc6fzqMgzpHOnc6RzpjOlc6jzpfCuyDOus6xzrkgzrcgz4DOsc+BzqzOtM6/z4POty/Phs+Mz4HPhM+Jz4POtyDOtM61zr0gzq3Ph861zrkgzrXOus+EzrXOu861z4PPhM6uLg==', 'base64'), 'UTF8'),
     convert_from(decode('zpXOss60zr/OvM6xzrTOuc6xzq/OvyDOlM65zrXOuM69z47OvSDihpIgzrcgz4DOsc+BzrHOs86zzrXOu86vzrEg4oaSIMKr4oCmzrzOtSDPhM6/z4DOuc66z4wgzr/OtM63zrPPjMK7OiDPgM6/zrnOv8+CIM+EzrfOvSDOus6szr3Otc65OyAozrHOvc6szrPOvc+Jz4POtyk=', 'base64'), 'UTF8'),
     convert_from(decode('zpzOtc+Ez4HOrCDOvM+Mzr3OvyDPhM6/z4DOuc66zq3PgiDOvM61IM+AzrHPgc6xzrPOs861zrvOr86xIChyZWxheV9kZWxpdmVyeS9yZWxheV9sb2FkaW5nKSDOvM61IM68zq3Pgc6xIM6tz4nPgiDOsc+Nz4HOuc6/ICjOkc64zq7Ovc6xKSDOriDOtc66z4DPgc+MzrjOtc+DzrzOtc+CLiDOoM6xz4HOsc6zzrPOtc67zq/OsSDOrs60zrcgRGVsaXZlcmVkICjOriBJbiBUcmFuc2l0IM6zzrnOsSDPhM6/z4DOuc66zq4gz4bPjM+Bz4TPic+DzrcpIM61zrrPhM+Mz4I6IM63IM60zr/Phc67zrXOuc6sIM6tzrPOuc69zrUuIM6fzrkgzrHPgM67zq3PgiDPhM6/z4DOuc66zq3PgiDOus65zr3Ors+DzrXOuc+CIM+Ezr/PhSDOlc6yzrTOv868zrHOtM65zrHOr86/z4UgzpXOuM69zrnOus+Ozr0gKG1vdmVfa2luZD0nbG9jYWwnKSDOtc66z4TPjM+CLg==', 'base64'), 'UTF8'),
     NULL,
     true,
     NULL),
    ($m$B-64$m$,
     convert_from(decode('zqTOv8+AzrnOus+Mz4Igzr/OtM63zrPPjM+CIOKGlCDOvM65z4POuM6/zrTOv8+Dzq/OsSAozrTOv8+FzrvOtc65zqwgz4fPic+Bzq/PgiDOs8+BzrHOvM68zq4sIM6zz4HOsc68zrzOriDPh8+Jz4HOr8+CIM60zr/Phc67zrXOuc6sKQ==', 'base64'), 'UTF8'),
     ARRAY[$m$F-22$m$,$m$F-35$m$]::text[],
     $m$SELECT (SELECT count(*) FROM (SELECT lm.driver_id, lm.move_date FROM local_moves lm
   WHERE lm.move_kind<>'local' AND lm.deleted_at IS NULL AND lm.status<>'Cancelled' AND lm.driver_id IS NOT NULL
   GROUP BY lm.driver_id, lm.move_date) k
  WHERE NOT EXISTS (SELECT 1 FROM dl_entries e WHERE e.local_move_id IS NOT NULL AND e.deleted_at IS NULL AND e.driver_id=k.driver_id AND e.entry_date=k.move_date))
 + (SELECT count(*) FROM dl_entries e WHERE e.local_move_id IS NOT NULL AND e.deleted_at IS NULL AND NOT e.needs_review
  AND coalesce(e.trip_value,0)=0 AND coalesce(e.advance,0)=0 AND coalesce(e.expenses,0)=0
  AND NOT EXISTS (SELECT 1 FROM local_moves lm WHERE lm.move_kind<>'local' AND lm.driver_id=e.driver_id AND lm.move_date=e.entry_date AND lm.deleted_at IS NULL AND lm.status<>'Cancelled'))$m$,
     $m$SELECT coalesce(array_agg(x ORDER BY x), '{}') FROM (SELECT 'unpaid:' || k.driver_id || ':' || k.move_date AS x FROM (SELECT lm.driver_id, lm.move_date FROM local_moves lm
   WHERE lm.move_kind<>'local' AND lm.deleted_at IS NULL AND lm.status<>'Cancelled' AND lm.driver_id IS NOT NULL
   GROUP BY lm.driver_id, lm.move_date) k
  WHERE NOT EXISTS (SELECT 1 FROM dl_entries e WHERE e.local_move_id IS NOT NULL AND e.deleted_at IS NULL AND e.driver_id=k.driver_id AND e.entry_date=k.move_date)
 UNION ALL SELECT 'orphan:' || e.id FROM dl_entries e WHERE e.local_move_id IS NOT NULL AND e.deleted_at IS NULL AND NOT e.needs_review
  AND coalesce(e.trip_value,0)=0 AND coalesce(e.advance,0)=0 AND coalesce(e.expenses,0)=0
  AND NOT EXISTS (SELECT 1 FROM local_moves lm WHERE lm.move_kind<>'local' AND lm.driver_id=e.driver_id AND lm.move_date=e.entry_date AND lm.deleted_at IS NULL AND lm.status<>'Cancelled') LIMIT 50) s$m$,
     NULL,
     $m$>$m$,
     0,
     NULL,
     $m$P2$m$,
     $m$hourly$m$,
     false,
     convert_from(decode('zp/OtM63zrPPjM+CIM+Azr/PhSDOrc66zrHOvc61IM+Ezr/PgM65zrrOriDOus6vzr3Ot8+DzrcgzrzOrc69zrXOuSDPh8+Jz4HOr8+CIM6zz4HOsc68zrzOriDCq86kzp/OoM6ZzprOn8K7IM+Dz4TOtyDOvM65z4POuM6/zrTOv8+Dzq/OsSDPhM6/z4UgKM6xz4DOu86uz4HPic+EzrcgzrTOv8+FzrvOtc65zqwpLCDOriDPhc+AzqzPgc+HzrXOuSDOs8+BzrHOvM68zq4gwqvOpM6fzqDOmc6azp/CuyDPh8+Jz4HOr8+CIM+Azr/Pg8+MIM66zrHOuSDPh8+Jz4HOr8+CIM62z4nOvc+EzrHOvc6uIM+Ezr/PgM65zrrOriDOus6vzr3Ot8+DzrcgzrXOus61zq/Ovc63IM+EzrcgzrzOrc+BzrEu', 'base64'), 'UTF8'),
     convert_from(decode('zpzOuc+DzrjOv860zr/Pg86vzrEg4oaSIM6/IM6/zrTOt86zz4zPgiDihpIgzrcgzrzOrc+BzrEuIG9ycGhhbjogwqvOkc66z43Pgc+Jz4POt8K7IM68zrUgzrHOuc+EzrnOv867zr/Os86vzrEgKM63IM6yzqzPg863IM+EzrfOvSDOtc+AzrnPhM+Bzq3PgM61zrkgzrzPjM69zr8gz4POtSDOvM6tz4HOsSDPh8+Jz4HOr8+CIM62z4nOvc+EzrHOvc6uIM+Ezr/PgM65zrrOriDPhM6/z4Ugzr/OtM63zrPOv8+NKS4gdW5wYWlkOiDOtyDOs8+BzrHOvM68zq4gzrPPgc6sz4bOtc+EzrHOuSDOvM+Mzr3OtyDPhM63z4Ig4oCUIM6xzr0gzrvOtc6vz4DOtc65LCDOus6/zq/PhM6xIM+Ezr/OvSBCLTU0ICh0cmlnZ2Vycyku', 'base64'), 'UTF8'),
     convert_from(decode('zprOrM64zrUgzr/OtM63zrPPjM+CIM+Azr/PhSDOus6szr3Otc65IM+Ezr/PgM65zrrOriDOus6vzr3Ot8+Dzrcgz4DOsc6vz4HOvc61zrkgzrPPgc6xzrzOvM6uIMKrzqTOn86gzpnOms6fwrsgz4PPhM63IM68zrnPg864zr/OtM6/z4POr86xIM+Ezr/PhSwgzrzOr86xIM6xzr3OrCDOvM6tz4HOsSDigJQgz4fPic+Bzq/PgiDOtM65zqzOus+BzrnPg863IM6/zrTOt86zz47OvSAob3duZXIgNS8xMCkuIM6Tz4HOsc68zrzOrc+CIMKrzrjOrc67zrXOuSDOrc67zrXOs8+Hzr/CuyDOtc66z4TPjM+CICjPhM65z4IgzrzOtc+Ez4HOrCDOvyBCLTA4KS4gb3JwaGFuID0gzrzPjM69zr8gzrPPgc6xzrzOvM6uIM6nzqnOoc6ZzqMgz4DOv8+Dz4w6IM6zz4HOsc68zrzOriDOvM61IM+Azr/Pg8+MIM+Azr/PhSDOrc68zrXOuc69zrUgz4fPic+Bzq/PgiDPhM6/z4DOuc66zq4gz4DOt86zzrHOr869zrXOuSDPgM+Bz47PhM6xIM+DzrUgwqvOuM6tzrvOtc65IM6tzrvOtc6zz4fOv8K7IChCLTA4KcK3IM6xzr0gz4TOvyDOu86/zrPOuc+Dz4TOrs+BzrnOvyDPhM63zr0gzrXOu86tzrPOvs61zrkgzrrOsc65IM+EzrfOvSDOus+BzrHPhM6uz4POtc65LCDOtc6vzr3Osc65IM6xz4DPjM+GzrHPg863LCDPjM+HzrkgzrvOrM64zr/PgiDigJQgzrrOsc65IM6+zrHOvc6xzrzPgM6xzq/Ovc61zrkgz4POtSDOrc67zrXOs8+Hzr8gzrzPjM67zrnPgiDOsc67zrvOrM6+zr/Phc69IM6+zrHOvc6sIM6/zrkgz4TOv8+AzrnOus6tz4Igz4TOt8+CIM68zq3Pgc6xz4IuIMKrzpHOvs6vzrEgMMK7ID0gz4fPic+Bzq/PgiDPgM6/z4PPjC4gaWRzOiB1bnBhaWQ6PM6/zrTOt86zz4zPgj46PM68zq3Pgc6xPiDCtyBvcnBoYW46PM6zz4HOsc68zrzOrj4u', 'base64'), 'UTF8'),
     NULL,
     true,
     NULL),
    ($m$B-65$m$,
     convert_from(decode('zqTOv8+AzrnOus6uIM+AzrHPgc6szrTOv8+Dzrcvz4bPjM+Bz4TPic+DzrcgzrHPg8+Fzr3Otc+Azq7PgiDOvM61IM+EzrfOvSDPgM6xz4HOsc6zzrPOtc67zq/OsSDPhM63z4I=', 'base64'), 'UTF8'),
     ARRAY[$m$F-22$m$,$m$F-35$m$]::text[],
     $m$SELECT count(*) FROM local_moves lm JOIN orders o ON o.id=lm.parent_order_id
 WHERE lm.move_kind<>'local' AND lm.deleted_at IS NULL AND lm.status<>'Cancelled' AND (
 o.deleted_at IS NOT NULL OR coalesce(o.status,'')='Cancelled' OR coalesce(o.ops_status,'')='Provisional'
 OR (CASE lm.move_kind WHEN 'relay_delivery' THEN o.delivery_datetime ELSE o.loading_datetime END) IS NULL
 OR lm.move_date <> (CASE lm.move_kind WHEN 'relay_delivery' THEN o.delivery_datetime ELSE o.loading_datetime END)
 OR lm.driver_id = o.driver_id OR lm.truck_id = o.truck_id
 OR (lm.truck_id IS NULL AND o.truck_id IS NULL AND lm.move_date <= (now() AT TIME ZONE 'Europe/Athens')::date + 1)
 OR coalesce(o.veroia_switch,false)
 OR coalesce(o.direction,'') <> (CASE lm.move_kind WHEN 'relay_delivery' THEN 'Import' ELSE 'Export' END)
 OR EXISTS (SELECT 1 FROM orders l WHERE l.parent_order_id=o.id AND l.deleted_at IS NULL))$m$,
     $m$SELECT coalesce(array_agg(x ORDER BY x), '{}') FROM (SELECT coalesce(lm.legacy_id, lm.id::text) || ':' || CASE
 WHEN o.deleted_at IS NOT NULL OR coalesce(o.status,'')='Cancelled' THEN 'parent'
 WHEN coalesce(o.ops_status,'')='Provisional' THEN 'preorder'
 WHEN (CASE lm.move_kind WHEN 'relay_delivery' THEN o.delivery_datetime ELSE o.loading_datetime END) IS NULL
   OR lm.move_date <> (CASE lm.move_kind WHEN 'relay_delivery' THEN o.delivery_datetime ELSE o.loading_datetime END) THEN 'day'
 WHEN lm.driver_id = o.driver_id THEN 'same-driver'
 WHEN lm.truck_id = o.truck_id THEN 'truck-copy'
 WHEN lm.truck_id IS NULL AND o.truck_id IS NULL AND lm.move_date <= (now() AT TIME ZONE 'Europe/Athens')::date + 1 THEN 'no-vehicle'
 WHEN coalesce(o.veroia_switch,false) THEN 'vs'
 WHEN coalesce(o.direction,'') <> (CASE lm.move_kind WHEN 'relay_delivery' THEN 'Import' ELSE 'Export' END) THEN 'direction'
 ELSE 'split' END AS x
 FROM local_moves lm JOIN orders o ON o.id=lm.parent_order_id
 WHERE lm.move_kind<>'local' AND lm.deleted_at IS NULL AND lm.status<>'Cancelled' AND (
 o.deleted_at IS NOT NULL OR coalesce(o.status,'')='Cancelled' OR coalesce(o.ops_status,'')='Provisional'
 OR (CASE lm.move_kind WHEN 'relay_delivery' THEN o.delivery_datetime ELSE o.loading_datetime END) IS NULL
 OR lm.move_date <> (CASE lm.move_kind WHEN 'relay_delivery' THEN o.delivery_datetime ELSE o.loading_datetime END)
 OR lm.driver_id = o.driver_id OR lm.truck_id = o.truck_id
 OR (lm.truck_id IS NULL AND o.truck_id IS NULL AND lm.move_date <= (now() AT TIME ZONE 'Europe/Athens')::date + 1)
 OR coalesce(o.veroia_switch,false)
 OR coalesce(o.direction,'') <> (CASE lm.move_kind WHEN 'relay_delivery' THEN 'Import' ELSE 'Export' END)
 OR EXISTS (SELECT 1 FROM orders l WHERE l.parent_order_id=o.id AND l.deleted_at IS NULL)) LIMIT 50) s$m$,
     NULL,
     $m$>$m$,
     0,
     NULL,
     $m$P3$m$,
     $m$daily$m$,
     false,
     convert_from(decode('zpcgz4TOv8+AzrnOus6uIM60zrXOvSDPhM6xzrnPgc65zqzOts61zrkgz4DOuc6xIM68zrUgz4TOt869IM+AzrHPgc6xzrPOs861zrvOr86xOiDOu86szrjOv8+CIM68zq3Pgc6xIM+Dz4TOvyDOl868zrXPgc6uz4POuc6/IM66zrHOuSDPg8+EzrcgzrzOuc+DzrjOv860zr/Pg86vzrEgz4TOv8+FIM+Ezr/PgM65zrrOv8+NLCDPhM6/z4DOuc66z4zPgiDPh8+Jz4HOr8+CIM+Mz4fOt868zrEsIM6uIM+Ezr/PgM65zrrOriDPgM6szr3PiSDPg861IM+AzrHPgc6xzrPOs861zrvOr86xIM+Azr/PhSDOtM61zr0gzrjOsSDOtc66z4TOtc67zrXPg8+EzrXOryDOrc+Ez4POuS4=', 'base64'), 'UTF8'),
     convert_from(decode('zpXOss60zr/OvM6xzrTOuc6xzq/OvyDOlM65zrXOuM69z47OvSDihpIgzrcgz4DOsc+BzrHOs86zzrXOu86vzrE6IM60zrnPjM+BzrjPic+DzrUgzq4gz4POss6uz4POtSDPhM63zr0gz4TOv8+AzrnOus6uICjOsc69zqzOs869z4nPg863KS4gbm8tdmVoaWNsZTogzrHOvc6szrjOtc+DzrUgz4TOt869IM+AzrHPgc6xzrPOs861zrvOr86xIM6uIM60z47Pg861IM+Dz4TOt869IM+Ezr/PgM65zrrOriDCq86szrvOu86/wrsgz4TPgc6szrrPhM6/z4HOsS4=', 'base64'), 'UTF8'),
     convert_from(decode('aWRzID0gPM61zrPOs8+BzrHPhs6uPjo8zrvPjM6zzr/Pgj4sIM6tzr3Osc+CIM67z4zOs86/z4IgzrHOvc6sIM+Ezr/PgM65zrrOriDOvM61IM6xz4XPhM6uIM+Ezrcgz4POtc65z4HOrDogcGFyZW50ICjPg86yzrfPg868zq3Ovc63L86xzrrPhc+Bz4nOvM6tzr3OtyDPgM6xz4HOsc6zzrPOtc67zq/OsSkgwrcgcHJlb3JkZXIgwrcgZGF5ICjOvM6tz4HOsSDiiaAgzrzOrc+BzrEgz4DOtc67zqzPhM63IM6uIM66zrXOvc6uKSDCtyBzYW1lLWRyaXZlciAozr8gz4TOv8+AzrnOus+Mz4IgPSDOvyDOtM65zrXOuM69zq7PgikgwrcgdHJ1Y2stY29weSAoz4TOvyDCq86szrvOu86/wrsgz4bOv8+Bz4TOt86zz4wgPSDPhM63z4Igz4DOsc+BzrHOs86zzrXOu86vzrHPgikgwrcgbm8tdmVoaWNsZSAozr8gz4TOv8+AzrnOus+Mz4IgzrzOtSDCq86vzrTOuc6/wrsgz4TPgc6szrrPhM6/z4HOsSwgzrHOu867zqwgzrcgz4DOsc+BzrHOs86zzrXOu86vzrEgzrTOtc69IM6tz4fOtc65IM+Ez4HOrM66z4TOv8+BzrEg4oCUIM6zzrnOsSDOvM6tz4HOsSDOrc+Jz4IgzrHPjc+BzrnOvykgwrcgdnMgwrcgZGlyZWN0aW9uIMK3IHNwbGl0ICjOtyDPgM6xz4HOsc6zzrPOtc67zq/OsSDPg8+AzqzPg8+EzrfOus61IM+DzrUgz4POus6tzrvOtykuIM6XIM6yzqzPg863IM6xz4HOvc61zq/PhM6xzrkgz4TOsSDOr860zrnOsSDPjM+EzrHOvSDOs8+BzqzPhs61z4TOsc65IM63IM+Ezr/PgM65zrrOrsK3IM61zrTPjiDPhs6xzq/Ovc6/zr3PhM6xzrkgz4zPg86xIM+Az4HOv86tzrrPhc+IzrHOvSDOsc+Az4wgzrHOu867zrHOs86uIM+EzrfPgiDPgM6xz4HOsc6zzrPOtc67zq/Osc+CIM68zrXPhM6sLiDOlc6+zrHOr8+BzrXPg863IM+Ezr8gbm8tdmVoaWNsZTogzrTOtc69IM6xz4DOsc6zzr/Pgc61z43Otc+EzrHOuSDPg8+EzrfOvSDOtc6zzrPPgc6xz4bOriAoz4DPgc6/zrPPgc6xzrzOvM6xz4TOuc+DzrzPjM+CIM+Az4HOuc69IM6xzr3Osc+EzrXOuM61zq8gzrcgz4DOsc+BzrHOs86zzrXOu86vzrEg4oCUIM+Ezr8gz4DOrM69zrXOuyDPgM+Bzr/Otc65zrTOv8+Azr/Ouc61zq8pwrcgzrPOr869zrXPhM6xzrkgzrXPjc+BzrfOvM6xIM68z4zOvc6/IM+Mz4TOsc69IM+Gz4TOrM+DzrXOuSDOtyDOvM6tz4HOsS4=', 'base64'), 'UTF8'),
     NULL,
     true,
     NULL);
  -- B-54 counts enabled non-internal triggers in public: 060 adds exactly 4.
  SELECT count(*) INTO trg_after FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  IF trg_after <> trg_before + 4 THEN
    RAISE EXCEPTION '060 proof: trigger count % -> % (expected +4)', trg_before, trg_after;
  END IF;
  UPDATE monitoring.checks SET red_value = trg_after WHERE id = 'B-54' AND red_value = trg_before;
  GET DIAGNOSTICS k = ROW_COUNT;
  IF k <> 1 THEN RAISE EXCEPTION '060: B-54 not updated (% rows)', k; END IF;

  -- 9. PROOFS inside the block: any failure rolls back everything above.
  SELECT count(*) INTO n FROM pg_constraint WHERE conrelid = 'public.local_moves'::regclass AND contype = 'c'
     AND conname IN ('local_moves_kind_chk', 'local_moves_kind_parent', 'local_moves_relay_points',
                     'local_moves_relay_status', 'local_moves_relay_executor', 'local_moves_relay_trailer');
  IF n <> 6 THEN RAISE EXCEPTION '060 proof: local_moves CHECKs %/6', n; END IF;
  SELECT count(*) INTO n FROM pg_constraint WHERE conrelid = 'public.dl_entries'::regclass AND contype = 'c'
     AND conname IN ('dl_one_origin', 'dl_lm_is_trip');
  IF n <> 2 THEN RAISE EXCEPTION '060 proof: dl_entries CHECKs %/2', n; END IF;
  SELECT count(*) INTO n FROM pg_constraint
   WHERE conrelid = 'public.dl_entries'::regclass AND contype = 'f' AND confrelid = 'public.local_moves'::regclass;
  IF n <> 1 THEN RAISE EXCEPTION '060 proof: dl_entries.local_move_id FK %/1', n; END IF;
  SELECT count(*) INTO n FROM pg_index i JOIN pg_class c ON c.oid = i.indexrelid
   WHERE c.relname IN ('local_moves_relay_once', 'dl_local_day_live') AND i.indisunique AND i.indisvalid;
  IF n <> 2 THEN RAISE EXCEPTION '060 proof: unique indexes %/2', n; END IF;
  SELECT count(*) INTO n FROM pg_trigger WHERE NOT tgisinternal AND tgenabled = 'O'
     AND (   (tgrelid = 'public.local_moves'::regclass AND tgname IN ('local_moves_before', 'dl_sync_from_local_move'))
          OR (tgrelid = 'public.orders'::regclass AND tgname = 'local_moves_follow_order')
          OR (tgrelid = 'public.dl_entries'::regclass AND tgname = 'dl_local_line_guard'));
  IF n <> 4 THEN RAISE EXCEPTION '060 proof: triggers %/4', n; END IF;
  -- 023 = the old text + step 6, character for character
  IF pg_get_functiondef('public.order_soft_delete_unlink()'::regprocedure) <> new_unlink
     OR position('update local_moves lm set deleted_at' IN new_unlink) = 0
     OR position('partner_assignments' IN new_unlink) = 0 THEN
    RAISE EXCEPTION '060 proof: order_soft_delete_unlink is not the 4/10 text + step 6';
  END IF;
  -- dl_v_entries: the 30 old columns deparse exactly as before, the old joins are intact, two
  -- columns appended, same options and grants.
  new_view := pg_get_viewdef('public.dl_v_entries'::regclass);
  sel_prefix := left(old_view, position('e.expenses_auto' IN old_view) + length('e.expenses_auto') - 1);
  old_joins := substring(old_view FROM 'LEFT JOIN ct_round_trips rt.*c ON \(\(e\.rt_id IS NOT NULL\)\)');
  IF left(new_view, length(sel_prefix)) <> sel_prefix OR old_joins IS NULL OR position(old_joins IN new_view) = 0 THEN
    RAISE EXCEPTION '060 proof: dl_v_entries old columns or joins changed';
  END IF;
  SELECT count(*) INTO n FROM pg_attribute
   WHERE attrelid = 'public.dl_v_entries'::regclass AND attnum > 0 AND NOT attisdropped;
  IF n <> view_cols_before + 2
     OR (SELECT attname FROM pg_attribute WHERE attrelid = 'public.dl_v_entries'::regclass AND attnum = view_cols_before + 1) <> 'local_move_id'
     OR (SELECT attname FROM pg_attribute WHERE attrelid = 'public.dl_v_entries'::regclass AND attnum = view_cols_before + 2) <> 'relay_info'
     OR (SELECT relacl::text FROM pg_class WHERE oid = 'public.dl_v_entries'::regclass) IS DISTINCT FROM view_acl_before
     OR NOT (SELECT coalesce('security_invoker=true' = ANY (reloptions), false) FROM pg_class WHERE oid = 'public.dl_v_entries'::regclass) THEN
    RAISE EXCEPTION '060 proof: dl_v_entries columns/options/grants not as expected';
  END IF;
  -- born closed
  SELECT count(*) INTO n FROM pg_proc p
   WHERE p.oid IN ('public.local_moves_before()'::regprocedure, 'public.local_moves_follow_order()'::regprocedure,
                   'public.dl_local_day_sync(bigint,date)'::regprocedure, 'public.dl_sync_from_local_move()'::regprocedure,
                   'public.dl_local_line_guard()'::regprocedure)
     AND NOT has_function_privilege('anon', p.oid, 'EXECUTE')
     AND NOT has_function_privilege('authenticated', p.oid, 'EXECUTE')
     AND NOT has_function_privilege('service_role', p.oid, 'EXECUTE');
  IF n <> 5 THEN RAISE EXCEPTION '060 proof: only % of 5 new functions are closed', n; END IF;
  IF has_table_privilege('anon', 'public.local_moves', 'SELECT') OR has_table_privilege('authenticated', 'public.local_moves', 'SELECT') THEN
    RAISE EXCEPTION '060 proof: anon/authenticated can read local_moves';
  END IF;
  -- auditor rows = catalog (md5 of the generated texts)
  IF NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-09' AND md5(sql_text) = '8be3476c69ef6dba15c0778a2b318ec8' AND md5(ids_sql) = 'f511f0a106d53b6b85d4f4dd04c34979' AND md5(exceptions) = '7d53ecfa0ac2936cd6e29aa2c7bfed2a') THEN
    RAISE EXCEPTION '060 proof: B-09 is not the catalog text';
  END IF;
  SELECT count(*) INTO n FROM monitoring.checks k
    JOIN (VALUES
      ('B-63', '9c8b0400fcea4adcdde4dccdf90e3d09'),
      ('B-64', 'fe6790fbafdd54f9f0bbd0fe337784d1'),
      ('B-65', '040318725578a5707cd2ed04c571ccf8')
    ) e(id, fp) ON e.id = k.id
   WHERE md5(k.title||'|'||k.sql_text||'|'||coalesce(k.ids_sql,'')||'|'||coalesce(k.impact,'')||'|'||coalesce(k.next_step,'')||'|'||coalesce(k.exceptions,'')||'|'||coalesce(k.entity_table,'')||'|'||k.red_op||'|'||k.red_value::text||'|'||k.severity||'|'||k.schedule_tag) = e.fp AND k.enabled;
  IF n <> 3 THEN RAISE EXCEPTION '060 proof: only % of B-63..B-65 match the catalog', n; END IF;
  -- nothing else moved
  IF (SELECT count(*) FROM public.dl_entries WHERE deleted_at IS NULL) <> dl_live_before
     OR (SELECT count(*) FROM public.orders WHERE deleted_at IS NULL) <> orders_before
     OR (SELECT count(*) FROM public.ct_round_trips) <> rts_before THEN
    RAISE EXCEPTION '060 proof: payroll, orders or round trips changed';
  END IF;
  -- Each touched check runs the way run_checks (047) runs it: guard, 10 s timeout, as
  -- tms_check_runner (SELECT only) - a missing GRANT fails HERE. Texts are read before the role
  -- switch (tms_check_runner cannot read schema monitoring).
  FOR r IN SELECT id, sql_text, ids_sql FROM monitoring.checks
            WHERE id IN ('B-09', 'B-54', 'B-63', 'B-64', 'B-65') AND enabled ORDER BY id LOOP
    PERFORM monitoring.check_sql_guard(r.sql_text);
    IF r.ids_sql IS NOT NULL THEN PERFORM monitoring.check_sql_guard(r.ids_sql); END IF;
    PERFORM set_config('statement_timeout', '10000', true);
    SET LOCAL ROLE tms_check_runner;
    EXECUTE r.sql_text INTO v;
    ids := NULL;
    IF r.ids_sql IS NOT NULL THEN EXECUTE r.ids_sql INTO ids; END IF;
    RESET ROLE;
    IF v IS NULL THEN RAISE EXCEPTION '060 proof: % returned NULL', r.id; END IF;
    -- no relay can exist yet, so the three new checks must be 0; B-54 must be green
    IF (r.id IN ('B-63', 'B-64', 'B-65') AND v <> 0) OR (r.id = 'B-54' AND v <> trg_after) THEN
      RAISE EXCEPTION '060 proof: % = % right after the migration', r.id, v;
    END IF;
    RAISE NOTICE '060: % = % (ids %)', r.id, v, coalesce(array_to_string(ids, ','), '');
  END LOOP;

  RAISE NOTICE '060 OK: local relay phase 1 in place; triggers % -> %, B-54 = %; B-63/B-64/B-65 = 0', trg_before, trg_after, trg_after;
END;
  -- ===== end of 060 =====

  -- A: what 060 creates is there (its own proofs already raised if not; this names it in the result)
  BEGIN
    SELECT count(*) INTO dry_n FROM information_schema.columns WHERE table_schema = 'public'
       AND ((table_name = 'local_moves' AND column_name = 'move_kind')
         OR (table_name = 'dl_entries' AND column_name = 'local_move_id') OR (table_name = 'dl_v_entries' AND column_name = 'relay_info'));
    IF dry_n = 3 AND (SELECT count(*) FROM monitoring.checks WHERE id IN ('B-63', 'B-64', 'B-65')) = 3 THEN
      ok := ok + 1; res := res || 'A ok columns, view column and B-63..B-65 in place'::text;
    ELSE bad := bad + 1; res := res || format('A FAIL columns %s/3', dry_n); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('A ERROR ' || SQLERRM);
  END;

  -- B: B-54 moved by exactly the four triggers 060 adds, and equals the live count
  BEGIN
    SELECT count(*) INTO dry_n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
      JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
    IF dry_n = dry_trg_before + 4 AND (SELECT red_value FROM monitoring.checks WHERE id = 'B-54') = dry_n AND dry_b54_before = dry_trg_before THEN
      ok := ok + 1; res := res || format('B ok B-54 %s -> %s (= live triggers)', dry_b54_before, dry_n);
    ELSE bad := bad + 1; res := res || format('B FAIL triggers %s -> %s, B-54 %s -> %s', dry_trg_before, dry_n, dry_b54_before,
                                             (SELECT red_value FROM monitoring.checks WHERE id = 'B-54')); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('B ERROR ' || SQLERRM);
  END;

  -- C: data 060 must not touch - same fingerprint after the block as before it. A save by someone
  --    else during these seconds also changes it (fails closed): the FAIL text says what to do.
  BEGIN
    IF (SELECT md5(
    coalesce((SELECT string_agg(concat_ws(':', id, status, driver_id, truck_id, trailer_id, partner_id, loading_datetime, delivery_datetime, deleted_at), ',' ORDER BY id) FROM public.orders), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, driver_id, entry_type, entry_date, rt_id, trip_value, advance, expenses, amount, deleted_at, needs_review, review_note), ',' ORDER BY id) FROM public.dl_entries), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, status, driver_id, truck_id, trailer_id, date_start, date_end), ',' ORDER BY id) FROM public.ct_round_trips), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, status, driver_id, parent_order_id, parent_nat_load_id, move_date, deleted_at), ',' ORDER BY id) FROM public.local_moves), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, full_name, active, deleted_at), ',' ORDER BY id) FROM public.drivers), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks
              WHERE id NOT IN ('B-09', 'B-54', 'B-63', 'B-64', 'B-65')), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) = dry_fp_before THEN
      ok := ok + 1; res := res || 'C ok orders, payroll, round trips, local_moves, drivers, other checks, sequences unchanged'::text;
    ELSE bad := bad + 1; res := res || 'C FAIL data changed during the dry run - 060 itself, or a save by someone else in those seconds: if A and B are ok, wait 5 minutes and run the dry run once more; if C fails again, stop and copy the panel to the coordinator'::text; END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('C ERROR ' || SQLERRM);
  END;

  RAISE EXCEPTION 'DRY RUN 060 finished - EVERYTHING UNDONE, nothing kept. Result: % OK, % FAIL  ||  %', ok, bad, array_to_string(res, '  |  ');
END
$dry$;
