-- 063 DRY RUN - GENERATED by worker/migrations/drafts/tools/build-063-dryrun.mjs from 063_local_line_guard.sql.
-- DO NOT EDIT BY HAND: edit 063 and regenerate (tms-auditor/test/dryrun-063.test.mjs fails on any drift).
--
-- WHAT: 063's own DO block, statement for statement (every guard, change and proof, B-54 run as
--   tms_check_runner), wrapped in ONE outer DO block that first fingerprints data 063 must not touch, then
--   checks the result, and ENDS WITH A DELIBERATE ERROR. The error rolls the whole block back: NOTHING it did
--   is kept (no function text, no function setting, no trigger change).
-- WHEN: the same evening, AFTER 15:00 (the team works 05:30-14:30), BEFORE 063_local_line_guard.sql. It
--   takes the same lock as 063 (lock_timeout 5 s, then it gives up - run it again a little later).
-- WHY ONE DO BLOCK: the Supabase SQL editor is NOT atomic across statements (lesson 056), but ONE DO
--   block is ONE statement: its final error undoes everything inside it.
-- EXPECTED (the red ERROR is deliberate):
--   ERROR: P0001: DRY RUN 063 finished - EVERYTHING UNDONE, nothing kept. Result: 3 OK, 0 FAIL  ||  A ok ... | B ok triggers T = T, B-54 T | C ok ...
--   (T = the live trigger count = B-54: 35 after 057 + 060.)
--   Anything with FAIL or ERROR in it: do NOT run 063, copy the panel to the coordinator.
--   ONE exception: "2 OK, 1 FAIL" where the FAIL is C alone (A ok, B ok). C fingerprints the payroll lines,
--   the local moves, the auditor rows and every public sequence while the block runs, so ONE save by
--   someone else in those seconds turns it red - it fails closed, nothing was kept. Wait 5 minutes and run
--   the dry run once more; if C fails again, copy the panel to the coordinator.
--   A different message altogether ("063: ...", "063 proof: ...", a lock timeout) is the guard or proof of
--   063 that stopped - exactly what 063 itself would have said. Do NOT run 063.
-- AFTER: SELECT that nothing was kept - the trigger dl_local_line_guard is still on deleted_at only and
--   dl_local_day_sync's config is still only its search_path.
-- Scenarios: A 063's changes exist inside the block; B the trigger count did not move and B-54 equals it;
--   C data 063 must not touch is unchanged (payroll lines, local moves, every auditor row, every public
--   sequence's last_value).

DO $dry$
DECLARE
  ok int := 0; bad int := 0; res text[] := '{}';
  dry_fp_before text; dry_b54_before int; dry_trg_before int; dry_n int;
BEGIN
  -- the B-54 value and the trigger count 063 will meet, and the data it must leave alone
  SELECT red_value INTO dry_b54_before FROM monitoring.checks WHERE id = 'B-54';
  SELECT count(*) INTO dry_trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  SELECT (SELECT md5(
    coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.dl_entries x), '')
 || coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.local_moves x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) INTO dry_fp_before;

  -- ===== 063_local_line_guard.sql, its DO block verbatim (a nested block: its errors stop everything) =====
DECLARE
  n int;
  trg_before int; trg_after int; deleted_at_attnum int;
  dl_live_before bigint; dl_local_before bigint; lm_before bigint;
  old_src text; new_src text; old_rules text;
  r record; v numeric;
BEGIN
  PERFORM set_config('search_path', 'public, extensions', true);
  -- DROP/CREATE TRIGGER on dl_entries need a strong lock: behind an idle open transaction they
  -- would wait forever while every ledger read queues behind them. Give up after 5 s instead -
  -- the whole block rolls back, nothing half-done; run it again later (same as 057/060).
  PERFORM set_config('lock_timeout', '5s', true);

  -- 0. GUARDS (SELECT only): 060 in place, as executed 6/10; 063 not yet.
  IF to_regclass('monitoring.checks') IS NULL THEN
    RAISE EXCEPTION '063: monitoring.checks does not exist (047 must run first)';
  END IF;
  IF to_regprocedure('public.dl_local_line_guard()') IS NULL
     OR to_regprocedure('public.dl_local_day_sync(bigint,date)') IS NULL
     OR NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema = 'public'
                     AND table_name = 'dl_entries' AND column_name = 'local_move_id') THEN
    RAISE EXCEPTION '063: 060 is not applied (dl_local_line_guard / dl_local_day_sync / dl_entries.local_move_id missing) - stop';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_proc p, unnest(p.proconfig) c
              WHERE p.oid = 'public.dl_local_day_sync(bigint,date)'::regprocedure AND c LIKE 'tms.local_day_sync=%')
     OR position('local_relay:line_locked' IN (SELECT prosrc FROM pg_proc WHERE oid = 'public.dl_local_line_guard()'::regprocedure)) > 0 THEN
    RAISE EXCEPTION '063: already applied';
  END IF;
  -- The guard is replaced and the rollback puts 060's text back: refuse if it is not that text.
  SELECT prosrc INTO old_src FROM pg_proc WHERE oid = 'public.dl_local_line_guard()'::regprocedure;
  IF md5(old_src) <> '2b4de99653da7f0859f08b07a410225c' THEN
    RAISE EXCEPTION '063: dl_local_line_guard is not the 060 text (md5 %) - re-measure', md5(old_src);
  END IF;
  -- The flag lets the sync's own writes through: what it writes was read from 060's text.
  IF (SELECT md5(prosrc) FROM pg_proc WHERE oid = 'public.dl_local_day_sync(bigint,date)'::regprocedure)
     <> '297954261e9e8fe2936f6217f31f1e7a'
     OR NOT EXISTS (SELECT 1 FROM pg_proc WHERE oid = 'public.dl_local_day_sync(bigint,date)'::regprocedure
                     AND prosecdef AND proconfig = ARRAY['search_path=public']) THEN
    RAISE EXCEPTION '063: dl_local_day_sync is not the 060 function (body, SECURITY DEFINER, search_path) - re-measure';
  END IF;
  -- The trigger is 060's: row, BEFORE UPDATE OF deleted_at only, enabled, calling the guard.
  SELECT attnum INTO deleted_at_attnum FROM pg_attribute
   WHERE attrelid = 'public.dl_entries'::regclass AND attname = 'deleted_at' AND NOT attisdropped;
  SELECT count(*) INTO n FROM pg_trigger
   WHERE tgrelid = 'public.dl_entries'::regclass AND tgname = 'dl_local_line_guard' AND NOT tgisinternal
     AND tgenabled = 'O' AND tgtype = 19 AND tgfoid = 'public.dl_local_line_guard()'::regprocedure
     AND tgattr::text = deleted_at_attnum::text;
  IF n <> 1 THEN
    RAISE EXCEPTION '063: trigger dl_local_line_guard is not the 060 one (BEFORE UPDATE OF deleted_at) - re-measure';
  END IF;
  SELECT count(*) INTO trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  -- run_checks compares against coalesce(baseline, red_value): B-54 must be green before, and stay.
  IF NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-54' AND red_value = trg_before AND baseline IS NULL) THEN
    RAISE EXCEPTION '063: B-54 red_value is not the live trigger count % (or has a baseline) - a migration changed triggers without bumping it, re-measure', trg_before;
  END IF;
  SELECT count(*) INTO dl_live_before FROM public.dl_entries WHERE deleted_at IS NULL;
  SELECT count(*) INTO dl_local_before FROM public.dl_entries WHERE local_move_id IS NOT NULL;
  SELECT count(*) INTO lm_before FROM public.local_moves;

  -- 1. THE GUARD. Rule 1 is new; rules 2 and 3 are 060's text verbatim (proven below).
  CREATE OR REPLACE FUNCTION public.dl_local_line_guard() RETURNS trigger
    LANGUAGE plpgsql SET search_path = public AS $f$
  BEGIN
    -- 063: who, when and what a local line pays is the relays' (dl_local_day_sync). A hand move
    -- would leave money on a day without a relay while the sync writes a second line for the old day.
    IF (NEW.entry_date, NEW.date_end, NEW.driver_id, NEW.route, NEW.rt_id, NEW.entry_type, NEW.local_move_id)
       IS DISTINCT FROM (OLD.entry_date, OLD.date_end, OLD.driver_id, OLD.route, OLD.rt_id, OLD.entry_type, OLD.local_move_id)
       AND current_setting('tms.local_day_sync', true) IS DISTINCT FROM 'on' THEN
      RAISE EXCEPTION 'local_relay: line % belongs to the relays of its driver and day - its day, driver, route, round trip, type and relay are written only by the system; edit the amounts, the note or the review flag', OLD.id
        USING ERRCODE = '23514', HINT = 'local_relay:line_locked';
    END IF;
    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN
      RAISE EXCEPTION 'local_relay: a cancelled local payroll line is not restored - it comes back by itself when a relay of that driver and day returns'
        USING ERRCODE = '23514', HINT = 'local_relay:line_restore';
    END IF;
    IF OLD.deleted_at IS NULL AND NEW.deleted_at IS NOT NULL
       AND EXISTS (SELECT 1 FROM local_moves lm
                    WHERE lm.driver_id = OLD.driver_id AND lm.move_date = OLD.entry_date AND lm.move_kind <> 'local'
                      AND lm.deleted_at IS NULL AND lm.status <> 'Cancelled') THEN
      RAISE EXCEPTION 'local_relay: line % pays a live relay of that driver and day - enter value 0 or change the relay, do not cancel the line', OLD.id
        USING ERRCODE = '23514', HINT = 'local_relay:line_has_relay';
    END IF;
    RETURN NEW;
  END $f$;

  -- 2. THE SYNC MARKS ITS OWN WRITES (function-level SET: restored by Postgres at every exit).
  ALTER FUNCTION public.dl_local_day_sync(bigint, date) SET tms.local_day_sync = 'on';

  -- 3. THE TRIGGER: the same name, now on the seven columns too.
  DROP TRIGGER dl_local_line_guard ON public.dl_entries;
  CREATE TRIGGER dl_local_line_guard
    BEFORE UPDATE OF deleted_at, entry_date, date_end, driver_id, route, rt_id, entry_type, local_move_id
    ON public.dl_entries
    FOR EACH ROW WHEN ((OLD.local_move_id IS NOT NULL OR NEW.local_move_id IS NOT NULL)
      AND (OLD.deleted_at IS DISTINCT FROM NEW.deleted_at
        OR (OLD.entry_date, OLD.date_end, OLD.driver_id, OLD.route, OLD.rt_id, OLD.entry_type, OLD.local_move_id)
           IS DISTINCT FROM (NEW.entry_date, NEW.date_end, NEW.driver_id, NEW.route, NEW.rt_id, NEW.entry_type, NEW.local_move_id)))
    EXECUTE FUNCTION public.dl_local_line_guard();

  -- 4. PROOFS inside the block: any failure rolls back everything above.
  -- the guard = rule 1 + 060's rules character for character (from the live text, not retyped here)
  SELECT prosrc INTO new_src FROM pg_proc WHERE oid = 'public.dl_local_line_guard()'::regprocedure;
  old_rules := substring(old_src FROM position('    IF OLD.deleted_at IS NOT NULL AND NEW.deleted_at IS NULL THEN' IN old_src));
  IF position('    IF OLD.deleted_at IS NOT NULL' IN old_src) = 0 OR right(new_src, length(old_rules)) <> old_rules
     OR position('local_relay:line_locked' IN new_src) = 0 OR position('local_relay:line_locked' IN new_src) > position(old_rules IN new_src) THEN
    RAISE EXCEPTION '063 proof: dl_local_line_guard is not rule 1 + the 060 rules verbatim';
  END IF;
  -- the sync: body untouched, the flag added next to its search_path
  IF (SELECT md5(prosrc) FROM pg_proc WHERE oid = 'public.dl_local_day_sync(bigint,date)'::regprocedure) <> '297954261e9e8fe2936f6217f31f1e7a'
     OR NOT EXISTS (SELECT 1 FROM pg_proc WHERE oid = 'public.dl_local_day_sync(bigint,date)'::regprocedure AND prosecdef
                     AND proconfig @> ARRAY['search_path=public', 'tms.local_day_sync=on'] AND cardinality(proconfig) = 2) THEN
    RAISE EXCEPTION '063 proof: dl_local_day_sync is not the 060 body with search_path + tms.local_day_sync';
  END IF;
  -- the trigger: ONE, enabled, row BEFORE UPDATE, the guard, exactly the eight columns
  SELECT count(*) INTO n FROM pg_trigger t
   WHERE t.tgrelid = 'public.dl_entries'::regclass AND t.tgname = 'dl_local_line_guard' AND NOT t.tgisinternal
     AND t.tgenabled = 'O' AND t.tgtype = 19 AND t.tgfoid = 'public.dl_local_line_guard()'::regprocedure
     AND (SELECT array_agg(a.attname::text ORDER BY a.attname) FROM unnest(t.tgattr::int2[]) k JOIN pg_attribute a
           ON a.attrelid = t.tgrelid AND a.attnum = k)
         = ARRAY['date_end', 'deleted_at', 'driver_id', 'entry_date', 'entry_type', 'local_move_id', 'route', 'rt_id'];
  IF n <> 1 THEN RAISE EXCEPTION '063 proof: trigger dl_local_line_guard is not on the eight columns'; END IF;
  -- born closed (060 section 7): CREATE OR REPLACE keeps the revoked ACL - prove it
  IF has_function_privilege('anon', 'public.dl_local_line_guard()', 'EXECUTE')
     OR has_function_privilege('authenticated', 'public.dl_local_line_guard()', 'EXECUTE')
     OR has_function_privilege('service_role', 'public.dl_local_line_guard()', 'EXECUTE')
     OR has_function_privilege('anon', 'public.dl_local_day_sync(bigint,date)', 'EXECUTE')
     OR has_function_privilege('authenticated', 'public.dl_local_day_sync(bigint,date)', 'EXECUTE')
     OR has_function_privilege('service_role', 'public.dl_local_day_sync(bigint,date)', 'EXECUTE') THEN
    RAISE EXCEPTION '063 proof: dl_local_line_guard or dl_local_day_sync is executable by anon/authenticated/service_role';
  END IF;
  -- B-54: the same number of triggers, and B-54 still equals it (not touched by this block)
  SELECT count(*) INTO trg_after FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  IF trg_after <> trg_before OR NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-54' AND red_value = trg_after) THEN
    RAISE EXCEPTION '063 proof: trigger count % -> % (expected unchanged), or B-54 moved', trg_before, trg_after;
  END IF;
  -- nothing else moved: no payroll line, no relay written by this block
  IF (SELECT count(*) FROM public.dl_entries WHERE deleted_at IS NULL) <> dl_live_before
     OR (SELECT count(*) FROM public.dl_entries WHERE local_move_id IS NOT NULL) <> dl_local_before
     OR (SELECT count(*) FROM public.local_moves) <> lm_before THEN
    RAISE EXCEPTION '063 proof: payroll lines or local moves changed';
  END IF;
  -- B-54 runs the way run_checks (047) runs it: guard, 10 s timeout, as tms_check_runner. The text
  -- is read before the role switch (tms_check_runner cannot read schema monitoring).
  FOR r IN SELECT id, sql_text FROM monitoring.checks WHERE id = 'B-54' AND enabled LOOP
    PERFORM monitoring.check_sql_guard(r.sql_text);
    PERFORM set_config('statement_timeout', '10000', true);
    SET LOCAL ROLE tms_check_runner;
    EXECUTE r.sql_text INTO v;
    RESET ROLE;
    IF v IS DISTINCT FROM trg_after::numeric THEN
      RAISE EXCEPTION '063 proof: B-54 = % right after the migration (expected %)', v, trg_after;
    END IF;
  END LOOP;

  RAISE NOTICE '063 OK: local line guard on 8 columns; triggers % -> %, B-54 = %', trg_before, trg_after, trg_after;
END;
  -- ===== end of 063 =====

  -- A: what 063 changes is there (its own proofs already raised if not; this names it in the result)
  BEGIN
    SELECT cardinality(tgattr::int2[]) INTO dry_n FROM pg_trigger
     WHERE tgrelid = 'public.dl_entries'::regclass AND tgname = 'dl_local_line_guard';
    IF dry_n = 8
       AND EXISTS (SELECT 1 FROM pg_proc p, unnest(p.proconfig) c
                    WHERE p.oid = 'public.dl_local_day_sync(bigint,date)'::regprocedure AND c = 'tms.local_day_sync=on')
       AND position('local_relay:line_locked' IN (SELECT prosrc FROM pg_proc WHERE oid = 'public.dl_local_line_guard()'::regprocedure)) > 0 THEN
      ok := ok + 1; res := res || 'A ok trigger on 8 columns, sync flag, guard rule line_locked in place'::text;
    ELSE bad := bad + 1; res := res || format('A FAIL trigger columns %s/8 or flag/rule missing', dry_n); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('A ERROR ' || SQLERRM);
  END;

  -- B: the trigger was dropped and created under the same name: the count and B-54 did not move
  BEGIN
    SELECT count(*) INTO dry_n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
      JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
    IF dry_n = dry_trg_before AND (SELECT red_value FROM monitoring.checks WHERE id = 'B-54') = dry_n AND dry_b54_before = dry_trg_before THEN
      ok := ok + 1; res := res || format('B ok triggers %s = %s, B-54 %s', dry_trg_before, dry_n, dry_b54_before);
    ELSE bad := bad + 1; res := res || format('B FAIL triggers %s -> %s, B-54 %s -> %s', dry_trg_before, dry_n, dry_b54_before,
                                             (SELECT red_value FROM monitoring.checks WHERE id = 'B-54')); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('B ERROR ' || SQLERRM);
  END;

  -- C: data 063 must not touch - same fingerprint after the block as before it. A save by someone
  --    else during these seconds also changes it (fails closed): the FAIL text says what to do.
  BEGIN
    IF (SELECT md5(
    coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.dl_entries x), '')
 || coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.local_moves x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) = dry_fp_before THEN
      ok := ok + 1; res := res || 'C ok payroll lines, local moves, auditor rows, sequences unchanged'::text;
    ELSE bad := bad + 1; res := res || 'C FAIL data changed during the dry run - 063 itself, or a save by someone else in those seconds: if A and B are ok, wait 5 minutes and run the dry run once more; if C fails again, stop and copy the panel to the coordinator'::text; END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('C ERROR ' || SQLERRM);
  END;

  RAISE EXCEPTION 'DRY RUN 063 finished - EVERYTHING UNDONE, nothing kept. Result: % OK, % FAIL  ||  %', ok, bad, array_to_string(res, '  |  ');
END
$dry$;
