-- 065 DRY RUN - GENERATED by worker/migrations/drafts/tools/build-065-dryrun.mjs from 065_temp_per_cmr.sql.
-- DO NOT EDIT BY HAND: edit 065 and regenerate (tms-auditor/test/dryrun-065.test.mjs fails on any drift).
--
-- WHAT: 065's own DO block, statement for statement (every guard, change and proof, B-54 run as
--   tms_check_runner), wrapped in ONE outer DO block that first fingerprints data 065 must not touch, then
--   checks the result, and ENDS WITH A DELIBERATE ERROR. The error rolls the whole block back: NOTHING it did
--   is kept (no column, no view change, the leg sync of 020 as it was).
-- WHEN: the same evening, AFTER 15:00 (the team works 05:30-14:30), BEFORE 065_temp_per_cmr.sql. It takes the
--   same locks as 065 (lock_timeout 5 s, then it gives up - run it again a little later).
-- WHY ONE DO BLOCK: the Supabase SQL editor is NOT atomic across statements (lesson 056), but ONE DO block is
--   ONE statement: its final error undoes everything inside it.
-- EXPECTED (the red ERROR is deliberate):
--   ERROR: P0001: DRY RUN 065 finished - EVERYTHING UNDONE, nothing kept. Result: 4 OK, 0 FAIL  ||  A ok ... | B ok triggers 35 = 35, B-54 35 | C ok ... | D ok ...
--   Anything with FAIL or ERROR in it: do NOT run 065, copy the panel to the coordinator.
--   ONE exception: "3 OK, 1 FAIL" where the FAIL is C alone (A, B and D ok). C fingerprints every order, every
--   row of orders_with_derived, the auditor rows and every public sequence while the block runs, so ONE save
--   by someone else in those seconds turns it red - it fails closed, nothing was kept. Wait 5 minutes and run
--   the dry run once more; if C fails again, copy the panel to the coordinator.
--   A different message altogether ("065: ...", "065 proof: ...", a lock timeout) is the guard or proof of 065
--   that stopped - exactly what 065 itself would have said. Do NOT run 065.
-- AFTER: 065_temp_per_cmr_verify.sql V0 again - nothing was kept: orders has no temp_per_cmr and
--   orders_with_derived is still the 057 text (md5 4f82b738847c4770ccc379b1d558d542, 137 columns), and
--   order_parent_to_legs and its trigger still 020's (md5 b1f552325162375855244a4161685fdc / a0ce809945f493872557b6e1a08001a3).
-- Scenarios: A 065's column and view exist inside the block (view md5 = the one measured after 065);
--   B the trigger count did not move and B-54 equals it (35); C data 065 must not touch is unchanged (every
--   order and every orders_with_derived row without the new key, every auditor row, every public sequence);
--   D the leg sync of 020 now carries the flag (order_parent_to_legs and its trigger md5 = the ones measured
--   after 065). D reads the catalog only: it does not save a parent to watch its legs - on production that
--   would fire every order trigger and advance sequences that the rollback cannot give back; the PGlite
--   harness proves the behaviour, D proves production got the same text.

DO $dry$
DECLARE
  ok int := 0; bad int := 0; res text[] := '{}';
  dry_fp_before text; dry_b54_before numeric; dry_trg_before int; dry_n int;
BEGIN
  -- the B-54 value and the trigger count 065 will meet, and the data it must leave alone
  SELECT red_value INTO dry_b54_before FROM monitoring.checks WHERE id = 'B-54';
  SELECT count(*) INTO dry_trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  SELECT (SELECT md5(
    coalesce((SELECT string_agg((to_jsonb(x) - 'temp_per_cmr')::text, ',' ORDER BY x.id) FROM public.orders x), '')
 || coalesce((SELECT string_agg((to_jsonb(x) - 'temp_per_cmr')::text, ',' ORDER BY x.id) FROM public.orders_with_derived x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) INTO dry_fp_before;

  -- ===== 065_temp_per_cmr.sql, its DO block verbatim (a nested block: its errors stop everything) =====
DECLARE
  n bigint; k bigint;
  trg_before int; trg_after int; b54_before numeric; b54_baseline numeric;
  orders_before bigint; owd_rows_before bigint; view_cols int;
  old_view text; new_view text;
  view_acl text; view_owner oid; view_opts text[];
  -- The ONE change to the view text: the last select item gets a comma and the flag follows it.
  -- Both strings are the deparsed form (pg_get_viewdef), so the proof below compares like with like.
  anchor_old text := E' AS stock_lot_reference\n   FROM ';
  anchor_new text := E' AS stock_lot_reference,\n    o.temp_per_cmr\n   FROM ';
  -- The leg sync of 020 (step 3). The function gets the flag next to temperature_c in BOTH places
  -- temperature_c is copied: the SET list and the "only real changes" test of the same UPDATE. The
  -- trigger gets it right after temperature_c in its UPDATE OF list. Same strings in the rollback.
  fn_set_old text := 'temperature_c = new.temperature_c,';
  fn_set_new text := 'temperature_c = new.temperature_c, temp_per_cmr = new.temp_per_cmr,';
  fn_dif_old text := 'temperature_c is distinct from new.temperature_c or ';
  fn_dif_new text := 'temperature_c is distinct from new.temperature_c or temp_per_cmr is distinct from new.temp_per_cmr or ';
  trg_col_old text := 'temperature_c, pallet_type,';
  trg_col_new text := 'temperature_c, temp_per_cmr, pallet_type,';
  fn_oid oid; old_fn text; new_fn text; fn_attrs text;
  trg_oid oid; old_trg text; new_trg text; trg_comment text;
  r record; v numeric;
BEGIN
  -- pg_get_viewdef prints names relative to the search_path (md5 guard below): pin it.
  PERFORM set_config('search_path', 'public, extensions', true);
  -- ALTER TABLE orders and CREATE OR REPLACE VIEW take ACCESS EXCLUSIVE locks: behind an idle open
  -- transaction they would wait forever while every ORDERS read of the app queues behind them. Give
  -- up after 5 s instead - the whole block rolls back; run it again a little later (as 057/060/063).
  PERFORM set_config('lock_timeout', '5s', true);

  -- 0. GUARDS (SELECT only): the base is what 057 + 060 + 063 left on 5-6/10.
  IF to_regclass('monitoring.checks') IS NULL THEN
    RAISE EXCEPTION '065: monitoring.checks does not exist (047 must run first)';
  END IF;
  IF to_regclass('public.orders_with_derived') IS NULL
     OR (SELECT relkind FROM pg_class WHERE oid = 'public.orders_with_derived'::regclass) <> 'v' THEN
    RAISE EXCEPTION '065: public.orders_with_derived is not a plain view - stop';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_attribute
              WHERE attrelid IN ('public.orders'::regclass, 'public.orders_with_derived'::regclass)
                AND attname = 'temp_per_cmr' AND attnum > 0 AND NOT attisdropped) THEN
    RAISE EXCEPTION '065: already applied (orders or orders_with_derived has temp_per_cmr)';
  END IF;
  -- The view is re-created from its live text: refuse if it is not the text 057 left.
  old_view := pg_get_viewdef('public.orders_with_derived'::regclass);
  IF md5(old_view) <> '4f82b738847c4770ccc379b1d558d542' THEN
    RAISE EXCEPTION '065: orders_with_derived is not the text 057 left on 5/10 (md5 %) - someone changed the view, re-measure', md5(old_view);
  END IF;
  SELECT count(*) INTO view_cols FROM pg_attribute
   WHERE attrelid = 'public.orders_with_derived'::regclass AND attnum > 0 AND NOT attisdropped;
  IF view_cols <> 137 THEN
    RAISE EXCEPTION '065: orders_with_derived has % columns, expected 137 (057) - re-measure', view_cols;
  END IF;
  IF (length(old_view) - length(replace(old_view, anchor_old, ''))) <> length(anchor_old) THEN
    RAISE EXCEPTION '065: the end of the select list of orders_with_derived is not where it was measured';
  END IF;
  SELECT relacl::text, relowner, reloptions INTO view_acl, view_owner, view_opts
    FROM pg_class WHERE oid = 'public.orders_with_derived'::regclass;
  IF view_opts IS NOT NULL THEN
    RAISE EXCEPTION '065: orders_with_derived has view options (%) - CREATE OR REPLACE would drop them; the owner decides',
      array_to_string(view_opts, ', ');
  END IF;
  -- B-54 counts enabled non-internal triggers in public; run_checks compares against
  -- coalesce(baseline, red_value), so a baseline would hide a change. 35 = 057 + 060 + 063 (6/10).
  SELECT count(*) INTO trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  SELECT red_value, baseline INTO b54_before, b54_baseline FROM monitoring.checks WHERE id = 'B-54';
  IF trg_before <> 35 OR b54_before IS DISTINCT FROM 35 OR b54_baseline IS NOT NULL THEN
    RAISE EXCEPTION '065: expected 35 enabled triggers in public = B-54 red_value, no baseline (057 + 060 + 063), found % triggers, B-54 red_value % baseline % - something changed triggers or B-54 since 6/10, re-measure',
      trg_before, b54_before, b54_baseline;
  END IF;
  -- The leg sync is re-created from its live text: refuse unless it is exactly what 020 left (the md5s
  -- were read on production 4/10). A hand fix since then would be silently overwritten otherwise.
  fn_oid := to_regprocedure('public.order_parent_to_legs()');
  IF fn_oid IS NULL THEN
    RAISE EXCEPTION '065: function public.order_parent_to_legs() does not exist (020) - stop';
  END IF;
  old_fn := pg_get_functiondef(fn_oid);
  IF md5(old_fn) <> 'b1f552325162375855244a4161685fdc' THEN
    RAISE EXCEPTION '065: order_parent_to_legs is not the text 020 left (md5 %) - someone changed the leg sync, re-measure', md5(old_fn);
  END IF;
  IF (length(old_fn) - length(replace(old_fn, fn_set_old, ''))) <> length(fn_set_old)
     OR (length(old_fn) - length(replace(old_fn, fn_dif_old, ''))) <> length(fn_dif_old) THEN
    RAISE EXCEPTION '065: the temperature_c copy in order_parent_to_legs is not where it was measured';
  END IF;
  -- every attribute CREATE OR REPLACE could move: proven identical after (oid, owner, grants, SECURITY
  -- DEFINER, search_path, language, volatility, strictness, cost, return and argument types)
  SELECT concat_ws('|', oid, proowner, proacl::text, prosecdef, proconfig::text, prolang, provolatile, proisstrict,
                   proleakproof, proparallel, procost, prorows, prorettype, proargtypes::text, prokind)
    INTO fn_attrs FROM pg_proc WHERE oid = fn_oid;
  IF (SELECT count(*) FROM pg_trigger WHERE tgrelid = 'public.orders'::regclass AND tgname = 'order_parent_to_legs' AND NOT tgisinternal) <> 1 THEN
    RAISE EXCEPTION '065: trigger order_parent_to_legs on orders is missing (020) - stop';
  END IF;
  SELECT oid, pg_get_triggerdef(oid), obj_description(oid, 'pg_trigger') INTO trg_oid, old_trg, trg_comment
    FROM pg_trigger WHERE tgrelid = 'public.orders'::regclass AND tgname = 'order_parent_to_legs' AND NOT tgisinternal;
  IF md5(old_trg) <> 'a0ce809945f493872557b6e1a08001a3'
     OR (SELECT tgenabled FROM pg_trigger WHERE oid = trg_oid) <> 'O'
     OR (SELECT tgfoid FROM pg_trigger WHERE oid = trg_oid) <> fn_oid THEN
    RAISE EXCEPTION '065: trigger order_parent_to_legs is not the one 020 left, enabled, calling order_parent_to_legs() (md5 %) - re-measure', md5(old_trg);
  END IF;
  IF (length(old_trg) - length(replace(old_trg, trg_col_old, ''))) <> length(trg_col_old) THEN
    RAISE EXCEPTION '065: temperature_c in the UPDATE OF list of trigger order_parent_to_legs is not where it was measured';
  END IF;
  SELECT count(*) INTO orders_before FROM public.orders;
  SELECT count(*) INTO owd_rows_before FROM public.orders_with_derived;

  -- 1. THE FACT, on the table (principle 4: every path - facade, SQL editor, future code - meets it).
  ALTER TABLE public.orders ADD COLUMN temp_per_cmr boolean NOT NULL DEFAULT false;
  COMMENT ON COLUMN public.orders.temp_per_cmr IS
    'true = the temperature of this order is the one written on the CMR; Temperature C may then be empty (owner 7/10/2026, migration 065). Facade label: Temp Per CMR.';

  -- 2. THE READ VIEW: the live text + the one line. The Worker reads every ORDERS record from here;
  --    without the column a read asking for "Temp Per CMR" would fail (PostgREST: no such column).
  EXECUTE 'CREATE OR REPLACE VIEW public.orders_with_derived AS ' || replace(old_view, anchor_old, anchor_new);

  -- 3. THE LEG SYNC (020): a parent's flag reaches its legs as its temperature_c does. The column
  --    exists by now (step 1), so the trigger can name it. pg_get_functiondef prints a complete
  --    CREATE OR REPLACE FUNCTION with the live attributes, so only the body changes. The trigger is
  --    dropped and created again in this same transaction: no other session ever sees orders without it.
  new_fn := replace(replace(old_fn, fn_set_old, fn_set_new), fn_dif_old, fn_dif_new);
  EXECUTE new_fn;
  new_trg := replace(old_trg, trg_col_old, trg_col_new);
  DROP TRIGGER order_parent_to_legs ON public.orders;
  EXECUTE new_trg;
  IF trg_comment IS NOT NULL THEN
    EXECUTE format('COMMENT ON TRIGGER order_parent_to_legs ON public.orders IS %L', trg_comment);
  END IF;

  -- 4. PROOFS inside the block: any failure rolls back everything above.
  IF NOT EXISTS (SELECT 1 FROM pg_attribute a JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
                  WHERE a.attrelid = 'public.orders'::regclass AND a.attname = 'temp_per_cmr' AND NOT a.attisdropped
                    AND a.atttypid = 'boolean'::regtype AND a.attnotnull AND pg_get_expr(d.adbin, d.adrelid) = 'false') THEN
    RAISE EXCEPTION '065 proof: orders.temp_per_cmr is not boolean NOT NULL DEFAULT false';
  END IF;
  SELECT count(*), count(*) FILTER (WHERE temp_per_cmr) INTO k, n FROM public.orders;
  IF k <> orders_before OR n <> 0 THEN
    RAISE EXCEPTION '065 proof: orders % -> %, % marked (expected none)', orders_before, k, n;
  END IF;
  -- the view: the new text IS the old text + the one line (nothing else moved), 138 columns, the
  -- last one the boolean flag, same owner, grants and (no) options, same rows, the table's value
  new_view := pg_get_viewdef('public.orders_with_derived'::regclass);
  IF new_view IS DISTINCT FROM replace(old_view, anchor_old, anchor_new) THEN
    RAISE EXCEPTION '065 proof: orders_with_derived is not the 057 text + o.temp_per_cmr';
  END IF;
  IF (SELECT count(*) FROM pg_attribute WHERE attrelid = 'public.orders_with_derived'::regclass
       AND attnum > 0 AND NOT attisdropped) <> view_cols + 1
     OR NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.orders_with_derived'::regclass
                     AND attnum = view_cols + 1 AND attname = 'temp_per_cmr' AND atttypid = 'boolean'::regtype) THEN
    RAISE EXCEPTION '065 proof: orders_with_derived does not end with temp_per_cmr (boolean) as column %', view_cols + 1;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_class WHERE oid = 'public.orders_with_derived'::regclass
                  AND relacl::text IS NOT DISTINCT FROM view_acl AND relowner = view_owner AND reloptions IS NULL) THEN
    RAISE EXCEPTION '065 proof: orders_with_derived owner, grants or options changed';
  END IF;
  IF (SELECT count(*) FROM public.orders_with_derived) <> owd_rows_before
     OR EXISTS (SELECT 1 FROM public.orders_with_derived d JOIN public.orders o ON o.id = d.id
                 WHERE d.temp_per_cmr IS DISTINCT FROM o.temp_per_cmr) THEN
    RAISE EXCEPTION '065 proof: orders_with_derived rows changed or the flag does not read the table';
  END IF;
  -- The Worker's path (service_role through PostgREST): it reads the flag from the view and writes
  -- it on the table. A missing privilege here would be a 500 on every save after the Worker deploy.
  IF NOT has_column_privilege('service_role', 'public.orders_with_derived', 'temp_per_cmr', 'SELECT')
     OR NOT has_column_privilege('service_role', 'public.orders', 'temp_per_cmr', 'INSERT')
     OR NOT has_column_privilege('service_role', 'public.orders', 'temp_per_cmr', 'UPDATE') THEN
    RAISE EXCEPTION '065 proof: service_role (the Worker) cannot read the flag from orders_with_derived or write it on orders';
  END IF;
  -- the leg sync: the SAME function (oid) whose text is the 020 text + the two pieces, character for
  -- character, with every attribute as before (owner, grants, SECURITY DEFINER, search_path ...)
  IF to_regprocedure('public.order_parent_to_legs()') IS DISTINCT FROM fn_oid
     OR pg_get_functiondef(fn_oid) IS DISTINCT FROM new_fn THEN
    RAISE EXCEPTION '065 proof: order_parent_to_legs is not the 020 text + the temp_per_cmr copy';
  END IF;
  IF (SELECT concat_ws('|', oid, proowner, proacl::text, prosecdef, proconfig::text, prolang, provolatile, proisstrict,
                       proleakproof, proparallel, procost, prorows, prorettype, proargtypes::text, prokind)
        FROM pg_proc WHERE oid = fn_oid) IS DISTINCT FROM fn_attrs THEN
    RAISE EXCEPTION '065 proof: order_parent_to_legs owner, grants, SECURITY DEFINER, search_path or another attribute changed';
  END IF;
  -- ... and ONE trigger of that name: the 020 text + temp_per_cmr in its UPDATE OF list, enabled,
  -- calling the same function, the same comment
  IF (SELECT count(*) FROM pg_trigger WHERE tgrelid = 'public.orders'::regclass AND tgname = 'order_parent_to_legs' AND NOT tgisinternal) <> 1
     OR NOT EXISTS (SELECT 1 FROM pg_trigger t
                     WHERE t.tgrelid = 'public.orders'::regclass AND t.tgname = 'order_parent_to_legs' AND NOT t.tgisinternal
                       AND pg_get_triggerdef(t.oid) = new_trg AND t.tgenabled = 'O' AND t.tgfoid = fn_oid
                       AND obj_description(t.oid, 'pg_trigger') IS NOT DISTINCT FROM trg_comment) THEN
    RAISE EXCEPTION '065 proof: trigger order_parent_to_legs is not the 020 trigger + temp_per_cmr in its UPDATE OF list';
  END IF;
  -- B-54: the same number of triggers (35: the leg-sync trigger was re-created under its own name, not
  -- added), and B-54 still equals it (not touched by this block)
  SELECT count(*) INTO trg_after FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  IF trg_after <> 35 OR trg_after <> trg_before OR NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-54' AND red_value = trg_after) THEN
    RAISE EXCEPTION '065 proof: trigger count % -> % (expected 35, unchanged), or B-54 moved', trg_before, trg_after;
  END IF;
  -- B-54 runs the way run_checks (047) runs it: guard, 10 s timeout, as tms_check_runner. The text
  -- is read before the role switch (tms_check_runner cannot read schema monitoring).
  FOR r IN SELECT id, sql_text FROM monitoring.checks WHERE id = 'B-54' AND enabled LOOP
    PERFORM monitoring.check_sql_guard(r.sql_text);
    PERFORM set_config('statement_timeout', '10000', true);
    SET LOCAL ROLE tms_check_runner;
    EXECUTE r.sql_text INTO v;
    RESET ROLE;
    IF v IS DISTINCT FROM trg_after::numeric THEN
      RAISE EXCEPTION '065 proof: B-54 = % right after the migration (expected %)', v, trg_after;
    END IF;
  END LOOP;

  RAISE NOTICE '065 OK: orders.temp_per_cmr in place (% orders, 0 marked); orders_with_derived % -> % columns, same owner/grants/options; order_parent_to_legs copies the flag to split legs (same owner/grants/SECURITY DEFINER/search_path), its trigger watches it; triggers % -> %, B-54 = %',
    k, view_cols, view_cols + 1, trg_before, trg_after, trg_after;
END;
  -- ===== end of 065 =====

  -- A: what 065 adds is there (its own proofs already raised if not; this names it in the result). 065 pinned
  --    search_path to "public, extensions" for this transaction, so the md5 is the one measured after 065.
  BEGIN
    SELECT count(*) INTO dry_n FROM public.orders WHERE temp_per_cmr;
    IF dry_n = 0
       AND (SELECT attname FROM pg_attribute WHERE attrelid = 'public.orders_with_derived'::regclass AND attnum = 138 AND NOT attisdropped) = 'temp_per_cmr'
       AND md5(pg_get_viewdef('public.orders_with_derived'::regclass)) = '55736818891a8f4e06193b23265cacf4' THEN
      ok := ok + 1; res := res || 'A ok orders.temp_per_cmr (0 marked), orders_with_derived 138 columns ending with it, view md5 as measured'::text;
    ELSE bad := bad + 1; res := res || format('A FAIL marked %s, column 138 %s, view md5 %s', dry_n,
           (SELECT attname FROM pg_attribute WHERE attrelid = 'public.orders_with_derived'::regclass AND attnum = 138),
           md5(pg_get_viewdef('public.orders_with_derived'::regclass))); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('A ERROR ' || SQLERRM);
  END;

  -- B: a column adds no trigger: the count and B-54 did not move
  BEGIN
    SELECT count(*) INTO dry_n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
      JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
    IF dry_n = dry_trg_before AND (SELECT red_value FROM monitoring.checks WHERE id = 'B-54') = dry_n AND dry_b54_before = dry_trg_before THEN
      ok := ok + 1; res := res || format('B ok triggers %s = %s, B-54 %s', dry_trg_before, dry_n, dry_b54_before);
    ELSE bad := bad + 1; res := res || format('B FAIL triggers %s -> %s, B-54 %s -> %s', dry_trg_before, dry_n, dry_b54_before,
                                             (SELECT red_value FROM monitoring.checks WHERE id = 'B-54')); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('B ERROR ' || SQLERRM);
  END;

  -- C: data 065 must not touch - same fingerprint after the block as before it. A save by someone else
  --    during these seconds also changes it (fails closed): the FAIL text says what to do.
  BEGIN
    IF (SELECT md5(
    coalesce((SELECT string_agg((to_jsonb(x) - 'temp_per_cmr')::text, ',' ORDER BY x.id) FROM public.orders x), '')
 || coalesce((SELECT string_agg((to_jsonb(x) - 'temp_per_cmr')::text, ',' ORDER BY x.id) FROM public.orders_with_derived x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) = dry_fp_before THEN
      ok := ok + 1; res := res || 'C ok orders, orders_with_derived rows, auditor rows, sequences unchanged'::text;
    ELSE bad := bad + 1; res := res || 'C FAIL data changed during the dry run - 065 itself, or a save by someone else in those seconds: if A and B are ok, wait 5 minutes and run the dry run once more; if C fails again, stop and copy the panel to the coordinator'::text; END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('C ERROR ' || SQLERRM);
  END;

  -- D: the leg sync (065 step 3) - the same texts the harness proved copy the flag to split legs
  BEGIN
    IF md5(pg_get_functiondef('public.order_parent_to_legs()'::regprocedure)) = '7ffe6ccd14b19f5c2b22934520ed6c9b'
       AND (SELECT md5(pg_get_triggerdef(oid)) FROM pg_trigger WHERE tgrelid = 'public.orders'::regclass
             AND tgname = 'order_parent_to_legs' AND NOT tgisinternal AND tgenabled = 'O') = 'cb0735f6fa07cba7d340ab9f3a3ace4c' THEN
      ok := ok + 1; res := res || 'D ok order_parent_to_legs copies temp_per_cmr to split legs, its trigger watches it (md5s as measured)'::text;
    ELSE bad := bad + 1; res := res || format('D FAIL order_parent_to_legs md5 %s, trigger md5 %s',
           md5(pg_get_functiondef('public.order_parent_to_legs()'::regprocedure)),
           (SELECT md5(pg_get_triggerdef(oid)) FROM pg_trigger WHERE tgrelid = 'public.orders'::regclass AND tgname = 'order_parent_to_legs')); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('D ERROR ' || SQLERRM);
  END;

  RAISE EXCEPTION 'DRY RUN 065 finished - EVERYTHING UNDONE, nothing kept. Result: % OK, % FAIL  ||  %', ok, bad, array_to_string(res, '  |  ');
END
$dry$;
