-- 066 DRY RUN - GENERATED by worker/migrations/drafts/tools/build-066-dryrun.mjs from 066_rt_group_base_join.sql.
-- DO NOT EDIT BY HAND: edit 066 and regenerate (tms-auditor/test/dryrun-066.test.mjs fails on any drift).
--
-- WHAT: 066's own DO block, statement for statement (every guard, change and proof, B-54 and B-77 run as
--   tms_check_runner), wrapped in ONE outer DO block that first fingerprints data 066 must not touch, then
--   checks the result, and ENDS WITH A DELIBERATE ERROR. The error rolls the whole block back: NOTHING it did
--   is kept (no function text, no B-77 row).
-- WHEN: the same evening, AFTER 15:00 (the team works 05:30-14:30), BEFORE 066_rt_group_base_join.sql. It
--   uses the same lock_timeout as 066 (5 s, then it gives up - run it again a little later).
-- WHY ONE DO BLOCK: the Supabase SQL editor is NOT atomic across statements (lesson 056), but ONE DO
--   block is ONE statement: its final error undoes everything inside it.
-- EXPECTED (the red ERROR is deliberate):
--   ERROR: P0001: DRY RUN 066 finished - EVERYTHING UNDONE, nothing kept. Result: 4 OK, 0 FAIL  ||  A ok ... | B ok triggers T = T, B-54 T | C ok ... | D ok B-77 = catalog, value 0 (ids )
--   (T = the live trigger count = B-54: 35 since 057 + 060 + 063.) D's value is B-77 on production - 0
--   after the 7/10 repair; another value is not a FAIL of the dry run (it measures data, not 066): copy it.
--   Anything with FAIL or ERROR in it: do NOT run 066, copy the panel to the coordinator.
--   ONE exception: "3 OK, 1 FAIL" where the FAIL is C alone (A, B, D ok). C fingerprints the orders, round
--   trips, legs, the auditor rows and every public sequence while the block runs, so ONE save by someone else
--   in those seconds turns it red - it fails closed, nothing was kept. Wait 5 minutes and run the dry run once
--   more; if C fails again, copy the panel to the coordinator.
--   A different message altogether ("066: ...", "066 proof: ...", a lock timeout) is the guard or proof of
--   066 that stopped - exactly what 066 itself would have said. Do NOT run 066.
-- AFTER: SELECT that nothing was kept - md5(pg_get_functiondef('public.rt_create_from_order()'::regprocedure))
--   is still 3f3a01204f7f4a4b6546e965fc231ae3, rt_link_split still 6189950c70b289fd5075afd17e28ecec, no B-77 row.
-- Scenarios: A 066's changes exist inside the block; B the trigger count did not move and B-54 equals it;
--   C data 066 must not touch is unchanged (orders, round trips, legs, every auditor row but B-77, every public
--   sequence's last_value); D B-77 is the catalog row and runs as tms_check_runner (its value reported).

DO $dry$
DECLARE
  ok int := 0; bad int := 0; res text[] := '{}';
  dry_fp_before text; dry_b54_before int; dry_trg_before int; dry_n int; dry_v numeric; dry_ids text[]; dry_sql text; dry_ids_sql text;
BEGIN
  -- the B-54 value and the trigger count 066 will meet, and the data it must leave alone
  SELECT red_value INTO dry_b54_before FROM monitoring.checks WHERE id = 'B-54';
  SELECT count(*) INTO dry_trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  SELECT (SELECT md5(
    coalesce((SELECT string_agg(md5(to_jsonb(x)::text), ',' ORDER BY x.id) FROM public.orders x), '')
 || coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.ct_round_trips x), '')
 || coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.ct_rt_legs x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks WHERE id <> 'B-77'), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) INTO dry_fp_before;

  -- ===== 066_rt_group_base_join.sql, its DO block verbatim (a nested block: its errors stop everything) =====
DECLARE
  -- THE ONE CHANGE, the same in both functions (the rollback swaps it back). Both strings are what
  -- pg_get_functiondef prints, so the proofs below compare like with like.
  cond_old text := $c$(cur.group_id is not null and n.group_id = cur.group_id)$c$;
  cond_new text := $c$(cur.group_id is not null and split_part(n.group_id,'|',1) = split_part(cur.group_id,'|',1))$c$;
  fn_create oid; fn_split oid;
  old_create text; old_split text; new_create text; new_split text;
  attrs_create text; attrs_split text; tg_before text; tg_after text;
  trg_before int; trg_after int;
  orders_before bigint; rts_before bigint; legs_before bigint; n int;
  r record; v numeric; ids text[]; b77 numeric; b77_ids text;
BEGIN
  -- pg_get_triggerdef prints names relative to the search_path (trigger proof below): pin it.
  PERFORM set_config('search_path', 'public, extensions', true);
  -- Neither CREATE OR REPLACE FUNCTION nor the INSERT is expected to wait on the app, but if one
  -- does (an idle open transaction), it must never queue the app behind it: give up after 5 s - the
  -- whole block rolls back; run it again a little later (as 057/060/063/065).
  PERFORM set_config('lock_timeout', '5s', true);

  -- 0. GUARDS (SELECT only): the two walks are the texts read on production 7/10; 066 not yet.
  IF to_regclass('monitoring.checks') IS NULL THEN
    RAISE EXCEPTION '066: monitoring.checks does not exist (047 must run first)';
  END IF;
  fn_create := to_regprocedure('public.rt_create_from_order()');
  fn_split  := to_regprocedure('public.rt_link_split()');
  IF fn_create IS NULL OR fn_split IS NULL THEN
    RAISE EXCEPTION '066: public.rt_create_from_order() or public.rt_link_split() does not exist (033 / 037) - stop';
  END IF;
  old_create := pg_get_functiondef(fn_create);
  old_split  := pg_get_functiondef(fn_split);
  IF md5(old_create) = '8e964f66556677a284eca13db70665c6' OR md5(old_split) = 'd8a4a03dca0e8e26d4e8d227f1287590'
     OR EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-77') THEN
    RAISE EXCEPTION '066: already applied (a walk already compares the base Group ID, or check B-77 exists)';
  END IF;
  -- Re-created from the live text: refuse unless it is exactly what was measured. A hand fix since
  -- 7/10 would be overwritten silently otherwise, and the rollback could not give it back.
  IF md5(old_create) <> '3f3a01204f7f4a4b6546e965fc231ae3'
     OR (SELECT md5(prosrc) FROM pg_proc WHERE oid = fn_create) <> 'f71d333b33e1404817779c4033534b30' THEN
    RAISE EXCEPTION '066: rt_create_from_order is not the text read on production 7/10 (md5 %) - someone changed it, re-measure', md5(old_create);
  END IF;
  IF md5(old_split) <> '6189950c70b289fd5075afd17e28ecec'
     OR (SELECT md5(prosrc) FROM pg_proc WHERE oid = fn_split) <> '75da6f6f0389ba01ffd86074191eb4d7' THEN
    RAISE EXCEPTION '066: rt_link_split is not the text read on production 7/10 (md5 %) - someone changed it, re-measure', md5(old_split);
  END IF;
  -- the condition sits ONCE in each walk (else "one substitution" would not hold)
  IF (length(old_create) - length(replace(old_create, cond_old, ''))) <> length(cond_old)
     OR (length(old_split) - length(replace(old_split, cond_old, ''))) <> length(cond_old)
     OR position(cond_new IN old_create) > 0 OR position(cond_new IN old_split) > 0 THEN
    RAISE EXCEPTION '066: the group condition of a walk is not where it was measured (exactly once)';
  END IF;
  -- what must survive: SECURITY DEFINER with search_path=public (033/037), and every attribute
  -- CREATE OR REPLACE could move (oid, owner, grants, language, volatility, strictness, cost, ...)
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE oid = fn_create AND prosecdef AND proconfig = ARRAY['search_path=public'])
     OR NOT EXISTS (SELECT 1 FROM pg_proc WHERE oid = fn_split AND prosecdef AND proconfig = ARRAY['search_path=public']) THEN
    RAISE EXCEPTION '066: a walk is not SECURITY DEFINER with search_path=public as measured - re-measure';
  END IF;
  SELECT concat_ws('|', oid, proowner, proacl::text, prosecdef, proconfig::text, prolang, provolatile, proisstrict,
                   proleakproof, proparallel, procost, prorows, prorettype, proargtypes::text, prokind)
    INTO attrs_create FROM pg_proc WHERE oid = fn_create;
  SELECT concat_ws('|', oid, proowner, proacl::text, prosecdef, proconfig::text, prolang, provolatile, proisstrict,
                   proleakproof, proparallel, procost, prorows, prorettype, proargtypes::text, prokind)
    INTO attrs_split FROM pg_proc WHERE oid = fn_split;
  -- the two triggers that call them: both on orders, enabled; their texts are proven unchanged after
  IF (SELECT count(*) FROM pg_trigger WHERE tgrelid = 'public.orders'::regclass AND NOT tgisinternal AND tgenabled = 'O'
        AND ((tgname = 'rt_create_from_order' AND tgfoid = fn_create) OR (tgname = 'rt_link_split' AND tgfoid = fn_split))) <> 2 THEN
    RAISE EXCEPTION '066: triggers rt_create_from_order / rt_link_split on orders are not both there, enabled, calling these functions - stop';
  END IF;
  SELECT string_agg(t.tgname || ':' || t.tgrelid::regclass::text || ':' || t.tgenabled::text || ':' || t.tgfoid::text || ':' || md5(pg_get_triggerdef(t.oid)), ',' ORDER BY t.oid)
    INTO tg_before FROM pg_trigger t WHERE t.tgfoid IN (fn_create, fn_split) AND NOT t.tgisinternal;
  -- B-54 counts enabled non-internal triggers in public; run_checks compares against
  -- coalesce(baseline, red_value), so B-54 must be green before (and this block never writes it).
  SELECT count(*) INTO trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  IF NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-54' AND red_value = trg_before AND baseline IS NULL) THEN
    RAISE EXCEPTION '066: B-54 red_value is not the live trigger count % (or has a baseline) - a migration changed triggers without bumping it, re-measure', trg_before;
  END IF;
  SELECT count(*) INTO orders_before FROM public.orders;
  SELECT count(*) INTO rts_before FROM public.ct_round_trips;
  SELECT count(*) INTO legs_before FROM public.ct_rt_legs;

  -- 1. THE TWO WALKS: the live text, the one condition swapped. pg_get_functiondef prints a complete
  --    CREATE OR REPLACE FUNCTION with the live header, so only the body changes. No existing round
  --    trip, leg or order is touched: the new compare acts on the next write to an order.
  new_create := replace(old_create, cond_old, cond_new);
  new_split  := replace(old_split, cond_old, cond_new);
  EXECUTE new_create;
  EXECUTE new_split;

  -- 2. AUDITOR: B-77, text = tms-auditor/checks/B-77.sql (generated, base64 for Greek; md5-proven below).
  INSERT INTO monitoring.checks (id, title, flows, sql_text, ids_sql, entity_table, red_op, red_value, baseline, severity,
    schedule_tag, is_queue, impact, next_step, exceptions, tolerance, enabled, disabled_reason) VALUES
    ($m$B-77$m$,
     convert_from(decode('zqPPh861z4TOuc66zq3PgiDPgM6xz4HOsc6zzrPOtc67zq/Otc+CICjOv868zqzOtM6xL862zrXPjc6zzr/Pgi/Pgc+Mz4TOsSkgz4POtSA+MSDOts+Jzr3PhM6xzr3OrCDOtM+Bzr/OvM6/zrvPjM6zzrnOsQ==', 'base64'), 'UTF8'),
     ARRAY[$m$F-21$m$,$m$F-16$m$,$m$F-18$m$,$m$F-14$m$]::text[],
     $m$SELECT count(*) FROM orders a JOIN ct_rt_legs la ON la.order_id=a.id JOIN ct_round_trips ra ON ra.id=la.rt_id AND ra.status<>'cancelled'
 JOIN orders b ON b.id>a.id AND b.deleted_at IS NULL JOIN ct_rt_legs lb ON lb.order_id=b.id JOIN ct_round_trips rb ON rb.id=lb.rt_id AND rb.status<>'cancelled'
 WHERE a.deleted_at IS NULL AND rb.id<>ra.id
 AND ((a.group_id||'#'||b.group_id) ~ '^([^|#]*)(\|[^#]*)?#\1(\|[^#]*)?$'
  OR a.matched_import_id=b.legacy_id OR b.matched_import_id=a.legacy_id OR a.rotation_id=b.legacy_id OR b.rotation_id=a.legacy_id)$m$,
     $m$SELECT coalesce(array_agg(x ORDER BY x), '{}') FROM (SELECT DISTINCT coalesce(o.legacy_id, o.id::text) AS x FROM orders o JOIN (SELECT a.id AS a_id, b.id AS b_id FROM orders a
 JOIN ct_rt_legs la ON la.order_id=a.id JOIN ct_round_trips ra ON ra.id=la.rt_id AND ra.status<>'cancelled'
 JOIN orders b ON b.id>a.id AND b.deleted_at IS NULL JOIN ct_rt_legs lb ON lb.order_id=b.id JOIN ct_round_trips rb ON rb.id=lb.rt_id AND rb.status<>'cancelled'
 WHERE a.deleted_at IS NULL AND rb.id<>ra.id
 AND ((a.group_id||'#'||b.group_id) ~ '^([^|#]*)(\|[^#]*)?#\1(\|[^#]*)?$'
  OR a.matched_import_id=b.legacy_id OR b.matched_import_id=a.legacy_id OR a.rotation_id=b.legacy_id OR b.rotation_id=a.legacy_id)) p
 ON o.id IN (p.a_id, p.b_id) ORDER BY 1 LIMIT 50) s$m$,
     $m$orders$m$,
     $m$>$m$,
     0,
     NULL,
     $m$P2$m$,
     $m$hourly$m$,
     false,
     convert_from(decode('zojOvc6xIM+Gz4XPg865zrrPjCDOtM+Bzr/OvM6/zrvPjM6zzrnOvyAozr/OvM6szrTOsSwgzrbOtc+NzrPOv8+CIM61zr7Osc6zz4nOs86uz4IvzrXOuc+DzrHOs8+JzrPOrs+CIM6uIM+Bz4zPhM6xKSDOus6szrjOtc+EzrHOuSDPg861IM60z43OvyBSVDogzr8gV29ya2VyIM6xz4HOvc61zq/PhM6xzrkgzrrOrM64zrUgz4PPhc6zz4fPgc6/zr3Ouc+DzrzPjCDPhM63z4Igzr/OvM6szrTOsc+CICg0MDkpLCDOtyDPgc+Mz4TOsSDOtM61zr0gzrzPgM6xzq/Ovc61zrksIM66zrHOuSDOvM65z4POuM6/zrTOv8+Dzq/OsS/Orc6+zr/OtM6xIM+Ezr/PhSDOv860zrfOs86/z40gzrzOv865z4HOrM62zr/Ovc+EzrHOuSDPg861IM60z43OvyDOtM+Bzr/OvM6/zrvPjM6zzrnOsS4gzqDOtc+BzrnPg8+EzrHPhM65zrrPjCA3LzEwOiBHSS1NVVY3Rk5LRSwgIzQ1MSDPg8+Ezr8gUlQtMTIxNyDOus6xzrkgIzQ0OSDOvM+Mzr3OtyDPg8+Ezr8gUlQtMTIyMC4=', 'base64'), 'UTF8'),
     convert_from(decode('zpXOss60zr/OvM6xzrTOuc6xzq/OvyDOlM65zrXOuM69z47OvSDihpIgzr/OuSDPgM6xz4HOsc6zzrPOtc67zq/Otc+CIM+Ez4nOvSBpZHM6IM+Azr/Ouc6/IFJUIM61zq/Ovc6xzrkgz4TOvyDPg8+Jz4PPhM+MOyDOnM61z4TOsc+Gzr/Pgc6sIM+DzrrOrc67zr/Phc+CIM68zrUgz4TOuc+CIM61zr3PhM6/zrvOrc+CIM+Ezr/PhSBXb3JrZXIgKERFTEVURSBsZWcgKyBQT1NUIGF0dGFjaCksIM+Mz4DPic+CIM63IM61z4DOuc+DzrrOtc+Fzq4gz4TOt8+CIDcvMTAg4oCUIM68z4zOvc6/IM68zrUgwqvOvc6xzrnCuyDPhM6/z4Ugb3duZXIu', 'base64'), 'UTF8'),
     convert_from(decode('zpbOtc+NzrPOtyDPgM6xz4HOsc6zzrPOtc67zrnPjs69ICjOus6szrjOtSDOts61z43Os86/z4IgzrzOr86xIM+Gzr/Pgc6sKSDOvM61IM6RzpzOlc6jzpcgz4PPh86tz4POtywgz4zPgM+Jz4Igz4TOtyDOss67zq3PgM6/z4XOvSDOv865IHRyaWdnZXIgMDMzLzAzNyDOvM61z4TOrCDPhM6/IDA2Njogzq/OtM65zr8gzrLOsc+DzrnOus+MIEdyb3VwIElEICjPjCzPhM65IM61zq/Ovc6xzrkgz4DPgc65zr0gz4TOvyDCq3zCuyDigJQgz4TOvyBmcm9udCDOs8+BzqzPhs61zrkgz4TOtyDPg861zrnPgc6sIM+AzrHPgc6szrTOv8+DzrfPgiDCq3xyZWNBLHJlY0LCuyDOrc69zrEgzrzOrc67zr/PgiDPhM63IM+Gzr/Pgc6sKSwgbWF0Y2hlZF9pbXBvcnRfaWQgPSBsZWdhY3lfaWQgzq4gcm90YXRpb25faWQgPSBsZWdhY3lfaWQgKM66zrHOuSDOsc69zqzPgM6/zrTOsSkuIM6azrHOuSDOv865IM60z43OvyDOvM63IM60zrnOsc6zz4HOsc68zrzOrc69zrXPgiwgzrzOtSDPg866zq3Ou86/z4Igz4POtSDOts+Jzr3PhM6xzr3PjCBSVCAoc3RhdHVzIOKJoCBjYW5jZWxsZWQpLCDPg861IM6UzpnOkc6mzp/Ooc6VzqTOmc6azpEgUlQuIM6czrXPhM+BzqwgzrrOsc65IM62zrXPjc6zzrcgz4POtSDOrM67zrvOvyDPjM+HzrfOvM6xOiDPhM6/IDAzMyDOsc69zr/Or86zzrXOuSDPhM+Mz4TOtSDPh8+Jz4HOuc+Dz4TPjCBSVCDOtc+Azq/PhM63zrTOtc+CLCDOsc67zrvOrCDOv868zqzOtM6xL862zrXPjc6zzr/Pgi/Pgc+Mz4TOsSDPg861IM60z43OvyDOv8+Hzq7OvM6xz4TOsSDOsc69z4TOuc+GzqzPg866zrXOuSDOvM61IM+Ezrcgz4PPh86tz4POtyDigJQgzrTOuc+Mz4HOuM+Jz4POtSDPjM+HzrfOvM6xIM6uIM+Dz4fOrc+DzrcuIM6gzrHPgc6xzrPOs861zrvOr86xIM+Azr/PhSDOvyAwMzMgzqzPhs63z4POtSDOp86pzqHOmc6jIFJUIM61z4DOtc65zrTOriDOv865IM+Dz4XOs86zzrXOvc61zq/PgiDPhM63z4Igzq7PhM6xzr0gzq7OtM63IM+DzrUgzrTPjc6/IFJUIM+EzrcgzrTOtc6vz4fOvc61zrkgz4TOvyBCLTAxLiBHcm91cCBJRCDPgM6/z4Ugz4DOtc+BzrnOrc+HzrXOuSDCqyPCuyDOtM61zr0gz4PPhc6zzrrPgc6vzr3Otc+EzrHOuSAozrTOuc6xz4fPic+BzrnPg8+EzrnOus+MIM+Ezr/PhSDOtc67zq3Os8+Hzr/PhTogzrcgzrvOr8+Dz4TOsSDPg8+Fzr3Osc+Bz4TOrs+DzrXPic69IM+Ezr/PhSDOtc67zrXOs866z4TOriDOtM61zr0gzq3Ph861zrkgc3BsaXRfcGFydMK3IM+Ezr8gZnJvbnQgzrPPgc6sz4bOtc65IM68z4zOvc6/IM6zz4HOrM68zrzOsc+EzrEsIM+IzrfPhs6vzrEsIMKrLcK7LCDCq3zCuyDOus6xzrkgwqsswrspLiBpZHMgPSBsZWdhY3lfaWQgzrrOsc65IM+Ez4nOvSDOtM+Nzr8gz4DOsc+BzrHOs86zzrXOu865z47OvSDOus6szrjOtSDOts61z43Os86/z4XPgi4=', 'base64'), 'UTF8'),
     NULL,
     true,
     NULL);
  GET DIAGNOSTICS n = ROW_COUNT;
  IF n <> 1 THEN RAISE EXCEPTION '066: B-77 inserted % rows', n; END IF;

  -- 3. PROOFS inside the block: any failure rolls back everything above.
  -- 3a. each walk: the SAME function (oid) whose live text = replace(old text, condition), computed
  --     here from the old text AND equal to the md5 measured on the copy; the condition is there
  --     once and the old one is gone; swapping back gives the old text byte for byte (the
  --     rollback's way back); every attribute as before.
  IF to_regprocedure('public.rt_create_from_order()') IS DISTINCT FROM fn_create
     OR pg_get_functiondef(fn_create) IS DISTINCT FROM new_create
     OR md5(pg_get_functiondef(fn_create)) <> '8e964f66556677a284eca13db70665c6'
     OR (SELECT md5(prosrc) FROM pg_proc WHERE oid = fn_create) <> '0845ec6170fd2918d21efd56856daa3e'
     OR (length(new_create) - length(replace(new_create, cond_new, ''))) <> length(cond_new)
     OR position(cond_old IN new_create) > 0
     OR replace(pg_get_functiondef(fn_create), cond_new, cond_old) IS DISTINCT FROM old_create THEN
    RAISE EXCEPTION '066 proof: rt_create_from_order is not the 7/10 text with only the base Group ID compare (md5 %)', md5(pg_get_functiondef(fn_create));
  END IF;
  IF to_regprocedure('public.rt_link_split()') IS DISTINCT FROM fn_split
     OR pg_get_functiondef(fn_split) IS DISTINCT FROM new_split
     OR md5(pg_get_functiondef(fn_split)) <> 'd8a4a03dca0e8e26d4e8d227f1287590'
     OR (SELECT md5(prosrc) FROM pg_proc WHERE oid = fn_split) <> '6f954b256f103f1c6a8f8ab400a67808'
     OR (length(new_split) - length(replace(new_split, cond_new, ''))) <> length(cond_new)
     OR position(cond_old IN new_split) > 0
     OR replace(pg_get_functiondef(fn_split), cond_new, cond_old) IS DISTINCT FROM old_split THEN
    RAISE EXCEPTION '066 proof: rt_link_split is not the 7/10 text with only the base Group ID compare (md5 %)', md5(pg_get_functiondef(fn_split));
  END IF;
  IF (SELECT concat_ws('|', oid, proowner, proacl::text, prosecdef, proconfig::text, prolang, provolatile, proisstrict,
                       proleakproof, proparallel, procost, prorows, prorettype, proargtypes::text, prokind)
        FROM pg_proc WHERE oid = fn_create) IS DISTINCT FROM attrs_create
     OR (SELECT concat_ws('|', oid, proowner, proacl::text, prosecdef, proconfig::text, prolang, provolatile, proisstrict,
                          proleakproof, proparallel, procost, prorows, prorettype, proargtypes::text, prokind)
           FROM pg_proc WHERE oid = fn_split) IS DISTINCT FROM attrs_split THEN
    RAISE EXCEPTION '066 proof: owner, grants, SECURITY DEFINER, search_path or another attribute of a walk changed';
  END IF;
  -- 3b. triggers: the same two, same text, same functions; the same count; B-54 still equals it
  SELECT string_agg(t.tgname || ':' || t.tgrelid::regclass::text || ':' || t.tgenabled::text || ':' || t.tgfoid::text || ':' || md5(pg_get_triggerdef(t.oid)), ',' ORDER BY t.oid)
    INTO tg_after FROM pg_trigger t WHERE t.tgfoid IN (fn_create, fn_split) AND NOT t.tgisinternal;
  SELECT count(*) INTO trg_after FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  IF tg_after IS DISTINCT FROM tg_before OR trg_after <> trg_before
     OR NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-54' AND red_value = trg_after AND baseline IS NULL) THEN
    RAISE EXCEPTION '066 proof: triggers changed (% -> %) or B-54 moved', trg_before, trg_after;
  END IF;
  -- 3c. the auditor row = the catalog file (md5 of the generated texts)
  IF NOT EXISTS (SELECT 1 FROM monitoring.checks k WHERE k.id = 'B-77' AND k.enabled AND NOT k.is_queue AND k.baseline IS NULL
                  AND md5(k.title||'|'||k.sql_text||'|'||coalesce(k.ids_sql,'')||'|'||coalesce(k.impact,'')||'|'||coalesce(k.next_step,'')||'|'||coalesce(k.exceptions,'')||'|'||coalesce(k.entity_table,'')||'|'||k.red_op||'|'||k.red_value::text||'|'||k.severity||'|'||k.schedule_tag)
                      = 'cd6133b37a823e99d6ca8c80600c2f06') THEN
    RAISE EXCEPTION '066 proof: B-77 does not match the catalog (tms-auditor/checks/B-77.sql)';
  END IF;
  -- 3d. nothing else moved: no order, round trip or leg written by this block
  IF (SELECT count(*) FROM public.orders) <> orders_before
     OR (SELECT count(*) FROM public.ct_round_trips) <> rts_before
     OR (SELECT count(*) FROM public.ct_rt_legs) <> legs_before THEN
    -- 066 writes none of them; a save by someone else in the same second also lands here (fails
    -- closed, nothing kept)
    RAISE EXCEPTION '066 proof: orders, round trips or legs changed while the block ran - nothing was kept; run 066 again in a few minutes, and if this repeats, stop and copy the panel to the coordinator';
  END IF;
  -- 3e. B-54 and B-77 run the way run_checks (047) runs them: guard, 10 s timeout, as
  --     tms_check_runner (SELECT only) - a missing GRANT or a refused function fails HERE, not at the
  --     first hourly run. Texts are read before the role switch (tms_check_runner cannot read
  --     schema monitoring). B-77's value is reported, not required: it measures data, not 066.
  FOR r IN SELECT id, sql_text, ids_sql FROM monitoring.checks WHERE id IN ('B-54', 'B-77') AND enabled ORDER BY id LOOP
    PERFORM monitoring.check_sql_guard(r.sql_text);
    IF r.ids_sql IS NOT NULL THEN PERFORM monitoring.check_sql_guard(r.ids_sql); END IF;
    PERFORM set_config('statement_timeout', '10000', true);
    SET LOCAL ROLE tms_check_runner;
    EXECUTE r.sql_text INTO v;
    ids := NULL;
    IF r.ids_sql IS NOT NULL THEN EXECUTE r.ids_sql INTO ids; END IF;
    RESET ROLE;
    IF v IS NULL THEN RAISE EXCEPTION '066 proof: % returned NULL', r.id; END IF;
    IF r.id = 'B-54' AND v IS DISTINCT FROM trg_after::numeric THEN
      RAISE EXCEPTION '066 proof: B-54 = % right after the migration (expected %)', v, trg_after;
    END IF;
    IF r.id = 'B-77' THEN b77 := v; b77_ids := coalesce(array_to_string(ids, ','), ''); END IF;
  END LOOP;
  IF b77 IS NULL THEN RAISE EXCEPTION '066 proof: B-77 did not run'; END IF;

  RAISE NOTICE '066 OK: rt_create_from_order + rt_link_split compare the base Group ID (same oid/owner/grants/SECURITY DEFINER/search_path); triggers % -> %, B-54 = %; B-77 = % (ids %)',
    trg_before, trg_after, trg_after, b77, b77_ids;
END;
  -- ===== end of 066 =====

  -- A: what 066 changes is there (its own proofs already raised if not; this names it in the result)
  BEGIN
    IF md5(pg_get_functiondef('public.rt_create_from_order()'::regprocedure)) = '8e964f66556677a284eca13db70665c6'
       AND md5(pg_get_functiondef('public.rt_link_split()'::regprocedure)) = 'd8a4a03dca0e8e26d4e8d227f1287590'
       AND position('split_part(n.group_id' IN (SELECT prosrc FROM pg_proc WHERE oid = 'public.rt_create_from_order()'::regprocedure)) > 0
       AND position('split_part(n.group_id' IN (SELECT prosrc FROM pg_proc WHERE oid = 'public.rt_link_split()'::regprocedure)) > 0 THEN
      ok := ok + 1; res := res || 'A ok both walks compare the base Group ID (066 md5s)'::text;
    ELSE bad := bad + 1; res := res || 'A FAIL a walk is not the 066 text'::text; END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('A ERROR ' || SQLERRM);
  END;

  -- B: no trigger was added or dropped: the count and B-54 did not move
  BEGIN
    SELECT count(*) INTO dry_n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
      JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
    IF dry_n = dry_trg_before AND (SELECT red_value FROM monitoring.checks WHERE id = 'B-54') = dry_n AND dry_b54_before = dry_trg_before THEN
      ok := ok + 1; res := res || format('B ok triggers %s = %s, B-54 %s', dry_trg_before, dry_n, dry_b54_before);
    ELSE bad := bad + 1; res := res || format('B FAIL triggers %s -> %s, B-54 %s -> %s', dry_trg_before, dry_n, dry_b54_before,
                                             (SELECT red_value FROM monitoring.checks WHERE id = 'B-54')); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('B ERROR ' || SQLERRM);
  END;

  -- C: data 066 must not touch - same fingerprint after the block as before it. A save by someone
  --    else during these seconds also changes it (fails closed): the FAIL text says what to do.
  BEGIN
    IF (SELECT md5(
    coalesce((SELECT string_agg(md5(to_jsonb(x)::text), ',' ORDER BY x.id) FROM public.orders x), '')
 || coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.ct_round_trips x), '')
 || coalesce((SELECT string_agg(to_jsonb(x)::text, ',' ORDER BY x.id) FROM public.ct_rt_legs x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks WHERE id <> 'B-77'), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) = dry_fp_before THEN
      ok := ok + 1; res := res || 'C ok orders, round trips, legs, auditor rows, sequences unchanged'::text;
    ELSE bad := bad + 1; res := res || 'C FAIL data changed during the dry run - 066 itself, or a save by someone else in those seconds: if A, B and D are ok, wait 5 minutes and run the dry run once more; if C fails again, stop and copy the panel to the coordinator'::text; END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('C ERROR ' || SQLERRM);
  END;

  -- D: B-77 is the catalog row and runs as run_checks runs it (guard, as tms_check_runner); value reported
  BEGIN
    IF NOT EXISTS (SELECT 1 FROM monitoring.checks k WHERE k.id = 'B-77' AND k.enabled
                    AND md5(k.title||'|'||k.sql_text||'|'||coalesce(k.ids_sql,'')||'|'||coalesce(k.impact,'')||'|'||coalesce(k.next_step,'')||'|'||coalesce(k.exceptions,'')||'|'||coalesce(k.entity_table,'')||'|'||k.red_op||'|'||k.red_value::text||'|'||k.severity||'|'||k.schedule_tag)
                        = 'cd6133b37a823e99d6ca8c80600c2f06') THEN
      bad := bad + 1; res := res || 'D FAIL B-77 missing or not the catalog row'::text;
    ELSE
      -- texts read before the role switch: tms_check_runner cannot read schema monitoring
      SELECT sql_text, ids_sql INTO dry_sql, dry_ids_sql FROM monitoring.checks WHERE id = 'B-77';
      PERFORM monitoring.check_sql_guard(dry_sql);
      PERFORM monitoring.check_sql_guard(dry_ids_sql);
      SET LOCAL ROLE tms_check_runner;
      EXECUTE dry_sql INTO dry_v;
      EXECUTE dry_ids_sql INTO dry_ids;
      RESET ROLE;
      ok := ok + 1; res := res || format('D ok B-77 = catalog, value %s (ids %s)', dry_v, coalesce(array_to_string(dry_ids, ','), ''));
    END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('D ERROR ' || SQLERRM);
  END;

  RAISE EXCEPTION 'DRY RUN 066 finished - EVERYTHING UNDONE, nothing kept. Result: % OK, % FAIL  ||  %', ok, bad, array_to_string(res, '  |  ');
END
$dry$;
