-- 067 DRY RUN - GENERATED by worker/migrations/drafts/tools/build-067-dryrun.mjs from 067_stop_delay_reason.sql.
-- DO NOT EDIT BY HAND: edit 067 and regenerate (tms-auditor/test/dryrun-067.test.mjs fails on any drift).
--
-- WHAT: 067's own DO block, statement for statement (every guard, the ALTER TABLE, every proof, B-54 run as
--   tms_check_runner), wrapped in ONE outer DO block that first fingerprints data 067 must not touch, then
--   checks the result, and ENDS WITH A DELIBERATE ERROR. The error rolls the whole block back: NOTHING it did
--   is kept (no column, no CHECK).
-- WHEN: the same evening, AFTER 15:00 (the team works 05:30-14:30), BEFORE 067_stop_delay_reason.sql. It
--   uses the same lock_timeout as 067 (5 s, then it gives up - run it again a little later).
-- WHY ONE DO BLOCK: the Supabase SQL editor is NOT atomic across statements (lesson 056), but ONE DO
--   block is ONE statement: its final error undoes everything inside it.
-- EXPECTED (the red ERROR is deliberate):
--   ERROR: P0001: DRY RUN 067 finished - EVERYTHING UNDONE, nothing kept. Result: 4 OK, 0 FAIL  ||  A ok ... | B ok triggers 35 = 35, B-54 35 | C ok ... | D ok ...
--   Anything with FAIL or ERROR in it: do NOT run 067, copy the panel to the coordinator.
--   ONE exception: "3 OK, 1 FAIL" where the FAIL is C alone (A, B, D ok). C fingerprints every order stop, the
--   auditor rows and every public sequence while the block runs, so ONE stop saved by someone else in those
--   seconds turns it red - it fails closed, nothing was kept. Wait 5 minutes and run the dry run once more;
--   if C fails again, copy the panel to the coordinator.
--   A different message altogether ("067: ...", "067 proof: ...", a lock timeout) is the guard or proof of
--   067 that stopped - exactly what 067 itself would have said. Do NOT run 067.
-- AFTER: SELECT that nothing was kept - order_stops has no column named delay_reason.
-- Scenarios: A 067's columns and CHECKs exist inside the block; B the trigger count did not move and B-54
--   equals it; C data 067 must not touch is unchanged (every order stop minus the three new keys, every
--   auditor row, every public sequence's last_value); D one probe stop (id -6799, OVERRIDING SYSTEM VALUE: no
--   sequence moves; undone inside D) takes "loading_wait" with responsibility "client" and refuses an unknown
--   code and "other" without a note.

DO $dry$
DECLARE
  ok int := 0; bad int := 0; res text[] := '{}';
  dry_fp_before text; dry_b54_before int; dry_trg_before int; dry_n int; dry_got text; dry_tries text;
BEGIN
  -- the B-54 value and the trigger count 067 will meet, and the data it must leave alone
  SELECT red_value INTO dry_b54_before FROM monitoring.checks WHERE id = 'B-54';
  SELECT count(*) INTO dry_trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  SELECT (SELECT md5(
    coalesce((SELECT string_agg(md5((to_jsonb(x) - 'delay_reason' - 'delay_note' - 'delay_responsibility')::text), ',' ORDER BY x.id) FROM public.order_stops x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) INTO dry_fp_before;

  -- ===== 067_stop_delay_reason.sql, its DO block verbatim (a nested block: its errors stop everything) =====
DECLARE
  trg_before int; trg_after int; b54_before numeric; b54_baseline numeric;
  stops_before bigint; delayed_before bigint; fp_before text;
  acl_before text; owner_before oid; colacl_before text; cons_before text;
  n bigint; r record; v numeric; got text;
BEGIN
  PERFORM set_config('search_path', 'public, extensions', true);
  -- ALTER TABLE takes an ACCESS EXCLUSIVE lock on order_stops (and rewrites it for the generated
  -- column): behind an idle open transaction it would wait forever while every stop read queues
  -- behind it. Give up after 5 s - the whole block rolls back; run it again a little later.
  PERFORM set_config('lock_timeout', '5s', true);

  -- 0. GUARDS (SELECT only)
  IF to_regclass('monitoring.checks') IS NULL THEN
    RAISE EXCEPTION '067: monitoring.checks does not exist (047 must run first)';
  END IF;
  IF to_regclass('public.order_stops') IS NULL
     OR (SELECT relkind FROM pg_class WHERE oid = 'public.order_stops'::regclass) <> 'r' THEN
    RAISE EXCEPTION '067: public.order_stops is not a plain table - stop';
  END IF;
  IF EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.order_stops'::regclass AND attnum > 0
              AND NOT attisdropped AND attname IN ('delay_reason', 'delay_note', 'delay_responsibility'))
     OR EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.order_stops'::regclass AND conname LIKE 'order_stops\_delay\_%') THEN
    RAISE EXCEPTION '067: already applied (order_stops has a delay_ column or an order_stops_delay_ constraint)';
  END IF;
  -- The rule "a reason only on a Delayed stop" leans on performance and its CHECK as measured.
  IF NOT EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = 'public.order_stops'::regclass AND attname = 'performance'
                  AND NOT attisdropped AND atttypid = 'text'::regtype)
     OR NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conrelid = 'public.order_stops'::regclass
                     AND conname = 'order_stops_performance_check' AND contype = 'c' AND convalidated
                     AND regexp_replace(pg_get_constraintdef(oid), '\s+', ' ', 'g')
                         = 'CHECK ((performance = ANY (ARRAY[''On Time''::text, ''Delayed''::text])))') THEN
    RAISE EXCEPTION '067: order_stops.performance or its CHECK (On Time / Delayed) is not what was measured - re-measure';
  END IF;
  -- B-54 counts enabled non-internal triggers in public; run_checks compares against
  -- coalesce(baseline, red_value), so a baseline would hide a change. 35 since 057 + 060 + 063
  -- (065 re-created one under its own name, 064/066 none).
  SELECT count(*) INTO trg_before FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  SELECT red_value, baseline INTO b54_before, b54_baseline FROM monitoring.checks WHERE id = 'B-54';
  IF trg_before <> 35 OR b54_before IS DISTINCT FROM 35 OR b54_baseline IS NOT NULL THEN
    RAISE EXCEPTION '067: expected 35 enabled triggers in public = B-54 red_value, no baseline; found % triggers, B-54 red_value % baseline % - something changed triggers or B-54, re-measure',
      trg_before, b54_before, b54_baseline;
  END IF;
  -- what must not move: owner, table ACL, column ACLs, the existing constraints, every row
  SELECT relacl::text, relowner INTO acl_before, owner_before FROM pg_class WHERE oid = 'public.order_stops'::regclass;
  SELECT coalesce(string_agg(attname || '=' || attacl::text, ',' ORDER BY attnum), '') INTO colacl_before
    FROM pg_attribute WHERE attrelid = 'public.order_stops'::regclass AND attnum > 0 AND NOT attisdropped AND attacl IS NOT NULL;
  SELECT string_agg(conname || ':' || pg_get_constraintdef(oid), ';' ORDER BY conname) INTO cons_before
    FROM pg_constraint WHERE conrelid = 'public.order_stops'::regclass;
  SELECT count(*), count(*) FILTER (WHERE performance = 'Delayed'),
         md5(coalesce(string_agg(md5(to_jsonb(s)::text), ',' ORDER BY s.id), ''))
    INTO stops_before, delayed_before, fp_before FROM public.order_stops s;

  -- 1. THE FACT, on the table. The CASE is THE list (the front's drift test reads these WHEN lines).
  ALTER TABLE public.order_stops
    ADD COLUMN delay_reason text,
    ADD COLUMN delay_note text,
    ADD COLUMN delay_responsibility text GENERATED ALWAYS AS (CASE delay_reason
      WHEN 'vehicle_breakdown' THEN 'us'
      WHEN 'driver_hours' THEN 'us'
      WHEN 'planning_error' THEN 'us'
      WHEN 'previous_stop' THEN 'us'
      WHEN 'cargo_not_ready' THEN 'client'
      WHEN 'loading_wait' THEN 'client'
      WHEN 'order_change' THEN 'client'
      WHEN 'missing_docs' THEN 'client'
      WHEN 'unloading_wait' THEN 'consignee'
      WHEN 'closed_refused' THEN 'consignee'
      WHEN 'border_queue' THEN 'borders'
      WHEN 'customs' THEN 'borders'
      WHEN 'traffic' THEN 'external'
      WHEN 'weather' THEN 'external'
      WHEN 'ferry_train' THEN 'external'
      WHEN 'strike_roads' THEN 'external'
      WHEN 'other' THEN 'other'
    END) STORED,
    ADD CONSTRAINT order_stops_delay_reason_check
      CHECK (delay_reason IS NULL OR delay_responsibility IS NOT NULL),
    ADD CONSTRAINT order_stops_delay_other_note_check
      CHECK (delay_reason IS DISTINCT FROM 'other' OR coalesce(delay_note ~ '[^[:space:]]', false)),
    ADD CONSTRAINT order_stops_delay_only_delayed_check
      CHECK ((delay_reason IS NULL OR performance IS NOT DISTINCT FROM 'Delayed')
             AND (delay_note IS NULL OR delay_reason IS NOT NULL));
  COMMENT ON COLUMN public.order_stops.delay_reason IS
    'Why the stop was late: one of the 17 codes of delay_responsibility (Daily Ops, dispatcher Pantelis / owner 9/10/2026, migration 067). Only on a Delayed stop. Facade label: Delay Reason.';
  COMMENT ON COLUMN public.order_stops.delay_note IS
    'Free text beside delay_reason; required (non-blank) when delay_reason = other (migration 067). Facade label: Delay Note.';
  COMMENT ON COLUMN public.order_stops.delay_responsibility IS
    'Whose the delay was - us / client / consignee / borders / external / other - DERIVED from delay_reason by the base (generated, never written; migration 067). Facade label: Delay Responsibility (read-only).';

  -- 2. PROOFS inside the block: any failure rolls back everything above.
  -- 2a. the three columns: text; reason and note plain and nullable; responsibility generated STORED
  --     with the CASE above (whitespace collapsed, so the proof does not depend on the deparser's layout)
  IF (SELECT count(*) FROM pg_attribute WHERE attrelid = 'public.order_stops'::regclass AND NOT attisdropped
        AND atttypid = 'text'::regtype AND NOT attnotnull AND atthasdef = (attname = 'delay_responsibility')
        AND ((attname IN ('delay_reason', 'delay_note') AND attgenerated = '')
          OR (attname = 'delay_responsibility' AND attgenerated = 's'))) <> 3 THEN
    RAISE EXCEPTION '067 proof: the three columns are not delay_reason/delay_note text NULL + delay_responsibility text generated STORED';
  END IF;
  SELECT btrim(regexp_replace(pg_get_expr(d.adbin, d.adrelid), '\s+', ' ', 'g')) INTO got
    FROM pg_attribute a JOIN pg_attrdef d ON d.adrelid = a.attrelid AND d.adnum = a.attnum
   WHERE a.attrelid = 'public.order_stops'::regclass AND a.attname = 'delay_responsibility' AND NOT a.attisdropped;
  IF md5(got) <> 'd5f97f72bb703e385c95975e0241b2a8' THEN
    RAISE EXCEPTION '067 proof: the generated responsibility is not the CASE measured on the copy (md5 %): %', md5(got), got;
  END IF;
  -- 2b. constraints: the three new ones validated, exactly as written; every older one unchanged
  SELECT string_agg(conname || ':' || btrim(regexp_replace(pg_get_constraintdef(oid), '\s+', ' ', 'g')) || ';', '' ORDER BY conname) INTO got
    FROM pg_constraint WHERE conrelid = 'public.order_stops'::regclass AND conname LIKE 'order_stops\_delay\_%' AND contype = 'c' AND convalidated;
  IF md5(coalesce(got, '')) <> 'e17368e86ebf64f8131add2eb9426615' THEN
    RAISE EXCEPTION '067 proof: the three CHECKs are not the ones measured on the copy (md5 %): %', md5(coalesce(got, '')), got;
  END IF;
  IF (SELECT string_agg(conname || ':' || pg_get_constraintdef(oid), ';' ORDER BY conname)
        FROM pg_constraint WHERE conrelid = 'public.order_stops'::regclass AND conname NOT LIKE 'order_stops\_delay\_%')
     IS DISTINCT FROM cons_before THEN
    RAISE EXCEPTION '067 proof: an existing constraint of order_stops changed';
  END IF;
  -- 2c. born closed: same owner and table ACL, no column-level ACL anywhere new or old
  IF (SELECT relacl::text FROM pg_class WHERE oid = 'public.order_stops'::regclass) IS DISTINCT FROM acl_before
     OR (SELECT relowner FROM pg_class WHERE oid = 'public.order_stops'::regclass) IS DISTINCT FROM owner_before
     OR (SELECT coalesce(string_agg(attname || '=' || attacl::text, ',' ORDER BY attnum), '') FROM pg_attribute
          WHERE attrelid = 'public.order_stops'::regclass AND attnum > 0 AND NOT attisdropped AND attacl IS NOT NULL)
        IS DISTINCT FROM colacl_before THEN
    RAISE EXCEPTION '067 proof: owner, table ACL or a column ACL of order_stops changed';
  END IF;
  -- the Worker's path (service_role through PostgREST): reads all three, writes reason and note.
  -- A missing privilege here would be a 500 on every delay save after the Worker deploy.
  IF NOT has_column_privilege('service_role', 'public.order_stops', 'delay_reason', 'SELECT')
     OR NOT has_column_privilege('service_role', 'public.order_stops', 'delay_note', 'SELECT')
     OR NOT has_column_privilege('service_role', 'public.order_stops', 'delay_responsibility', 'SELECT')
     OR NOT has_column_privilege('service_role', 'public.order_stops', 'delay_reason', 'UPDATE')
     OR NOT has_column_privilege('service_role', 'public.order_stops', 'delay_note', 'UPDATE')
     OR NOT has_column_privilege('service_role', 'public.order_stops', 'delay_reason', 'INSERT')
     OR NOT has_column_privilege('service_role', 'public.order_stops', 'delay_note', 'INSERT') THEN
    RAISE EXCEPTION '067 proof: service_role (the Worker) cannot read the three columns or write delay_reason / delay_note';
  END IF;
  -- nobody else: anon and authenticated (the public API keys) reach none of the three
  FOR r IN SELECT rol, col, priv FROM unnest(ARRAY['anon', 'authenticated']) rol,
             unnest(ARRAY['delay_reason', 'delay_note', 'delay_responsibility']) col,
             unnest(ARRAY['SELECT', 'INSERT', 'UPDATE', 'REFERENCES']) priv LOOP
    IF has_column_privilege(r.rol, 'public.order_stops', r.col, r.priv) THEN
      RAISE EXCEPTION '067 proof: % has % on order_stops.% - the new columns must be born closed', r.rol, r.priv, r.col;
    END IF;
  END LOOP;
  -- 2d. data: same rows, same values (the rewrite moved nothing), the new columns empty everywhere
  SELECT count(*) INTO n FROM public.order_stops;
  IF n <> stops_before
     OR (SELECT count(*) FROM public.order_stops WHERE performance = 'Delayed') <> delayed_before
     OR (SELECT md5(coalesce(string_agg(md5((to_jsonb(s) - 'delay_reason' - 'delay_note' - 'delay_responsibility')::text), ',' ORDER BY s.id), ''))
           FROM public.order_stops s) IS DISTINCT FROM fp_before
     OR EXISTS (SELECT 1 FROM public.order_stops WHERE delay_reason IS NOT NULL OR delay_note IS NOT NULL OR delay_responsibility IS NOT NULL) THEN
    RAISE EXCEPTION '067 proof: order_stops rows changed (% -> %) or a new column is not empty - nothing was kept; if a save by someone else landed in these seconds, run 067 again in a few minutes', stops_before, n;
  END IF;
  -- 2e. triggers: the same count, B-54 still equals it (not written), and B-54 runs the way
  --     run_checks (047) runs it: guard, 10 s timeout, as tms_check_runner. The text is read before
  --     the role switch (tms_check_runner cannot read schema monitoring).
  SELECT count(*) INTO trg_after FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
   WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
  IF trg_after <> trg_before OR NOT EXISTS (SELECT 1 FROM monitoring.checks WHERE id = 'B-54' AND red_value = trg_after AND baseline IS NULL) THEN
    RAISE EXCEPTION '067 proof: trigger count % -> % (expected unchanged), or B-54 moved', trg_before, trg_after;
  END IF;
  FOR r IN SELECT id, sql_text FROM monitoring.checks WHERE id = 'B-54' AND enabled LOOP
    PERFORM monitoring.check_sql_guard(r.sql_text);
    PERFORM set_config('statement_timeout', '10000', true);
    SET LOCAL ROLE tms_check_runner;
    EXECUTE r.sql_text INTO v;
    RESET ROLE;
    IF v IS DISTINCT FROM trg_after::numeric THEN
      RAISE EXCEPTION '067 proof: B-54 = % right after the migration (expected %)', v, trg_after;
    END IF;
  END LOOP;

  RAISE NOTICE '067 OK: order_stops.delay_reason / delay_note / delay_responsibility (generated) + 3 CHECKs; % stops, % Delayed, 0 with a reason; ACL and owner unchanged, new columns closed to anon/authenticated; triggers % -> %, B-54 = %',
    n, delayed_before, trg_before, trg_after, trg_after;
END;
  -- ===== end of 067 =====

  -- A: what 067 adds is there (its own proofs already raised if not; this names it in the result)
  BEGIN
    IF (SELECT count(*) FROM pg_attribute WHERE attrelid = 'public.order_stops'::regclass AND NOT attisdropped
          AND attname IN ('delay_reason', 'delay_note', 'delay_responsibility')) = 3
       AND (SELECT count(*) FROM pg_constraint WHERE conrelid = 'public.order_stops'::regclass AND convalidated
             AND conname IN ('order_stops_delay_reason_check', 'order_stops_delay_other_note_check', 'order_stops_delay_only_delayed_check')) = 3 THEN
      ok := ok + 1; res := res || 'A ok 3 delay columns (responsibility generated) + 3 CHECKs'::text;
    ELSE bad := bad + 1; res := res || 'A FAIL a delay column or CHECK is missing'::text; END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('A ERROR ' || SQLERRM);
  END;

  -- B: no trigger was added or dropped: the count and B-54 did not move
  BEGIN
    SELECT count(*) INTO dry_n FROM pg_trigger t JOIN pg_class c ON c.oid = t.tgrelid
      JOIN pg_namespace ns ON ns.oid = c.relnamespace WHERE NOT t.tgisinternal AND t.tgenabled <> 'D' AND ns.nspname = 'public';
    IF dry_n = dry_trg_before AND (SELECT red_value FROM monitoring.checks WHERE id = 'B-54') = dry_n AND dry_b54_before = dry_trg_before THEN
      ok := ok + 1; res := res || format('B ok triggers %s = %s, B-54 %s', dry_trg_before, dry_n, dry_b54_before);
    ELSE bad := bad + 1; res := res || format('B FAIL triggers %s -> %s, B-54 %s -> %s', dry_trg_before, dry_n, dry_b54_before,
                                             (SELECT red_value FROM monitoring.checks WHERE id = 'B-54')); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('B ERROR ' || SQLERRM);
  END;

  -- C: data 067 must not touch - same fingerprint after the block as before it. A save by someone
  --    else during these seconds also changes it (fails closed): the FAIL text says what to do.
  BEGIN
    IF (SELECT md5(
    coalesce((SELECT string_agg(md5((to_jsonb(x) - 'delay_reason' - 'delay_note' - 'delay_responsibility')::text), ',' ORDER BY x.id) FROM public.order_stops x), '')
 || coalesce((SELECT string_agg(concat_ws(':', id, md5(sql_text), md5(coalesce(ids_sql, '')), red_value, baseline, enabled), ',' ORDER BY id) FROM monitoring.checks), '')
 || coalesce((SELECT string_agg(s.sequencename || '=' || coalesce(s.last_value::text, '-'), ',' ORDER BY s.sequencename) FROM pg_sequences s WHERE s.schemaname = 'public'), ''))) = dry_fp_before THEN
      ok := ok + 1; res := res || 'C ok order stops (minus the new keys), auditor rows, sequences unchanged'::text;
    ELSE bad := bad + 1; res := res || 'C FAIL data changed during the dry run - 067 itself, or a save by someone else in those seconds: if A, B and D are ok, wait 5 minutes and run the dry run once more; if C fails again, stop and copy the panel to the coordinator'::text; END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('C ERROR ' || SQLERRM);
  END;

  -- D: the rules act on a real write - one probe stop, undone by the inner error (C was read before it)
  BEGIN
    dry_tries := '';
    BEGIN
      INSERT INTO public.order_stops (id, legacy_id, performance, delay_reason) OVERRIDING SYSTEM VALUE
        VALUES (-6799, 'recTEST067-DRY', 'Delayed', 'loading_wait') RETURNING delay_responsibility INTO dry_got;
      IF dry_got IS DISTINCT FROM 'client' THEN dry_tries := dry_tries || ' loading_wait->' || coalesce(dry_got, 'NULL'); END IF;
      BEGIN
        UPDATE public.order_stops SET delay_reason = 'lost_keys' WHERE id = -6799;
        dry_tries := dry_tries || ' unknown code accepted';
      EXCEPTION WHEN check_violation THEN NULL;
      END;
      BEGIN
        UPDATE public.order_stops SET delay_reason = 'other', delay_note = NULL WHERE id = -6799;
        dry_tries := dry_tries || ' other without note accepted';
      EXCEPTION WHEN check_violation THEN NULL;
      END;
      RAISE EXCEPTION USING ERRCODE = 'P0067', MESSAGE = 'dry run probe undone';
    EXCEPTION WHEN SQLSTATE 'P0067' THEN NULL;
    END;
    IF dry_tries = '' AND NOT EXISTS (SELECT 1 FROM public.order_stops WHERE id = -6799) THEN
      ok := ok + 1; res := res || 'D ok probe: loading_wait -> client; unknown code and other without note refused; probe undone'::text;
    ELSE bad := bad + 1; res := res || ('D FAIL' || dry_tries); END IF;
  EXCEPTION WHEN others THEN bad := bad + 1; res := res || ('D ERROR ' || SQLERRM);
  END;

  RAISE EXCEPTION 'DRY RUN 067 finished - EVERYTHING UNDONE, nothing kept. Result: % OK, % FAIL  ||  %', ok, bad, array_to_string(res, '  |  ');
END
$dry$;
